### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by wernerbarnard** [zzzprojects/EntityFramework-Extensions#123]
Hi - it seems that the Timeout isn't being honoured anymore?

In the DbContext I have: (as a test)

```c#
Database.SetCommandTimeout(60 * 60 * 6);
```

The specific execution is: (I tried adding BatchTimeout here - no difference)

```c#
await _dbContext.BulkSaveChangesAsync(o =>
{
    o.BatchSize = 5000;
    o.IncludeGraph = true;
    o.BatchTimeout = 60 * 60 * 6;
});
```

This is all code that worked before, only difference is the .net core 2.1 upgrade?

```
System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period
 elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out
         --- End of inner exception stack trace ---
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
         at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at .(DbCommand , CommandBehavior , BulkOperation , Int32 )
         at .(Boolean , String[] )
         at Z.BulkOperations.BulkOperation.()
         --- End of inner exception stack trace ---
         at Z.BulkOperations.BulkOperation.()
         at Z.BulkOperations.BulkOperation.()
         at .[](DbContext this, IEnumerable`1 , Action`1 )
         at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
         at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
         at .(DbContext this, Action`1 )
         at .[](DbContext this, IEnumerable`1 , Action`1 )
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
      --- End of stack trace from previous location where exception was thrown ---
         at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
```

**System:**

    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>7.2</LangVersion>

    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
    <PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="2.1.21" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="1.7.20" />

Host OS: Windows 10 Fall update & Server 2016
SQL Server 2016 Enterprise & 2017 Developer

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

When using `IncludeGraph`, you need to include options in the `IncludeGraphBuilder`

See: http://entityframework-extensions.net/include-graph

Example:

```csharp
await _dbContext.BulkSaveChangesAsync(o =>
{
	o.IncludeGraph = true;
	
	options.IncludeGraphOperationBuilder = operation =>
	{
		var bulk = (BulkOperation)operation;
		bulk.BatchSize = 5000;
		bulk.BatchTimeout = 60 * 60 * 6;		
	};
});
```

Let me know if that solves your problem.

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Exactly the same error persists with setting the options that way - the error occurs +/- 30s after starting.

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

We tried a few scenarios but it seems we always honor the timeout.

Could you try on your side by logging the SQL executed? You will find out the timeout used inside the log. Perharp that will help us to find out what we are missing.

```csharp
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace Z.Lab.EFCore20
{
    public class Request_Timeout
    {
        public static void Execute()
        {
            // CLEAR
            using (var ctx = new CurrentContext())
            {
                ctx.Database.EnsureCreated();

                ctx.EntitySimples.RemoveRange(ctx.EntitySimples);
                ctx.BulkSaveChanges();
            }

            // SEED
            using (var ctx = new CurrentContext())
            {
                ctx.EntitySimples.Add(new EntitySimple {IntColumn = 1});
                ctx.EntitySimples.Add(new EntitySimple {IntColumn = 2});
                ctx.BulkSaveChanges();
            }

            // TEST
            using (var ctx = new CurrentContext())
            {
                var sb = new StringBuilder();

                var list = new List<EntitySimple>();

                for (var i = 0; i < 50; i++) list.Add(new EntitySimple {Id = i, IntColumn = i});


                // TEST 1
                //BulkOperationManager.BulkOperationBuilder = operation => operation.BatchTimeout = 301;
                //ctx.BulkInsert(list, options => options.Log += s => sb.AppendLine(s));

                // TEST 2
                //ctx.BulkInsert(list, options =>
                //{
                //    options.BatchTimeout = 301;
                //    options.Log += s => sb.AppendLine(s);
                //});

                // TEST 3
                //ctx.BulkInsert(list, options =>
                //{
                //    options.IncludeGraph = true;
                //    options.IncludeGraphOperationBuilder = builder =>
                //    {
                //        var bulk = (Z.BulkOperations.BulkOperation)builder;
                //        bulk.BatchTimeout = 301;
                //        bulk.Log += s => sb.AppendLine(s);
                //    };
                //});

                // TEST 3
                ctx.Database.SetCommandTimeout(301);
                ctx.BulkInsert(list, options => { options.Log += s => sb.AppendLine(s); });

                var log = sb.ToString();
            }
        }


        public class CurrentContext : DbContext
        {
            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }
        }

        public class EntitySimple
        {
            public int Id { get; set; }

            public int IntColumn { get; set; }
        }
    }
}
```

**Comment by wernerbarnard** [comment]
Hi - will do.
Side note - Are you referencing 2.1.1 ?  I didn’t have this issue before - it might be related to the latest stable version of EF Core?
		

		
	





On Tue, Jul 3, 2018 at 3:44 PM +0200, "Jonathan Magnan" <notifications@github.com> wrote:












Hello @wernerbarnard ,


We tried a few scenarios but it seems we always honor the timeout.


Could you try on your side by logging the SQL executed? You will find out the timeout used inside the log. Perharp that will help us to find out what we are missing.
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace Z.Lab.EFCore20
{
    public class Request_Timeout
    {
        public static void Execute()
        {
            // CLEAR
            using (var ctx = new CurrentContext())
            {
                ctx.Database.EnsureCreated();

                ctx.EntitySimples.RemoveRange(ctx.EntitySimples);
                ctx.BulkSaveChanges();
            }

            // SEED
            using (var ctx = new CurrentContext())
            {
                ctx.EntitySimples.Add(new EntitySimple {IntColumn = 1});
                ctx.EntitySimples.Add(new EntitySimple {IntColumn = 2});
                ctx.BulkSaveChanges();
            }

            // TEST
            using (var ctx = new CurrentContext())
            {
                var sb = new StringBuilder();

                var list = new List<EntitySimple>();

                for (var i = 0; i < 50; i++) list.Add(new EntitySimple {Id = i, IntColumn = i});


                // TEST 1
                //BulkOperationManager.BulkOperationBuilder = operation => operation.BatchTimeout = 301;
                //ctx.BulkInsert(list, options => options.Log += s => sb.AppendLine(s));

                // TEST 2
                //ctx.BulkInsert(list, options =>
                //{
                //    options.BatchTimeout = 301;
                //    options.Log += s => sb.AppendLine(s);
                //});

                // TEST 3
                //ctx.BulkInsert(list, options =>
                //{
                //    options.IncludeGraph = true;
                //    options.IncludeGraphOperationBuilder = builder =>
                //    {
                //        var bulk = (Z.BulkOperations.BulkOperation)builder;
                //        bulk.BatchTimeout = 301;
                //        bulk.Log += s => sb.AppendLine(s);
                //    };
                //});

                // TEST 3
                ctx.Database.SetCommandTimeout(301);
                ctx.BulkInsert(list, options => { options.Log += s => sb.AppendLine(s); });

                var log = sb.ToString();
            }
        }


        public class CurrentContext : DbContext
        {
            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }
        }

        public class EntitySimple
        {
            public int Id { get; set; }

            public int IntColumn { get; set; }
        }
    }
}

**Comment by JonathanMagnan** [comment]
Yup, I was referencing this version.

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

The log shows the Timeout as 30s for me...

```
-- CommandTimeout:30
```

I am setting the Timeout globally in the Context construct - i.e. 

```c#

        public MyDbContext()
        {
            Database.SetCommandTimeout(600);
        }

        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
            Database.SetCommandTimeout(600);
        }
```

Also tried your "test 3" from above, i.e.

```c#
            var sb = new StringBuilder();

            _context.Database.SetCommandTimeout(600);
            
            await _context.BulkInsertAsync(entities, o =>
            {
                o.IncludeGraph = true;

                o.IncludeGraphOperationBuilder = builder =>
                {
                    var bulk = (Z.BulkOperations.BulkOperation) builder;
                    bulk.Log += s => sb.AppendLine(s);
                };
            });
```

even adding this to the above, did not show it in the log as anything other than 30 for me:

```c#
bulk.BatchTimeout = 600;
```

---

Then, I tried the non-Async version..... 

```c#
var sb = new StringBuilder();

            _context.Database.SetCommandTimeout(600);
            
            _context.BulkInsert(entities, o =>
            {
                o.IncludeGraph = true;

                o.IncludeGraphOperationBuilder = builder =>
                {
                    var bulk = (Z.BulkOperations.BulkOperation) builder;
                    bulk.BatchTimeout = 600;
                    bulk.Log += s => sb.AppendLine(s);
                };
            });
```

Still I get:

```
-- CommandTimeout:30
```

Any ideas?

**Comment by JonathanMagnan** [comment]
Let begin from the start by a clean project, perhaps we will find out something that's missing.

Here is a project, could you try it and check what's your CommandTimeout:

[Request_Timeout.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/2163211/Request_Timeout.zip)

Some possible cause could be:
- You are using a profiler library that hooks on the command, we don't manage correctly the BatchTimeout for this library
- Somewhere in your code, you force the `BatchTimeout` for our library using, for example, the `PreExecute` event

Well, let see first if you still have the CommandTimeout problem with the clean project.

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Did you get the time to check the project in attachment?

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Sorry, yes, the one in the attachment works - mine doesn't, struggling to see what i'm doing differently but will get back to it soon and will post back what the issue was (whether mine or another issue)

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Do you have any news about this issue?

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Came back to this now, and getting this error after changing to your example - have you had this before?

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Ifr.Scheduler.Database.Persistence.DataContext.SchedulerDbContext' to type 'Z.BulkOperations.BulkOperation'.
```

The line that triggers the exception is:

```csharp
await _context.BulkUpdateAsync(entities, opts =>
{
    opts.IncludeGraph = true;
    opts.IncludeGraphOperationBuilder = o =>
    {
    var bulk = (Z.BulkOperations.BulkOperation) o; // <--- this one
    bulk.BatchTimeout = _config.SchedulerBatchTimeout;
};
});
```

**Comment by JonathanMagnan** [comment]
That's weird,

We never got this error.

It doesn't make sense in our API anyway that the `o` is of type object. It should be of type `BulkOperation` if that's always a `BulkOperation`. We will make this change, perhaps we will find out something that I didn't see when looking at the source.

**Comment by wernerbarnard** [comment]
@JonathanMagnan 

FYI - on `v2.1.33` of `Extensions.EFCore` I still got this issue...

I added this, and it doesn't throw the exception, and doesn't seem to affect the functionality based on a quick test.

```csharp
if (!(o is BulkOperation bulk)) 
  return;
```

**Comment by wernerbarnard** [comment]
And FYI - the timeout issue was unrelated to EF Extensions - sorry about that.

**Comment by wernerbarnard** [comment]
@JonathanMagnan some info regarding the timeout - seems it got stuck and happened executing something like this:

```csharp
await _context.Database.ExecuteSqlCommandAsync("delete from TableName;", ct);
_context.Database.ExecuteSqlCommand("DBCC CHECKIDENT('TableName', RESEED, 0);");
```

and doing BulkInsert and BulkSaveChanges after the above, in the same transaction, caused it for some reason to time out on the first query done by EF Ext - namely the one that checks columns / etc that takes milliseconds to execute ... that one also didn't respect the timeout when logged.

Moving the above and the Bulk actions into seperate transactions resolves the issue, but then it defeats the purpose of using a transaction.... (in this instance I'm refreshing a table with lots of data - probably a specific use case)

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Thank you for reporting, we will look at it.

I'm not sure if that's a normal behavior (from SQL Server) or not.

I will try to give you more info very soon.

**Comment by wernerbarnard** [comment]
@JonathanMagnan - both is actually Async, I just copied the wrong one out of methods - I had both async and non-async versions, the code that reproduced the error was both using the async one.

RE v3.1.34 - thanks, will check
