### ISSUE TITLE
BulkMerge throws NullReferenceException reference exception

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#133]
I believe this error has to do with a circular reference in the entity model, even if that value is null when being passed into BulkMerge.  The mappings and entity work fine thru EF and can be persisted and retrieved without issue.

Z.EntityFramework.Extensions.EFCore 2.1.28
EF Core 2.1.1.

Entity Code
```
public class SomeEntity
{
     public virtual int Id {get;set;}
     public virtual string Name {get;set;}
     public virtual SomeEntity Parent {get;set;}
}
```

Mapping Code
```
builder.Property(x => x.Name)
     .HasColumnName("Name");

builder.HasOne(x => x.Parent)
     .WithMany()
     .IsRequired(false)
     .HasForeignKey("ParentId");

```

Bulk Merge Code
```
public void BulkMerge(ICollection<T> entities, int batchSize)
{
      entities = SetDateTime(entities);
      Context.UnderlyingContext.BulkMerge(entities, options =>
      {
          options.BatchSize = batchSize;
          options.MergeKeepIdentity = true;
          options.InsertKeepIdentity = true;
       });
}
```

Exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at .(List`1 ,  )
   at .`1.( )
   at .Read()
   at .()
   at System.Data.SqlClient.SqlBulkCopy.ReadFromRowSourceAsync(CancellationToken cts)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at .( , SqlConnection , SqlTransaction , Int32 )
   at .( )
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at Weiss.Importers.Data.Repositories.BulkRepositoryBase`1.BulkMerge(ICollection`1 entities, Int32 batchSize)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Weiss.Data.Transactions.TransactionInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Weiss.Importers.Services.Importers.ImportServiceBase`2.<>c__DisplayClass6_0.<Import>b__0(ParsingResult`1 result)
```

**Comment by mmiller678** [comment]
Yes that resolved the issue.  Thank you.
