### ISSUE TITLE
Invalid Expression Exception when trying to cast in  IgnoreOnMergeUpdateExpression expression

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#134]
The following code results in the included exception.  How else can I express this conditional logic without using an if else around the entire BulkMerge call?  I find it difficult work with the expressions rather in some cases rather than being able to pass in the options I want directly.

Z.EntityFramework.Extensions.EFCore 2.1.28
EF Core 2.1.1.

Code
```
Context.UnderlyingContext.BulkMerge(entities, options =>
{
     options.BatchSize = batchSize;
     options.MergeKeepIdentity = true;
     options.InsertKeepIdentity = true;

     //TODO: Add expression to keep DateCreated from being overwritten
     if (typeof(IHasTimeStamp).IsAssignableFrom(typeof(T)))
     {
         options.IgnoreOnMergeUpdateExpression = e => new { ((IHasTimeStamp)e).DateCreated }; 
      }
});
```

Exception
```
System.Exception: Invalid expression.
   at .(Expression this, ParameterExpression )
   at ..(Expression )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at Weiss.Importers.Data.Repositories.BulkRepositoryBase`1.BulkMerge(ICollection`1 entities, Int32 batchSize)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Weiss.Data.Transactions.TransactionInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Weiss.Importers.Services.Importers.ImportServiceBase`2.<>c__DisplayClass6_0.<Import>b__0(ParsingResult`1 result)
```

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

The issue happen because of the following code `new { ((IHasTimeStamp)e).DateCreated };`

Unfortunately, this conversion makes it very hard for us to handle it in the code.

However, it this possible on your side to handle it:

```csharp
Expression<Func<IHasTimeStamp, object>> func = e => new {e.DateCreated};
options.LambdaIgnoreOnMergeUpdateExpression = func;
```

Using the option `LambdaIgnoreOnMergeUpdateExpression` allow you/us more flexibility.

Let me know if this workaround is good for you.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
