### ISSUE TITLE
Unable to save many-to-many relation table with BulkInsert

### ISSUE THREAD

**Issue by NicolasGauvreau** [zzzprojects/EntityFramework-Extensions#156]
Greetings,

I have a model which looks like this (slightly simplified):
```
    public class Log
    {
        public int Id { get; set; }
        public List<Tag> Tags { get; set; } = new List<Tag>();
    }

    public class Tag
    {
        public Guid Guid { get; set}
        public string Name { get; set; }
    }
```
...with the following maps (slightly simplified):
```
        public TagMap()
        {
            ToTable("Tags");
            HasKey(l => l.Guid);
        }

        public LogMap()
        {
            ToTable("Logs");
            HasKey(l => l.Id);
            Property(l => l.Id)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            HasMany<Tag>(l => l.Tags)
                .WithMany()
                .Map(ltl =>
                {
                    ltl.MapLeftKey("id_log");
                    ltl.MapRightKey("id_tag");
                    ltl.ToTable("log_tag");
                });
        }
```
To be saved in the following tables (slightly simplified):
* LOGS
  * Columns
    * ID
* TAGS
  * Columns
    * GUID
    * NAME
* LOG_TAG
  * Columns
    * ID_LOG
    * ID_TAG

I'm attempting to save a list of logs using the bulk methods. The logs reuse existing tags, so for a given log, I would expect an ```INSERT``` into ```LOGS``` and ```LOG_TAG```. However, only the ```LOGS``` table is updated (the ```LOG_TAG``` table remains empty).

I've tried:
* #### BulkInsert
  ```
            dbContext.BulkInsert(logs);
  ```
  which only inserts the records in the ```LOGS``` table.
* #### BulkInsert (IncludeGraph = true)
  ```
            dbContext.BulkInsert(logs, options => {
                options.IncludeGraph = true;
                options.UnsafeMode = true;
            });
  ```
  which fails because it tries to insert a tag with an existing primary key in the ```TAGS``` table.
* #### BulkInsert (IncludeGraph = true + Tag ReadOnly)
  ```
            dbContext.BulkInsert(logs, options => {
                options.IncludeGraph = true;
                options.UnsafeMode = true;
                options.IncludeGraphOperationBuilder = bulk =>
                {
                    if (bulk is BulkOperation<Tag> bulkTag)
                    {
                        bulkTag.IsReadOnly = true;
                    }
                };
            });
  ```
  which fails with the following:
  ```
  System.Exception
    HResult=0x80131500
    Message=An error occurred while updating the entries. See the inner exception for details.
    Source=Z.EntityFramework.Extensions
    StackTrace:
     at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )
     at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
     at Cyme.Server.Common.Public.Repository.LogRepository.BulkInsert(IEnumerable`1 logs) in 
  C:\Dev\Git\cyme-server\Cyme.Server.Common.Public\Repository\LogRepository.cs:line 50

  Inner Exception 1:
  TargetInvocationException: Exception has been thrown by the target of an invocation.
    StackTrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, 
  Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, 
  Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, 
  Object[] parameters, CultureInfo culture)
     at .[](BulkOperation`1 this, DbContext , List`1 , Boolean , List`1 , Type , String )
     at .`1.(SchemaEntityType )
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at .[](DbContext this, BulkOperation`1 , IEnumerable`1 , List`1 )
     at .[](BulkOperation`1 this, DbContext , IEnumerable`1 , List`1 )
     at DbContextExtensions.[](DbContext this, IEnumerable`1 , Action`1 , List`1 )
     at .(DbContext , List`1 , List`1 , Action`1 , Boolean )
     at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )

  Inner Exception 2:
  Exception: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com
    StackTrace:    at .( , DbCommand )
     at .( , DbCommand )
     at .Execute(List`1 actions)
     at .(List`1 )
     at Z.BulkOperations.BulkOperation.Execute()
     at Z.BulkOperations.BulkOperation.BulkInsert()
     at .[](BulkOperation`1 this, DbContext , List`1 , Boolean , List`1 , Type , String )
     at Z.EntityFramework.Extensions.PublicInternalBulkOperationManager.BulkInsertCast[T](BulkOperation`1 this, DbContext context, List`1 list, Boolean isManager, List`1 entitiesToUpdate, Type type, String typeName)

### NOTE: It does work when I do the following:
```
            DbContext.Set<Log>().AddRange(logs);
            DbContext.BulkSaveChanges();
```

**Comment by JonathanMagnan** [comment]
Hello @NicolasGauvreau ,

Thank you for reporting. We successfully reproduced the issue (https://dotnetfiddle.net/SyUELH).

We will start to look at it within a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @NicolasGauvreau ,

The v3.16.5 has been released.

Let me know if everything is working as expected.

Best Regards,

Jonathan
