### ISSUE TITLE
Column 'ZZZ_Index' does not belong to table 

### ISSUE THREAD

**Issue by mafshin** [zzzprojects/EntityFramework-Extensions#16]
Tried to do a simple bulk insert via `BulkSaveChanges`or `BulkInsert`, I get the following exception:

```
Column 'ZZZ_Index' does not belong to table 
```

```
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at ..( , DataTable )
   at ..( , DataTable )
   at ..( , DbCommand )
   at ..(List`1 )
   at ..(List`1 )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at ..[](BulkOperation`1 , DbContext , List`1 , Boolean , List`1 , Type , String )
   at ...(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ..[](DbContext , BulkOperation`1 , IEnumerable`1 , List`1 )
   at ..[](BulkOperation`1 , DbContext , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
```

**Comment by zzzprojects** [comment]
Thank you mafshin for reporting,

Which database provider are you using? We did some test and everything seem to work under SQL Server/Azure?

**Comment by mafshin** [comment]
I'm using EF 6.1.3 with SQLServer

**Comment by zzzprojects** [comment]
Thank you,

I know exactly where this issue appears, but I still don't understand why this is not working in your environment or how this is happening.

My guess is something modify the SQL and make it all in lower case or upper case (which modify the case of the "ZZZ_Index" column name!).

Do you have any idea if in your environment something could change the SQL? Can you provide using SQL Profiler the SQL which is executed?

### Example
```csharp
exec sp_executesql N'MERGE INTO [dbo].[EntitySimples] AS DestinationTable
USING
(
SELECT * FROM #ZZZProjects_e7af87cb_81de_4564_bfd1_e0e1b2a0ec9d
WHERE ZZZ_Index >= @IndexStart AND ZZZ_Index <= @IndexEnd
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [IntColumn] )
    VALUES ( [IntColumn] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    INSERTED.[ID] AS [ID_zzzinserted]

;',N'@IndexStart int,@IndexEnd int',@IndexStart=0,@IndexEnd=100
```

**Comment by zzzprojects** [comment]
Closing Issue: No answer
