### ISSUE TITLE
BulkSaveChanges in Transaction with Effort

### ISSUE THREAD

**Issue by VasylBakalets** [zzzprojects/EntityFramework-Extensions#199]
Hi,

I'm using **BulkSaveChanges** in a transaction like this:

```
using (var scope =
                new TransactionScope(TransactionScopeOption.Required, TransactionScopeAsyncFlowOption.Enabled))
{
	var context = ((IObjectContextAdapter)this).ObjectContext;
	...
	await context.BulkSaveChangesAsync(cancellationToken);
	scope.Complete();
}
```

And this works perfectly in my web app with **SQL Server**, but in my tests with mocked db using **[Effort](https://www.nuget.org/packages/Effort/)** I'm getting this error:

```
System.AggregateException: One or more errors occurred. ---> System.Exception: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.EntityException: An error occurred while starting a transaction on the provider connection. See the inner exception for details. ---> System.InvalidOperationException: Ambient transaction is already set.
    at Effort.Provider.EffortTransaction..ctor(EffortConnection connection, IsolationLevel isolationLevel)
   at Effort.Provider.EffortConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<BeginTransaction>b__0(DbConnection t, BeginTransactionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.BeginTransaction(DbConnection connection, BeginTransactionInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<>c__DisplayClassf.<BeginDbTransaction>b__d()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
 --- End of inner exception stack trace ---
    at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Entity.Core.EntityClient.EntityConnection.BeginTransaction()
   at System.Data.Entity.DbContextTransaction..ctor(EntityConnection connection)
   at System.Data.Entity.Database.BeginTransaction()
   at ..(BulkOperation )
   at .(List`1 , Object , Dictionary`2 )
   at .Execute()
 --- End of inner exception stack trace ---
    at .Execute()
   at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )
   at DbContextExtensions..()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DbContextExtensions..MoveNext()

```

Is there something I'm missing or doing wrong?

**Comment by JonathanMagnan** [comment]
Hello @VasylBakalets ,

Thank you for reporting.

We are currently unsure if the issue is in EF Extensions or Effort but we will try your scenario and look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @VasylBakalets ,

The issue happens in `Effort` which doesn't support `TransactionScope`. 

Unfortunately, we have spent some time to try to support this issue but we didn't success to fix it.

We suggest you using `context.BeginTransaction()` instead which will work fine

Let me know if that can work for you.

Best Regards,

Jonathan

**Comment by VasylBakalets** [comment]
Hello @JonathanMagnan ,

Thanks for the suggestion, I will have it as a plan B.
But the interesting thing is that `await context.SaveChangesAsync(cancellationToken)`, in this case, works well :(
Are there any plans regarding the support for `TransactionScope`?

**Comment by JonathanMagnan** [comment]
You got a point.

We will looks how `Entity Framework` handle the `TransactionScope`

**Comment by VasylBakalets** [comment]
Ok, thanks
