### ISSUE TITLE
EF Core + BulkInsert + InMemory provider expects public default constructor

### ISSUE THREAD

**Issue by idesfosses** [zzzprojects/EntityFramework-Extensions#203]
Dear,

When using the Z.EntityFramework.Extensions.EFCore package in combination with the Microsoft.EntityFrameworkCore.InMemory package, I get the following exception when trying to BulkInsert objects with a private default constructor.

**Code**
```csharp
await dbContext.BulkInsertAsync(entities, options => options.SqlBulkCopyOptions = SqlBulkCopyOptions.CheckConstraints);
```

**Exception**
```
System.MissingMethodException: No parameterless constructor defined for this object.
    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
```

Having a private default constructor is allowed when persisting to SqlServer, so I was wondering if you could change it so that a private default constructor is also supported with an in memory database.

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

Thank you for reporting,

We will look at how we can handle it.

Just to make sure, your default constructors is parameterless but only private? If that's the case, it should be pretty easy to support on our side.

Best Regards,

Jonathan

**Comment by idesfosses** [comment]
Correct:

```
public class MyEntity
{
    private MyEntity() { } // used by EF

    public MyEntity(string prop1, string prop2)
    {
        // ...
    }

    // ...
}
```

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

A new version (v2.2.3) has been released.

We should now support private constructor.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by idesfosses** [comment]
Hi @JonathanMagnan ,

After updating to the latest version (2.2.3), everything works as expected.

Thanks for the quick replies!

Best regards,

Igor
