### ISSUE TITLE
EF Core BulkMergeAsync with MySql Throwing Null Pointer

### ISSUE THREAD

**Issue by rabberbock** [zzzprojects/EntityFramework-Extensions#211]
### Description
Describe the issue or proposed feature.
I am using EF Core 2.2.4 with the Pomelo (2.2.0) driver for MySql. For my tests I am using the sqlite provider (2.2.4). I am experiencing an issue with `BulkMergeAsync`, it is working in my tests, but not in the actual application.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Object reference not set to an instance of an object.
Stack trace:
 at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkMergeAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Shared.Database.ApplicationContext.BulkMergeAsync[T](IEnumerable`1 entities, Action`1 options) in ....
```

### Fiddle or Project (Optional)
If you are able, 

Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

I don't have time this second, but will try to put something together.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version: 2.2.4
- EF Extensions version: 2.2.7
- Database Provider: MySql Pomelo (2.2.0)

**Comment by JonathanMagnan** [comment]
Hello @rabberbock ,

Is it possible for your side to share some code? (You can send private code here: info@zzzprojects.com).

I currently don't think we have enough information to find what's the current issue.

Best Regards,

Jonathan
