### ISSUE TITLE
Bulk Insert/Update with IncludeGraph does not work with ValueConverter

### ISSUE THREAD

**Issue by Jagailo** [zzzprojects/EntityFramework-Extensions#218]
### Description
Hello @JonathanMagnan,

I have two entities (Orders and OrderDetails) that have DateInsert field, which is automatically filled in the database: `DateInsert DATETIME(6) NOT NULL DEFAULT utc_timestamp()`.

I also use a converter to get time in the UTС format:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var converter = new ValueConverter<DateTime, DateTime>(
        x => x.ToUniversalTime(),
        x => DateTime.SpecifyKind(x, DateTimeKind.Utc));

    modelBuilder.Entity<Order>().Property("DateInsert").HasConversion(converter);
    modelBuilder.Entity<OrderDetail>().Property("DateInsert").HasConversion(converter);
}
```

When I try to insert (`BulkInsertAsync()`) this data with the option `IncludeGraph = true`, an exception is thrown. Adding data without `IncludeGraph` works fine. Adding data through the EFCore works fine too.

### InvalidCastException
```
{System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
   at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
   at .`1.( )
   at .Read()
   at .()
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at BulkIssue.Program.Main(String[] args) in C:\Users\Jagailo\Desktop\BulkIssue\BulkIssue\Program.cs:line 21}
```

### Project for reproduce
[BulkIssue.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/3212053/BulkIssue.zip)

### Further technical details
- ASP.NET Core: 2.2
- EntityFrameworkCore.Tools: 2.2.4
- Pomelo.EntityFrameworkCore.MySql: 2.2.0
- Z.EntityFramework.Extensions.EFCore: 2.2.9
- Database: 10.3.11-MariaDB

**Comment by JonathanMagnan** [comment]
Hello @Jagailo,

Thank you for reporting.

We will look if something is missing on our side about ValueConverter.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jagailo ,

Just to give you an update.

A solution has been coded but unfortunately, it was not working as expected. We got some side effect issue.

We are still working on it. We hope that we get it fixed for next week.

**Comment by JonathanMagnan** [comment]
Hello @Jagailo ,

Sorry for the late answer,

I asked for an update today to my developer, it seems the major part of this issue was already fixed but the release was waiting for another fix due to an issue we found when adding test for your case.

The v2.5.2 has been released,

The `Object cannot be cast from DBNull to other types.` error should no longer happen.

**Comment by Jagailo** [comment]
Good job, works fine.
