### ISSUE TITLE
Saving DateTimeOffset to PostgreSQL throws exception

### ISSUE THREAD

**Issue by Bouke** [zzzprojects/EntityFramework-Extensions#226]
### Description
I have a model class with a property with type `DateTimeOffset`. The backing store is PostgreSQL. The generated database field type is `timestamp with time zone`. When doing a `BatchInsert` (or `BulkSaveChanges`), an exception is thrown.

### Exception

BatchInsert:
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at .( , DbConnection , DbTransaction )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at .[](BulkOperation`1 this, DbContext , List`1 , Boolean , List`1 , Type , String )
   at .`1.(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .[](DbContext this, BulkOperation`1 , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at (...)

Inner Exception 1:
InvalidCastException: Can't write CLR type System.DateTimeOffset with handler type TimestampHandler
```

BulkSaveChanges:
```
System.Exception
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at .Execute()
   at DbContextExtensions.BulkSaveChanges(DbContext this)
   at (...)

Inner Exception 1:
ArgumentException: Type of value has a mismatch with column typeCouldn't store <1/1/0001 12:00:00 AM +00:00> in CreatedDate Column.  Expected type is Byte[].

Inner Exception 2:
ArgumentException: Type of value has a mismatch with column type
```

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.19.0
- Database Provider: Npgsql 4.0.7, EntityFramework6.Npgsql 3.2.1.1

**Comment by JonathanMagnan** [comment]
Hello @Bouke ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Bouke ,

The v3.20.1 has been released.

Let me know if the issue is fixed on your side.

**Comment by Bouke** [comment]
Hi @JonathanMagnan thanks for the response. I'm still having issues with `DateTimeOffset`, although the exception has now changed to this:

```
NpgsqlException: The NpgsqlDbType '260' isn't present in your database. You may need to install an extension or upgrade to a newer version.

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at .( , DbConnection , DbTransaction )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at .[](BulkOperation`1 this, DbContext , List`1 , Boolean , List`1 , Type , String )
   at .`1.(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .[](DbContext this, BulkOperation`1 , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   (...)
```

I'm running Postgresql 11. The type `DateTimeOffset` is mapped to `timestamptz` in the EF library.

**Comment by JonathanMagnan** [comment]
Thank you for reporting, I will re-open the issue on our side.

**Comment by JonathanMagnan** [comment]
Hello @Bouke ,

A new version has been released.

My developer didn't success to make exactly the same issue, so if you still have it an issue with your DateTimeOffset column, are you able to provide a runnable solution so we could make sure we fix exactly your case the next release.

Best Regards,

Jonathan

**Comment by Bouke** [comment]
The issue has been resolved, thank you.
