### ISSUE TITLE
Azure AAD Token based authentication does not work with BulkInsert method

### ISSUE THREAD

**Issue by hemangmaradiya** [zzzprojects/EntityFramework-Extensions#262]
### Description
When try to invoke EntityFramework-Extenstions method Bulkinsert() with parameter pass a Entity framework DBContext object that contains Azure authentication access token for Azure SQL Server) and second paramter as a options
it is throwing exception that user is blank.

### Exception

```txt
 at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)

   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKTest poolKTest, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)

   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKTest poolKTest, DbConnectionOptions userOptions)

   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)

   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)

   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)

   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)

   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)

   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)

   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)

   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)

   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)

   at System.Data.SqlClient.SqlConnection.Open()

   at EntityFramework.BulkInsert.Providers.ProviderBase`2.Run[T](IEnumerable`1 entities, BulkInsertOptions options) in c:\dev\EntityFramework.BulkInsert\dev\Src\EntityFramework.BulkInsert\Providers\ProviderBase.cs:line 90

   at EntityFramework.BulkInsert.Extensions.BulkInsertExtension.BulkInsert[T](DbContext context, IEnumerable`1 entities, BulkInsertOptions options) in c:\dev\EntityFramework.BulkInsert\dev\Src\EntityFramework.BulkInsert\Extensions\BulkInsertExtension.cs:line 63

   at Test.DataAccess.Preview.Repository.EntityRepository.BulkInsertTargetLinks(IEnumerable`1 targetLinks) in C:\TFS\Dev\Feature\Src\Test\DataAccess\Test.DataAccess\Preview\Repository\EntityRepository.cs:line 212

   at Test.Business.ExternalPayload.Implementations.LinkBaseProcessor.ParseAndSaveTargetLocators(IEnumerable`1 targetLinkElements) in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalPayload\Implementations\LinkBaseProcessor.cs:line 465

   at Test.Business.ExternalPayload.Implementations.LinkBaseProcessor.ParseAndSaveLinkBase() in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalPayload\Implementations\LinkBaseProcessor.cs:line 155

   at Test.Business.ExternalPayload.Implementations.DocumentHandler.Publish() in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalPayload\Handlers\DocumentHandler.cs:line 307

   at Test.Business.ExternalPayload.Implementations.DocumentHandler.ProcessObject(ObjectContext processObjectContext) in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalPayload\Handlers\DocumentHandler.cs:line 107

   at Test.Business.ExternalMessageInfo.Business.Implementations.InputProcessingService.ProcessObject(PublishedMessage externalMessage, ExternalMessageInfo externalMessageInfo) in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalMessageInfo\Business\Implementations\InputProcessingService.cs:line 229

   at Test.Business.ExternalMessageInfo.Business.Implementations.InputProcessingMessageHandler.ProcessAndRemoveObject(ExternalMessageInfo externalMessageInfo, ExternalMessageInfoProcessingResult inputProcessingResult, LogUtilConfiguration logconfig, Boolean isInputQueueListener) in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalMessageInfo\Business\Implementations\InputProcessingMessageHandler.cs:line 286

   at Test.Business.ExternalMessageInfo.Business.Implementations.InputProcessingMessageHandler.Handle(ExternalMessageInfo externalMessageInfo, IServiceBusClient serviceBusClient) in C:\TFS\Dev\Feature\Src\Test\Business\Test.Business\ExternalMessageInfo\Business\Implementations\InputProcessingMessageHandler.cs:line 80
```

### Fiddle or Project (Optional)
If you are able, 

Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
-DLL Version-

EntityFramework.BulkInsert.dll
Runtime Version-v4.0.30319
DLL version- 6.0.2.8
EntityFramework.dll
Runtime Version-v4.0.30319
DLL version- 6.0.0.0
EntityFramework.Extended.dll
Runtime Version-v4.0.30319
DLL version- 6.0.0.0

**Comment by JonathanMagnan** [comment]
Hello @hemangmaradiya ,

This is the support for `Entity Framework Extensions`.

It looks you use `EntityFramework.Extended.dll` which is no longer supported since 2014 and another library than ours for your `Bulk Insert`.

I recommand you to try our library instead: https://entityframework-extensions.net/

If you still get the same issue, let us know and we will be happy to help you.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
