### ISSUE TITLE
"The Provider could not be resolved" on BulkInsertAsync

### ISSUE THREAD

**Issue by gilian1993** [zzzprojects/EntityFramework-Extensions#273]
### Description
I'm trying to do a bulk insert like so:

```
// _database is received through dependency injection.
// If I don't set the ContextFactory, it will ask me to set it. From: https://entityframework-extensions.net/context-factory
EntityFrameworkManager.ContextFactory = context => _database;
await _database.BulkInsertAsync(accounts, options =>
{
    options.InsertIfNotExists = true;
    options.ColumnPrimaryKeyExpression = customer => customer.AccountId;
});
```

However, this gives me the exception listed below.

My database is registered like so in Startup.cs:

```
var connection = _configuration["App:DatabaseKey"];
            services.AddDbContext<DatabaseContext>(options => { options.UseSqlServer(connection); },
                ServiceLifetime.Transient);
```

As you can see in the code above, my provider is added. So I'm a little clueless.

### Exception
```
System.Exception: The Provider could not be resolved. You must explicitly set the Provider.
  at at Z.BulkOperations.BulkOperation.()
  at at Z.BulkOperations.BulkOperation.Execute()
  at at Z.BulkOperations.BulkOperation.BulkInsert()
  at at .[](DbContext this, IEnumerable`1 , Action`1 )
  at at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
  at at DbContextExtensions.`1.()
  at at System.Threading.Tasks.Task.InnerInvoke()
  at at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
  at at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
  at at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
  at SomePackage.Method(SomeObject param) in C:\SomeFile.cs:76
```

### Further technical details
- EF version: 3.0.0-preview8.19405.11
- EF Extensions version: 3.0.0-preview8-03
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by JonathanMagnan** [comment]
Hello @gilian1993 ,

Unfortunately, our library didn't make the move yet for `Microsoft.EntityFrameworkCore.SqlServer` provider instead of `System.Data.SqlServer`.

We are supposing to look at it next week.

So the support is coming very soon but at this moment, there is no quick fix we can do to make it happen.

**Comment by gilian1993** [comment]
Ah, that makes sense then. Alright, good luck with the implementation :) .

**Comment by JonathanMagnan** [comment]
Hello @gilian1993 ,

Starting from the v3.0.0-preview9-02, `Microsoft.EntityFrameworkCore.SqlServer` is now supported.

Let us know if everything works as expected.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @gilian1993 ,

Did you get the chance the test latest version?
