### ISSUE TITLE
BatchSaveChanges sometimes throws an exception: SqlException: The variable name '@generated_keys' has already been declared

### ISSUE THREAD

**Issue by davidnemeti** [zzzprojects/EntityFramework-Extensions#275]
### Description
`BatchSaveChanges` throws an exception in a certain case: "_SqlException: The variable name '@generated_keys' has already been declared. Variable names must be unique within a query batch or stored procedure._"

I tried to reproduce the problem in an example project/Fiddle, but unfortunately, I was not able to simplify our real code so the problem would still occur.

However, here is the SQL which was generated by `BatchSaveChanges` (I removed the `exec sp_executesql` part from the beginning, rearranged the parameter declaration, and added newlines for better readability). So, this was generated when I was trying to add and save two `Group` and three `Card` entities to the database:

``` SQL
DECLARE @zzz_0 uniqueidentifier,@zzz_1 int,@zzz_2 nvarchar(50),@zzz_3 nvarchar(max) ,@zzz_4 bit,@zzz_5 datetimeoffset(7),@zzz_6 uniqueidentifier,@zzz_7 int,
@zzz_8 nvarchar(50),@zzz_9 nvarchar(max) ,@zzz_10 bit,@zzz_11 datetimeoffset(7),@zzz_12 uniqueidentifier,@zzz_13 int,@zzz_14 nvarchar(50),@zzz_15 nvarchar(max) ,
@zzz_16 bit,@zzz_17 datetimeoffset(7),@zzz_18 bit,@zzz_19 nvarchar(254),@zzz_20 bit,@zzz_21 bit,@zzz_22 bit,@zzz_23 bit,@zzz_24 int,@zzz_25 datetimeoffset(7),
@zzz_26 int,@zzz_27 bit,@zzz_28 nvarchar(254),@zzz_29 bit,@zzz_30 bit,@zzz_31 bit,@zzz_32 bit,@zzz_33 int,@zzz_34 datetimeoffset(7),@zzz_35 int

INSERT [dbo].[Cards]([Id], [Column1], [Column2], [Column3], [Column4], [Column5], [Column6], [Column7], [Column8], [Column9], [Column10], [Column11], [Column12], [CommonColumn13], [CommonColumn14], [CommonColumn15])
VALUES (@zzz_0, NULL, NULL, @zzz_1, NULL, NULL, @zzz_2, @zzz_3, NULL, NULL, NULL, NULL, NULL, @zzz_4, @zzz_5, NULL)

SELECT [RowVersion]
FROM [dbo].[Cards]
WHERE @@ROWCOUNT > 0 AND [Id] = @zzz_0

INSERT [dbo].[Cards]([Id], [Column1], [Column2], [Column3], [Column4], [Column5], [Column6], [Column7], [Column8], [Column9], [Column10], [Column11], [Column12], [CommonColumn13], [CommonColumn14], [CommonColumn15])
VALUES (@zzz_6, NULL, NULL, @zzz_7, NULL, NULL, @zzz_8, @zzz_9, NULL, NULL, NULL, NULL, NULL, @zzz_10, @zzz_11, NULL)

SELECT [RowVersion]
FROM [dbo].[Cards]
WHERE @@ROWCOUNT > 0 AND [Id] = @zzz_6

INSERT [dbo].[Cards]([Id], [Column1], [Column2], [Column3], [Column4], [Column5], [Column6], [Column7], [Column8], [Column9], [Column10], [Column11], [Column12], [CommonColumn13], [CommonColumn14], [CommonColumn15])
VALUES (@zzz_12, NULL, NULL, @zzz_13, NULL, NULL, @zzz_14, @zzz_15, NULL, NULL, NULL, NULL, NULL, @zzz_16, @zzz_17, NULL)

SELECT [RowVersion]
FROM [dbo].[Cards]
WHERE @@ROWCOUNT > 0 AND [Id] = @zzz_12

DECLARE @generated_keys table([Id] uniqueidentifier)

INSERT [dbo].[Groups]([CommonColumn13], [Column1], [Column2], [Column3], [Column4], [Column5], [Column6], [Column7], [Column8], [Column9], [Column10], [CommonColumn14], [CommonColumn15], [Column11])
OUTPUT inserted.[Id] INTO @generated_keys
VALUES (@zzz_18, @zzz_19, NULL, @zzz_20, @zzz_21, @zzz_22, @zzz_23, @zzz_24, NULL, NULL, NULL, @zzz_25, NULL, @zzz_26)

SELECT t.[Id], t.[ComputedColumn], t.[RowVersion]
FROM @generated_keys AS g JOIN [dbo].[Groups] AS t ON g.[Id] = t.[Id]
WHERE @@ROWCOUNT > 0

DECLARE @generated_keys table([Id] uniqueidentifier)

INSERT [dbo].[Groups]([CommonColumn13], [Column1], [Column2], [Column3], [Column4], [Column5], [Column6], [Column7], [Column8], [Column9], [Column10], [CommonColumn14], [CommonColumn15], [Column11])
OUTPUT inserted.[Id] INTO @generated_keys
VALUES (@zzz_27, @zzz_28, NULL, @zzz_29, @zzz_30, @zzz_31, @zzz_32, @zzz_33, NULL, NULL, NULL, @zzz_34, NULL, @zzz_35)

SELECT t.[Id], t.[ComputedColumn], t.[RowVersion]
FROM @generated_keys AS g JOIN [dbo].[Groups] AS t ON g.[Id] = t.[Id]
WHERE @@ROWCOUNT > 0
```

So the problem is that `@generated_keys` table variable is declared twice. But, actually, it seems to me that not only the **declaration** should be done only once, but also the **selection** from the `@generated_keys` table variable.

### Exception
```
System.Data.Entity.Core.UpdateException
  HResult=0x80131501
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at ..MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Libraries.MyDbContext.<SaveChangesAsync>d__65.MoveNext() in D:\SVN\MyProject\MyDbContext.cs:line 224

Inner Exception 1:
SqlException: The variable name '@generated_keys' has already been declared. Variable names must be unique within a query batch or stored procedure.
```

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.21.13
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

Thank you for reporting,

We will look at it

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

The v3.22.4 has been released.

Could you try it again and let us know if everything works as expected?

Best Regards,

Jonathan

**Comment by davidnemeti** [comment]
Hi @JonathanMagnan ,

The v3.22.4 has fixed the `@generated_keys` problem.

However, it seems that there are still some other problems with `BatchSaveChanges`, but I am going to open another bug ticket for them, because those problems are different from this one.
