### ISSUE TITLE
BulkMerge Exception using ColumnPrimaryKeyExpression w/ inheritance

### ISSUE THREAD

**Issue by JesseKlaasse** [zzzprojects/EntityFramework-Extensions#287]
### Description
When we have an abstract and a concrete class and using table per class inheritance, an exception occurs while using BulkMerge with a ColumnPrimaryKeyExpression. Without the ColumnPrimaryKeyExpression, it's working fine.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: An error occured while resolving ColumnPrimaryKey expression. See the inner exception for details.
Stack trace: [System.Exception: Missing Colum : ResourceId
On entity : CmGroup
On Table : [dbo].[CmGroup]]
   at Z.BulkOperations.BulkOperation.(String , Boolean , Boolean , Boolean )
   at Z.BulkOperations.BulkOperation.()

[System.Exception: An error occured while resolving ColumnPrimaryKey expression. See the inner exception for details.]
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkMerge()
   at .[](BulkOperation`1 this, DbContext , List`1 , Boolean , Type , String )
   at .[](DbContext this, BulkOperation`1 , IEnumerable`1 )
   at .[](BulkOperation`1 this, DbContext , IEnumerable`1 )
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at Program.Main() :line 28
```

### Fiddle or Project (Optional)
https://dotnetfiddle.net/l0QgX8

**Comment by JonathanMagnan** [comment]
Hello @JesseKlaasse ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JesseKlaasse ,

Unfortunately, our library doesn't support this case.

You specify a custom key expression `ResourceId` on the entity `CmGroup`

However, the table `CmGroup` doesn't contain this column. That's why our library currently throws an error for this special case.

The custom key must, unfortunately, be part of the destination table at this moment.
