### ISSUE TITLE
Bulk Merge Testing With In Memory Provider

### ISSUE THREAD

**Issue by aboru** [zzzprojects/EntityFramework-Extensions#290]
### Description
I am attempting to write some tests that use the `BulkMerge` command combined with an EF Core InMemory provider. When running the tests I get the trace shown below. I have been able to work around this by specifying an IncludeGraph/IncludeGraphOperationBuilder with the same options, even though I am not actually including the graph. This works as expected.

I would prefer to just specify my single table options instead of wrapping it up like I am including more of the entity graph. I found no documentation about testing or the in memory provider so it is very possible that I am missing something.

### Exception

```
System.Exception : Oops! InMemoryConnection.CreateDbCommand must be implemented.
   at .CreateDbCommand()
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkMergeAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at BG.Services.BuildingConnectedServices.Api.Background.Company.CompanySyncTask.ExecuteAsync(Object _) in D:\GitRepository\Development\Apis\BuildingConnectedServices\BG.Services.BuildingConnectedServices.Api\Background\Company\CompanySyncTask.cs:line 170
   at BG.Shared.Web.Hangfire.HangfireBase`1.Execute(PerformContext performContext, T parameters) in D:\GitRepository\Development\Components\BG.Shared.Web\Hangfire\HangfireBase.cs:line 71
   at BG.Shared.Web.Hangfire.HangfireBase`1.Execute(PerformContext performContext, T parameters) in D:\GitRepository\Development\Components\BG.Shared.Web\Hangfire\HangfireBase.cs:line 78
   at BG.Shared.Web.Hangfire.HangfireBase`1.Execute(PerformContext performContext, T parameters) in D:\GitRepository\Development\Components\BG.Shared.Web\Hangfire\HangfireBase.cs:line 84
   at BG.Services.BuildingConnectedServices.Test.Background.Company.CompanySyncTaskTest.ExecuteAsync_ShouldSaveReturnedData() in D:\GitRepository\Development\Apis\BuildingConnectedServices\BG.Services.BuildingConnectedServices.Test\Background\Company\CompanySyncTaskTest.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
```

### Fiddle or Project (Optional)
I do not have anything available too easily, but basically if I make a call such below I get the error as:
```
await _context.BulkMergeAsync(entities, options =>
{
    options.ColumnPrimaryKeyExpression = ...
});
```

if I change it to this format but with the same options set in the `builder` it will succeed:

```
await _context.BulkMergeAsync(entities, options =>
{
    options.IncludeGraph = true;
    options.IncludeGraphOperationBuilder = operation =>
    {
        switch (operation)
        {
            case BulkOperation<TEntity> builder:
                options.ColumnPrimaryKeyExpression = ...
                break;
            default:
                throw Exception();
        }
    };
});
```

If there is more information needed I can try to provide it.

### Further technical details
- EF version: 2.1.0
- EF Extensions version: 2.7.1
- Database Provider: Microsoft.EntityFrameworkCore.InMemory: 2.1.0

**Comment by JonathanMagnan** [comment]
Hello @aboru ,

Thank you for the information. We will try to reproduce this issue on our side.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aboru ,

The v2.7.5 has been released.

Could you try this version and let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by aboru** [comment]
I will try it out as soon as possible and let you know.

Thank you for the quick turnaround on that.

**Comment by aboru** [comment]
I was able to get this tested and it is working as expected. Thanks again for the help and quick support here.
