### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection

### ISSUE THREAD

**Issue by valmirbispo** [zzzprojects/EntityFramework-Extensions#303]
### Description
I was using SQL server and change to MariaDB. Changed only connector provider to Pomelo.EntityFrameworkCore.MySql.
All features worked. But only BulkInsertAsync not work any more.
![erro](https://user-images.githubusercontent.com/1265459/68387221-981e2780-013c-11ea-88a3-0a5335c5a799.png)

### Exception
Exception message:
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

Stack trace:
at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at .`1.(Int32 , String , Object )
   at .SetValue(Int32 position,  accessor, Object value)
   at .( , DataSet )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DbContextExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Investimentos.Investidor.Data.Repositorios.RepositorioAtivo.<Salvar>d__10.MoveNext() in C:\Users\myuser\Desktop\Projetos\MyProject\src\Repositorios\RepositorioAtivo.cs:line 73
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Investimentos.Investidor.Aplicacao.Commands.Proventos.ProventosCommandHandler.<Handle>d__3.MoveNext() in C:\Users\myuser\Desktop\Projetos\MyProject\src\Investimentos.Investidor.Aplicacao\Commands\Proventos\ProventosCommandHandler.cs:line 26
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

### Further technical details
- EF version: 3.0
- EF Extensions version: 3.0.15
- Database Provider: 3.0.0-rc3.final (Pomelo)
- Database Version: 10.4.8-MariaDB

**Comment by valmirbispo** [comment]
I commented this code and its worked:
![erro](https://user-images.githubusercontent.com/1265459/68389319-69ef1680-0141-11ea-8f90-c36bc5928081.png)

But I cant check if not exits ;(

**Comment by JonathanMagnan** [comment]
Hello @valmirbispo ,

Thank you for reporting,

We will look at what is happening.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @valmirbispo ,

My developer investigated your scenario but unfortunately was not able to reproduce the issue.

It is possible for you to look at it and check what we are missing:

[BulkInsertAsync.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/3824782/BulkInsertAsync.zip)

## Context Factory
https://entityframework-extensions.net/context-factory
Looking at your code, we have seen that you pass your current context to the `ContextFactory` which is very bad. The context factory needs a new context every time that we use for some internal use. Things that we don't want to do in your context since it has some side impact such as doing some trick with the `ChangeTracker`.

Perhaps that's your problem? 

Here are good examples of how to use the ContextFactory:

```csharp
// Using the default constructor
EntityFrameworkManager.ContextFactory = context => new CurrentContext();

// Using a constructor that requires optionsBuilder (EF Core) 
EntityFrameworkManager.ContextFactory = context =>
{
	var optionsBuilder = new DbContextOptionsBuilder<EntityContext>();
	optionsBuilder.UseSqlServer(My.ConnectionString);
	return new EntityContext(optionsBuilder.Options);
};
```

_(We are currently looking at how to avoid to use the ContextFactory in a future version of our library)_

**Comment by JonathanMagnan** [comment]
Hello @valmirbispo 

A simple follow to see if you have the time to check the project or fixed the ContextFactory issue.

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @valmirbispo,

Since our last conversation, we haven't heard from you. 

did you get the time to look at the project or fixed the ContextFactory issue? 

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @valmirbispo,

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide more information. 

Best regards,

Jon

**Comment by BurakOZN** [comment]
If you are generating the id field automatically in the db. (auto increment)
You need to add this line: options.AutoMapOutputDirection = false;
