### ISSUE TITLE
BulkMerge got error 

### ISSUE THREAD

**Issue by Belala** [zzzprojects/EntityFramework-Extensions#309]
### Description 
```
using (var context = new EntityContext())
            {
                var parentProducts = new List<Product>();

                for (var i = 0; i < 10; i++)
                {
                    Product p = new Product()
                    {
                        Name = "p-" + i,
                        Manufacturers = new List<Manufacturer>() {
                            new Manufacturer(){ Name="m1-"+i },
                             new Manufacturer(){ Name="m2-"+i },
                              new Manufacturer(){ Name="m3-"+i },
                               new Manufacturer(){ Name="m4-"+i },
                                new Manufacturer(){ Name="m5-"+i },
                                 new Manufacturer(){ Name="m6-"+i }
                        }
                    };
                    parentProducts.Add(p);
                }

                context.BulkMerge(parentProducts, options =>
                {
                    options.ColumnPrimaryKeyExpression = x => new { x.Name };
                    options.IncludeGraph = true; 
                    options.IncludeGraphOperationBuilder = opt =>
                    {
                        if (opt is BulkOperation<Manufacturer> mOpt)
                        {
                            mOpt.ColumnPrimaryKeyExpression = x => new { x.Name };
                        }
                    };
                });
            } 
``` 

### Further technical details
- EF version:3.1.0
- EF Extensions version:3.0.26
- Database Provider:SqlServer

If remove options.ColumnPrimaryKeyExpression = x => new { x.Name }; will not get error, but i need make name unique;

**Comment by JonathanMagnan** [comment]
Hello @Belala ,

You need to include the first `ColumnPrimaryKeyExpression` in the `IncludeGraphOperationBuilder` as you have done with the Manufacturer.

```csharp
context.BulkMerge(parentProducts, options =>
{
	options.IncludeGraph = true; 
	options.IncludeGraphOperationBuilder = opt =>
	{
		if (opt is BulkOperation<Product> pOpt)
		{
			pOpt.ColumnPrimaryKeyExpression = x => new { x.Name };
		}
		else if (opt is BulkOperation<Manufacturer> mOpt)
		{
			mOpt.ColumnPrimaryKeyExpression = x => new { x.Name };
		}
	};
});
```

Only options not related to an entity type such as `BatchSize` is allowed outside of the `IncludeGraphOperationBuilder` when the `IncludeGraph` option is true.

Let me know if that answers successfully to your question.

Best Regards,

Jon

**Comment by Belala** [comment]
Thanks, But i got new error, i'm not sure whether data filter problem. 
I use  aspnetboilerplate template, disabled soft delete filter , but got error:

 Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at .( , DataSet )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkMergeAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at UxRetail.EntityFrameworkCore.Repositories.ExtendUxRetailRepository`2.BulkMergeAsync(IEnumerable`1 items, Action`1 options) in D:\Pro\UxRetail\UxRetail\src\UxRetail.EntityFrameworkCore\EntityFrameworkCore\Repositories\ExtendUxRetailRepository.cs:line 120
   at Abp.Threading.InternalAsyncHelper.AwaitTaskWithPostActionAndFinally(Task actualReturnValue, Func`1 postAction, Action`1 finalAction) in D:\Github\aspnetboilerplate\src\Abp\Threading\InternalAsyncHelper.cs:line 35
   at UxRetail.ReferenceDatas.BaseColors.BaseColorAppService.TestBulk() in D:\Pro\UxRetail\UxRetail\src\UxRetail.Application.MasterDatas\ReferenceDatas\BaseColors\BaseColorAppService.cs:line 87
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by JonathanMagnan** [comment]
Hello @Belala ,

Do you think you could provide us a runnable project that contains only this error? At this moment, it's currently to hard to find how to reproduce it.

You can send it in private here if you want: info@zzzprojects.com

**Comment by JonathanMagnan** [comment]
Hello @Belala ,

Since our last conversation, we haven't heard from you. 

As mentioned in my previous email, feel free to send us a sample project on our email info@zzzprojects.com

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Belala,

A quick reminder that we are here to assist you. 

Feel free to send us your project on our email info@zzzprojects.com 

Happy holidays, 

Jon
