### ISSUE TITLE
hierarchyid  not supported in Z.EntityFramework.Extensions

### ISSUE THREAD

**Issue by alibahal** [zzzprojects/EntityFramework-Extensions#311]
### Description
hi.
in entity framework 6.3 support for hierarchyid is added. but i think that your referenced version is lower than 6.3.
I paste the error raised when using hierarchyid  in model.
please update it's version to latest one, that is "Entity Framework 6.4". tank you in advance.

### Exception
the Error is :

Type not supported yet (LazyType): hierarchyid
at . (String , PrimitiveType )   
at .<>c. (Property ) 
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at . . (SchemaEntityType )  
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at . (Schema , Boolean ) 
at . (Schema , Boolean ) 
at . (XDocument ) 
at . (DbContext ) 
at . (DbContext ) 
at DbContextExtensions.GetModel(DbContext this)
at . (DbContext this, String )  
at . [ ](DbContext this, BulkOperation`1 , IEnumerable`1 , List`1 )  
at . [ ](BulkOperation`1 this, DbContext , IEnumerable`1 , List`1 )  
at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities

**Comment by JonathanMagnan** [comment]
Hello @alibahal ,

Thank you for reporting, we will look at it on Friday,

Best Regards,

Jon

**Comment by alibahal** [comment]
Thank you very much

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 24, 2019 at 19:48, Jonathan Magnan<notifications@github.com> wrote:   
Hello @alibahal ,

Thank you for reporting, we will look at it on Friday,

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @alibahal ,

The v4.0.33 has been released,

Could you try it and confirm us that the `HierarchyId` type now work as expected?

Best Regards,

Jon

**Comment by alibahal** [comment]
thanks a lot. all working great.

**Comment by JonathanMagnan** [comment]
awesome @alibahal ,

we are glad everything is working out for you! 

Best regards, 

Jon
