### ISSUE TITLE
BulkInsertAsync does not work

### ISSUE THREAD

**Issue by arturfityka** [zzzprojects/EntityFramework-Extensions#312]
### Description
The following `BulkInsertAsync` does not work.
```cs
public override async Task AddAsync(IEnumerable<Payment> payments)
  => await _dbContext.BulkInsertAsync(payments);
```
`Payment` is a very simple class:
```cs
public class Payment
{
  public Guid Id { get; }

  public Payment()
  {
    Id = Guid.NewGuid();
  }
}

```
### Exception
I get `ArgumentException`.
Exception message: `Expression must be writeable (Parameter 'left')`
Stack trace:
```
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at .[](Type ,  )
   at .(Type )
   at ..(String )
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at .SetValue(Object obj, Object value)
   at .`1.(Int32 , String , Object )
   at .SetValue(Int32 position,  accessor, Object value)
   at .SetValue(Int32 position,  accessor, Object value)
   at .( , DataTable )
   at .( , DataTable )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at BulkInsert.Infrastructure.Repositories.BulkInsertRepository.AddAsync(IEnumerable`1 payments) in C:\solutions\playground\BulkInsert\BulkInsert.Infrastructure\Repositories\BulkInsertRepository.cs:line 15
```
### Fiddle or Project (Optional)
The entire solution is avaiable here: [https://github.com/arturfityka/dotnet-bulk-insert/tree/c62bd9f4a2fd3cb30a11780180dcf10ce87a43c0](https://github.com/arturfityka/dotnet-bulk-insert/tree/c62bd9f4a2fd3cb30a11780180dcf10ce87a43c0)

### Further technical details
- EF version: 3.1
- EF Extensions version: 3.0.31
- Database Provider: SQL Express

**Comment by JonathanMagnan** [comment]
Hello @arturfityka ,

We are still trying to find a way to fix it.

An easy solution on your side is to add a private setter:

```csharp
public Guid ID { get; private set; }
public Guid ID { get; internal set; }
```

So it will still be possible to write in the property via reflection/expression but not directly from the code.

Is that a solution viable for you?
