### ISSUE TITLE
MySql InsertFromQuery ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ArFreeman** [zzzprojects/EntityFramework-Extensions#322]
### Description
When creating new entities with InsertFromQuery throws 'ArgumentOutOfRangeException'
Example: context.Heroes.InsertFromQuery("Villains", hero => new {hero.FirstName, hero.LastName});

### Exception
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at `1..( )
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at `1.()
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression)
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression)
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String tableName, Expression`1 selectFieldsExpression)
   at EFExtensions.Program.Main(String[] args) in C:\dev\ef extensions demo\EFExtensions\EFExtensions\Program.cs:line 10

### Fiddle or Project (Optional)
Repo: https://github.com/ArFreeman/EFExtensionsDemo.git

### Further technical details
- EF version: 6.4.0
- EF Extensions version: 4.0.43
- Database Provider: MySql.Data 8.0.19.0

**Comment by JonathanMagnan** [comment]
Hello @ArFreeman ,

Thank you for reporting,

My developer will try to reproduce this issue but there is a good chance that we come back and ask you for a runnable project with the issue.

Best Regards,

Jon

**Comment by ArFreeman** [comment]
> Hello @ArFreeman ,
> 
> Thank you for reporting,
> 
> My developer will try to reproduce this issue but there is a good chance that we come back and ask you for a runnable project with the issue.
> 
> Best Regards,
> 
> Jon

I've created a repo with a demo project.
Regards,
Artem

**Comment by JonathanMagnan** [comment]
Awesome thank you,

We will test your repo with the fix my developer made yesterday. It should be released today.

**Comment by ArFreeman** [comment]
> Awesome thank you,
> 
> We will test your repo with the fix my developer made yesterday. It should be released today.

Now I've Unhandled exception
System.Exception
  HResult=0x80131500
  Message=Oops! Your provider is not yet supported. At this moment, only SQL Server is supported for EF6.
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression)
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression)
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String tableName, Expression`1 selectFieldsExpression)
   at EFExtensions.Program.Main(String[] args) in C:\dev\efextensions\EFExtensionsDemo\EFExtensions\Program.cs:line 10

**Comment by JonathanMagnan** [comment]
Hello @ArFreeman ,

Yes, that was expected, this fix was not yet released ;)

A new release is now available v4.0.45

The first pull request has been refused, we created a new logic this night but didn't have time to add corresponding unit test. Tomorrow, my developer will spend some time to test the new logic.

But the fix is still already available (we were not supporting MySQL at all before this version for EF6, )
