### ISSUE TITLE
Exception when Bulk Inserting Geo Spatial Data

### ISSUE THREAD

**Issue by AdamQuintana** [zzzprojects/EntityFramework-Extensions#325]
### Description
I have been experimenting with EF-Extensions for the last few months for Bulk Inserts.  My database uses spatial data types of point, polygon and multipolygons.  An example of one of my column configurations - 

`            entity.Property(e => e.Border)
                .HasColumnType("geography (multipolygon)")
                .HasColumnName("border");
`

I was operating on version 3.0.30 and bulk inserts were working fine.  I recently upgraded to the latest version and started getting the exceptions below.

I did a bit more experimentation and found that bulk inserts work for me up to version 3.0.39, but fails on 3.0.40 and any versions more recent.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

`
Exception message: "Could not find SqlServerGeometryTypeMapping for property 'Border."
Source: "Z.EntityFramework.Extensions.EFCore"
Stack trace:

   at .(DbContext , IProperty , Object )
   at .`1.( )
   at .Read()
   at .()
   at .Read()
   at .( , DbConnection , DbTransaction , Int32 )
   at .( )
   at .( )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .[](DbContext this, IEntityType , IEnumerable`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )
   at .[](DbContext this, IEntityType , IEnumerable`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DbContextExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

`

### Further technical details
- EF version: EF Core 3.1.2
- EF Extensions version: 3.0.40 +
- Database Provider: PostGreSQL 12 + PostGIS 3

**Comment by JonathanMagnan** [comment]
Hello @AdamQuintana ,

Thank you for reporting,

Our library doesn't support yet spatial type for PostgreSQL but we will look at it. 

One of my developers just added support to spatial type for SQLite this week, so I guess this is time for PostgreSQL now ;)

I will give you an update about this request next week.

Best Regards,

Jon

**Comment by AdamQuintana** [comment]
Thanks for the quick reply.  I'd be happy to help test if needed!

**Comment by JonathanMagnan** [comment]
Hello @AdamQuintana ,

A new version is now available.

Could you try it and let us know if everything works fine with your model?

**Comment by AdamQuintana** [comment]
My bulk insert code works again.  Thanks guys!

**Comment by JonathanMagnan** [comment]
Awesome @AdamQuintana !

We are glad everything is working out for you. 

feel free to contact us for questions, issues or feedback! 

best regards,

Jon

**Comment by yurshanskyi** [comment]
Have the same problem with MySql

**Comment by JonathanMagnan** [comment]
Hello @yurshanskyi ,

Could you open a new Issue and provide a runnable project with it.

That will be easier for us to get started for `MySql`. We currently indeed don't still support it but we will be happy to investigate it if we have a project that helps my developer to get started with it.

Best Regards,

Jon
