### ISSUE TITLE
The object is in a detached state. This operation cannot be performed on an ObjectStateEntry when the object is detached.

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [zzzprojects/EntityFramework-Extensions#328]
### Description
I updated to .net 4.7.2, and suddenly I am getting this error when calling BulkInsertAsync (also update and merge)

> _context.BulkInsertAsync(models, (opts) =>
                        {
                            opts.IncludeGraph = true;
                        }).ConfigureAwait(false)

Any ideas why I would see this?  I am saving an object graph with includeGraph turned on, but never had to attach entities in the past. Everything was working until I updated some packages and now the same code that was working before throws an error.

The object I am saving contains an object of another type in its graph. If I remove that objects the save succeeds... there is also a self referencing child collection, which doesn't seem to cause any issues either way.

The most confusing part is that other places in my app where I am doing the exact same type of insert with the same object graph works. Pulling my hair out on this one.

    var node = new MyObjectType()
            {
                GUID = guid,
                MyOtherObject = new MyOtherObjectType()
                {
                    GUID= guid,
                },
                Children = new List<TreeNode>()
                    {
                        new TreeNode()
                        {

                        }
                    }
            };

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:

> The object is in a detached state. This operation cannot be performed on an ObjectStateEntry when the object is detached.

Stack trace:

>    at System.Data.Entity.Core.Objects.ObjectStateEntry.ValidateState()
>    at System.Data.Entity.Core.Objects.EntityEntry.AcceptChanges()
>    at .(DbContext , List`1 , List`1 , Action`1 , Boolean )
>    at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )


and for the outer exception 

>   at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )
>    at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
>    at System.Threading.Tasks.Task.Execute()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at DbContextExtensions.`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()

```

### Fiddle or Project (Optional)
If you are able, 

Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version: 6.4.0
- EF Extensions version:

>   "Z.EntityFramework.Extensions" version="4.0.59" targetFramework="net472" 
>   "Z.EntityFramework.Plus.EF6" version="1.12.19" targetFramework="net472"

- Database Provider:

**Comment by PTC-JoshuaMatthews** [comment]
I was missing a required property on my modal, not sure why the above error was thrown but adding the required property fixed it.
