### ISSUE TITLE
Column 'ZZZ_Index' does not belong to table Table.

### ISSUE THREAD

**Issue by skynet2** [zzzprojects/EntityFramework-Extensions#335]
### Description
EfCore BulkMerge fails due to exception "-- Failed with error: Column 'ZZZ_Index' does not belong to table Table."
After some testing, looks like                 opt.ColumnPrimaryKeyExpression = (e) => new {e.Token}; causes an issue somehow. 

### Dependencies
```
    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="1.1.0" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.3" />
      <PackageReference Include="System.Runtime.Caching" Version="4.7.0" />
      <PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="3.0.71" />
    </ItemGroup>
```

### Exception
```
Exception message: -- Failed with error: Column 'ZZZ_Index' does not belong to table Table."
Stack trace: System.ArgumentException: Column 'ZZZ_Index' does not belong to table Table.
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at .( , DataTable )
   at .( , DbCommand )
   at .Execute(List`1 actions)
```

### Fiddle or Project (Optional)
```
    public class MarketTypeP
    {
        public int Id { get; set; }
        public string Token { get; set; }
    }
public class Postgres : DbContext
    {
        public DbSet<MarketTypeP> MarketTypes { get; set; }

        public Postgres(DbContextOptions<Postgres> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("common");
            
            modelBuilder.Entity<MarketTypeP>(builder => {
                builder.Property(x => x.Token).IsRequired();
                builder.HasIndex(x => x.Token).IsUnique(); 
            });
        }
    }
```
```
static void PostgreIssue()
        {
            var conStr =
                "host=127.0.0.1;Username=postgres;Password=qwerty;database=event-publisher;Pooling=True;Minimum Pool Size=15;Maximum Pool Size=64";
            var x = new DbContextOptionsBuilder<Postgres>();

            x.UseNpgsql(
                    conStr)
                .UseSnakeCaseNamingConvention();

            EntityFrameworkManager.ContextFactory = context =>
            {
                var builder = new DbContextOptionsBuilder<Postgres>();

                builder.UseNpgsql(conStr)
                    .EnableSensitiveDataLogging()
                    .UseSnakeCaseNamingConvention();
                    
                return new Postgres(builder.Options);
            };
            
            var context = new Postgres(x.Options);


            var typesToAdd = new List<MarketTypeP>()
            {
                new MarketTypeP()
                {
                    Token = Guid.NewGuid().ToString()
                }
            };
            
            context.BulkMerge(typesToAdd, opt =>
            {
                opt.InsertKeepIdentity = false;
                opt.ColumnPrimaryKeyExpression = (e) => new {e.Token};
                opt.InsertIfNotExists = true;
                opt.Log = s =>
                {
                    Console.WriteLine(s);
                };
                
            });

        }
```

### Generated query
```
-- Executing Command:
INSERT  INTO "common"."market_types" AS DestinationTable
("token")
SELECT  "token"
FROM    (
SELECT @0_0 AS "id", @0_1 AS "token", @0_2 AS ZZZ_Index
) AS StagingTable
WHERE NOT EXISTS (SELECT 1 FROM "common"."market_types" AS DestinationTable WHERE DestinationTable."token" = StagingTable."token")
ORDER BY StagingTable.ZZZ_Index
RETURNING 'INSERT' as "$action", DestinationTable."id" AS "id_zzzinserted"
;
-- @0_0: 0 (Type = Int32, Size = -1)
-- @0_1: 23c953d9-100e-4d27-bed2-d86b8f077b6b (Type = String, Size = -1)
-- @0_2: 0 (Type = Int32, Size = 0)
-- CommandTimeout:120
-- Executing at 5/12/2020 1:34:03 PM

```
### Further technical details
- EF version: 3.1.3
- EF Extensions version: 3.0.71
- Database Provider: npgsql
- Postgre: PostgreSQL 10.8 (Ubuntu 10.8-0ubuntu0.18.10.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0, 64-bit

Thanks,
Stas

**Comment by skynet2** [comment]
Looks like i found how to bypass that. 
```
            context.BulkMerge(typesToAdd, opt =>
            {
                opt.AllowUpdatePrimaryKeys = true;
                opt.IncludeGraph = false;
                opt.ColumnPrimaryKeyExpression = (e) => e.Token;
                opt.Log = s => { Console.WriteLine(s); };
            });
```
I assume that most of magic is in opt.AllowUpdatePrimaryKeys = true;

i checked the query and now it generates : 
```
-- Executing Command:

UPDATE "common"."market_types" AS DestinationTable
SET     "token" = StagingTable."token"
FROM (
SELECT @0_0 AS "id", @0_1 AS "token", @0_2 AS ZZZ_Index
) AS StagingTable
WHERE DestinationTable."token" = StagingTable."token" 
RETURNING 'UPDATE' as "$action", StagingTable.ZZZ_Index, DestinationTable."id" AS "id_zzzinserted", 1
;

INSERT  INTO "common"."market_types" AS DestinationTable
("token")
SELECT  "token"
FROM    (
SELECT @0_0 AS "id", @0_1 AS "token", @0_2 AS ZZZ_Index
) AS StagingTable
WHERE NOT EXISTS (SELECT 1 FROM "common"."market_types" AS DestinationTable WHERE DestinationTable."token" = StagingTable."token")
ORDER BY StagingTable.ZZZ_Index
RETURNING 'INSERT' as "$action", DestinationTable."id" AS "id_zzzinserted"
;
-- @0_0: 0 (Type = Int32, Size = -1)
-- @0_1: abcd (Type = String, Size = -1)
-- @0_2: 0 (Type = Int32, Size = 0)
-- CommandTimeout:120
-- Executing at 5/13/2020 2:15:05 AM
```
But i am not sure if using this option will not try to update my real primary key (id), can you please check ?

Thanks,
Stas

**Comment by JonathanMagnan** [comment]
Hello @skynet2 ,

Thank you for reporting, we will look at it.

Yes, it will try to update the key if the column is **not an identity**.

I believe this issue happens because you only have one column and have some options on the keys. We will try to fix it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @skynet2 ,

A new version has been released today.

Let us know if everything is now working as expected on your side.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @skynet2 ,

Since our last conversation, we haven't heard from you. 

Did you get the chance to try the latest version?

Feel free to contact us for further assistance. 

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @skynet2 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us once you try the latest version.

Best regards,

Jon
