### ISSUE TITLE
4.0.67 - DeleteFromQueryAsync (Could not find the context from the IQueryable)

### ISSUE THREAD

**Issue by ZePhteven** [zzzprojects/EntityFramework-Extensions#339]
### Description
Hi,

When I try to use the `.DeleteFromQueryAsync()` extension I got an exception.

Sincerely,

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: "Could not find the context from the IQueryable expression. Are you sure this is coming from an Entity Framework Context?"
Stack trace:
System.Exception: Could not find the context from the IQueryable expression. Are you sure this is coming from an Entity Framework Context?
   at DbContextExtensions.GetContext[TEntity](IQueryable`1 query)
   at DbContextExtensions.Ã®â‚¬â€ [Ã®â‚¬Â](IQueryable`1 Ã®â‚¬Â, Action`1 Ã®â‚¬Â, CancellationToken Ã®â‚¬â€˜)
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.DeleteFromQueryAsync[TEntity](IQueryable`1 query)
```

### Fiddle or Project (Optional)
I can only provide this abstract :
```
public class EFBaseStore<TEntity>
{
        private readonly DbContext _context;
        private readonly DbSet<TEntity> _dbSet;

        public EFBaseStore(DbContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _dbSet = _context.Set<TEntity>();
        }

        public async Task DeleteAsync(Expression<Func<TEntity, bool>> predicate,
            bool saveChanges = true)
        {
            await _dbSet
                .Where(predicate)
                .DeleteFromQueryAsync();

            if (saveChanges)
            {
                await _context.SaveChangesAsync();
            }
        }
}
```

### Further technical details
- .NET Core version: 3.1
- EF version: EFCore 3.1.3
- EF Extensions version: 4.0.67 (I tried 4.0.79 too)
- Database Provider: SQLServer

**Comment by JonathanMagnan** [comment]
Hello @ZePhteven ,

I'm not sure if your problem is only this, but when using EF Core, you must use EF Extensions Core: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/3.0.79

The v4.0.79 is from EF Extensions for EF6.

Perhaps the issue is only this.

Best Regards,

Jon

**Comment by ZePhteven** [comment]
Damn, how could I not see that.

You were right, sorry for the inconvenience.

Have a nice day !
