### ISSUE TITLE
System.Exception: 'Type not supported yet (LazyType): geometrypoint'

### ISSUE THREAD

**Issue by mattiaskagstrom** [zzzprojects/EntityFramework-Extensions#342]
### Description
I'm trying to migrate 500 000 rows of roads from one database to another, but it would seem like bulk insert does not support System.Data.Entity.Spatial.DbGeometry

### Exception

```
System.Exception
  HResult=0x80131500
  Message=Type not supported yet (LazyType): geometrypoint
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at .(String , PrimitiveType )
   at .<>c.(Property )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ..(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .(Schema , Boolean )
   at .(Schema , Boolean )
   at .(String , String , String , String )
   at .(DbContext )
   at .(DbContext )
   at DbContextExtensions.GetModel(DbContext this)
   at .(DbContext this, String )
   at .BulkInsert[T](DbContext this, BulkOperation`1 bulkOperation, IEnumerable`1 entities2, List`1 entitiesToUpdate)
   at .BulkInsert[T](BulkOperation`1 this, DbContext context, IEnumerable`1 entities, List`1 entitiesToUpdate)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
   at IDbSetExtensions.BulkInsert[T](IDbSet`1 this, IEnumerable`1 entities)
   at CommonMigrator.Program.MigrateRoadSegments(GPDCalculationContainer calcctx, GPDCommonContainer commonctx) in D:\lokaldev\GPD Analys\GPDAnalys\CommonMigrator\Program.cs:line 83
   at CommonMigrator.Program.Migrate(GPDCalculationContainer calcctx, GPDAnalysisContainer actx, GPDCommonContainer commonctx) in D:\lokaldev\GPD Analys\GPDAnalys\CommonMigrator\Program.cs:line 45
   at CommonMigrator.Program.Main(String[] args) in D:\lokaldev\GPD Analys\GPDAnalys\CommonMigrator\Program.cs:line 22

```

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 4.0.79
- Database Provider: MS SQL Server

**Comment by mattiaskagstrom** [comment]
AddRange and BulkSaveChanges() does the trick! :)

**Comment by JonathanMagnan** [comment]
Hello @mattiaskagstrom ,

Thank you for reporting.

We will still look at why this is error is thrown with `BulkInsert`.

I do not think we support this spatial type (We are expected DbGeometry or DbGeography for example).

Best Regards,

Jon

**Comment by mattiaskagstrom** [comment]
Yupp, it is of type System.Data.Entity.Spatial.DbGeometry that in turn can be a polygon or point.

**Comment by JonathanMagnan** [comment]
Hello @mattiaskagstrom ,

Do you think you could provide us a runnable example? You can send it in private here if you want: info@zzzprojects.com

We might do something wrong as everything work as expected. We fail to make an example that throws this error.

**Comment by mattiaskagstrom** [comment]
@JonathanMagnan I'm currently on vacation, i can get back to you with an example after 3rd of august.

But the gist of it was that i hade a list of objects containing a DbGeometry with the subtype "point" (aka a single coordinate) that i then tried top do a bulk insert with.

**Comment by JonathanMagnan** [comment]
Pretty much what we did:

```csharp
DbGeometry test = DbGeometry.FromText("POINT(-73.935242 40.730610)");

public class EntitySimple
{
	public int ID { get; set; }
	public int ColumnInt { get; set; }
	public String ColumnString { get; set; }
	public System.Data.Entity.Spatial.DbGeometry Location { get; set; }
}
```

I guess we will wait till you come back ;)

Enjoy your vacation!

**Comment by mattiaskagstrom** [comment]
yeah, that should do the trick... one thing I'm thinking might be the cause is that i have a foreign key to another object that has a geometry point. But I'm adding it via id, not the entire object.

**Comment by JonathanMagnan** [comment]
Hello @mattiaskagstrom ,

I'm not exactly sure to understand your scenario or how it could make it fail.

Can we close this issue or can you provide a runnable project with the issue that we could try?

**Comment by mattiaskagstrom** [comment]
We can mark it as closed now since AddRange and BulkSaveChanges() is a working workaround. if I figure out why it happens I'll open a new one and refer to this :)
