### ISSUE TITLE
EFCore 3 + Postgres + UpdateFromQuery - Fails with missing FROM-clause entry for table "b"

### ISSUE THREAD

**Issue by kfirpeled** [zzzprojects/EntityFramework-Extensions#348]
### Description
Trying to use the UpdateFromQuery feature fails on certain conditions

### Exception

```
Exception message:
Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: missing FROM-clause entry for table "b"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
   at BatchUpdateExtensions.`1.()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at BatchUpdateExtensions.UpdateFromQueryAsync[TEntity](IQueryable`1 query, Expression`1 updateExpression)
   at Program.Main() in /Users/peledkfir/Documents/bs/ZExtensionsDemo/ConsoleApp1/Program.cs:line 36
   at Program.<Main>()
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: missing FROM-clause entry for table "b"
    Position: 45
    File: parse_relation.c
    Line: 3305
    Routine: errorMissingRTE

```

### Fiddle or Project (Optional)

https://dotnetfiddle.net/UfU67n#

### Further technical details
- EF version: 3.1.4
- EF Extensions version: 3.0.55
- Database Provider: Npgsql

fails with following nugets:
```
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.4"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.4"/>
        <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="3.0.55"/>

```
when fails (EF 3.x), it generates the following sql command:

UPDATE "PolicyCustomers"
SET "Counter" = **B.**"Counter" + 1
WHERE EXISTS ( SELECT 1 FROM (SELECT p."PolicyCustomerID", p."Counter", p."Name"
FROM "PolicyCustomers" **AS p**
WHERE p."Counter" >= 1) B
               WHERE "PolicyCustomers"."PolicyCustomerID" = B."PolicyCustomerID"
           )  

works with the following nugets:
```
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.4"/>
        <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="2.0.55"/>

```
when works (EF 2), it generates the following sql command:

UPDATE "PolicyCustomers"
SET "Counter" = "Counter" + 1
WHERE EXISTS ( SELECT 1 FROM (SELECT x."PolicyCustomerID", x."Counter", x."Name"
FROM "PolicyCustomers" **AS x**
WHERE x."Counter" >= 1) B
               WHERE "PolicyCustomers"."PolicyCustomerID" = B."PolicyCustomerID"
           )

**Comment by kfirp-bs** [comment]
Same issue on dotnet 5 preview 6

**Comment by kfirp-bs** [comment]
if we change a bit the code and change the lambdas parameters

`context.PolicyCustomers.Where(r => r.Counter >= 1).UpdateFromQuery(r => new PolicyCustomer {Counter = r.Counter + 10});`

it fails also on EF 2, it generates the following sql command:


UPDATE "PolicyCustomers"
SET "Counter" = **r.**"Counter" + 1
WHERE EXISTS ( SELECT 1 FROM (SELECT r."PolicyCustomerID", r."Counter", r."Name"
FROM "PolicyCustomers" **AS r**
WHERE r."Counter" >= 1) B
               WHERE "PolicyCustomers"."PolicyCustomerID" = B."PolicyCustomerID"
           )

**Comment by JonathanMagnan** [comment]
Hello @kfirp-bs ,

Thank you for reporting,

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @kfirp-bs ,

A new version has been released.

Could you try it and let us know if everything now works as expected?

Best Regards,

Jon

**Comment by kfirp-bs** [comment]
It works now, Thanks !!!

Is there an estimation when this will be available in the Plus version?

**Comment by JonathanMagnan** [comment]
Hello @kfirp-bs ,

We will make a release tonight or tomorrow for EF Plus. I will let you know.

**Comment by JonathanMagnan** [comment]
Hello @kfirp-bs ,

A new version of EF Plus with the latest EFE dependencies has been released.

**Comment by JonathanMagnan** [comment]
Hello @kfirp-bs ,

Since our last conversation, we haven't heard from you. 

Did you get the chance to try the new version of EF Plus with the latest EFE dependencies?

Don't hesitate to contact us for further assistance. 

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @kfirp-bs 

A simple reminder that we are here to assist you!

Don't hesitate to contact us once you try the new version of EF Plus with the latest EFE dependencies.

Best regards,

Jon

**Comment by kfirpeled** [comment]
Hey,
Super sorry for the late response,
Yes I've got the release and it fixed my issue
