### ISSUE TITLE
BulkInsert throws error "Property could not be resolved: Inventory"

### ISSUE THREAD

**Issue by jehhynes** [zzzprojects/EntityFramework-Extensions#352]
### Description
I am getting an exception when attempting to use BulkInsert. In my Fiddle demonstrating the issue, Inventory is not a property of InstallationItemInvoiceItem or any base classes. However, it appears that it's trying to resolve the "Inventory" property, which is actually a property of InventoryInvoiceItem. It seems that somehow my inheritance scenario is messing it up.

### Exception

```
Property could not be resolved: Inventory FullName:System.String[]

Stack Trace:
[System.Exception: Property could not be resolved: Inventory FullName:System.String[]]
   at Z.EntityFramework.Extensions.Core.Mapping.ScalarAccessorMapping.(Object )
   at Z.EntityFramework.Extensions.Core.Mapping.ScalarAccessorMapping.(Object )
   at .[](DbContext this, List`1 ,  , SchemaEntityType , Int32 , List`1 , Boolean , List`1 )
   at DbContextExtensions.`1.( )
   at .Read()
   at .()
   at .( , DbCommand )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at .BulkInsert[T](BulkOperation`1 this, DbContext context, List`1 list, Boolean isManager, List`1 entitiesToUpdate, Type type, String typeName)
   at .`1.(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .BulkInsert[T](DbContext this, BulkOperation`1 bulkOperation, IEnumerable`1 entities2, List`1 entitiesToUpdate)
   at .BulkInsert[T](BulkOperation`1 this, DbContext context, IEnumerable`1 entities, List`1 entitiesToUpdate)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
   at Program.Main() :line 21
```

### Fiddle or Project (Optional)
https://dotnetfiddle.net/5wp0Xs

### Further technical details
- EF version: 6
- EF Extensions version: Latest
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @jehhynes ,

Thank you for reporting, we will look at it.

`SaveChanges` works with this scenario so this is likely something we want to support as well.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jehhynes ,

The v4.0.88 is now available.

This error will not be longer throw in this TPH scenario.

Let me know if everything is now working as expected.

Best Regards,

Jon

**Comment by jehhynes** [comment]
Thanks, I've confirmed that the error is solved.
