### ISSUE TITLE
InsertFromQuery with DevArt gives ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by citypermit** [zzzprojects/EntityFramework-Extensions#359]
#239 # Description
When using InsertFromQuery with DevArt on an Oracle 19 database I always get an ArgumentOutOfRangeException.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

Stack trace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at `1..( )
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at `1.()
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression, Type tableType)
   at DbContextExtensions.[](IQueryable`1 , String , String , String , Expression`1 , Type )
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, Expression`1 selectFieldsExpression)
   at TestConsoleApplication.Program.Main() in C:\local\TestConsoleApplication\TestConsoleApplication\Program.cs:line 9
```

### Fiddle or Project (Optional)
Included my test project. The connection string is of course changed.
[TestConsoleApplication.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/5161815/TestConsoleApplication.zip)

### Further technical details
- EF version: 6.4.4 (6.3 has the same issue)
- EF Extensions version: 4.0.91
- Database Provider: Devart.Data.Oracle

**Comment by JonathanMagnan** [comment]
Hello @citypermit ,

The v4.0.92 has been released, could you try it and let us know if the issue is fixed with DevArt Oracle?

Best Regards,

Jon

**Comment by citypermit** [comment]
Hello Jon,

Thank you for the response. However with the new version the problem is not resolved, although the error message is a bit different:

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at `1.()
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression, Type tableType)
   at DbContextExtensions.[](IQueryable`1 , String , String , String , Expression`1 , Type )
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, Expression`1 selectFieldsExpression)
   at TestConsoleApplication.Program.Main() in C:\local\TestConsoleApplication\TestConsoleApplication\Program.cs:line 9

  This exception was originally thrown at this call stack:
    [External Code]
    TestConsoleApplication.Program.Main() in Program.cs

**Comment by JonathanMagnan** [comment]
Thank you, we will look at it

**Comment by JonathanMagnan** [comment]
Hello @citypermit ,

A new version has been released which should now better handled how DevArt generates SQL.

Could you try it and let us know if everything works as expected?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @citypermit,

Did you get the time to try the new version?

Don't hesitate to contact us for further assistance.

Jon

**Comment by citypermit** [comment]
Hello Jon,

Sorry for the late reply, I was away the last two weeks. I tested the last version and it works now. Thank you very much for the fast service.
