### ISSUE TITLE
Bulk UpdateFromQuery dos not support complex objects

### ISSUE THREAD

**Issue by EvgeniyaZamakhina** [zzzprojects/EntityFramework-Extensions#365]
### Description

I have complex object  like 
```
public class Customer
	{
		public int CustomerID { get; set; }
		public NewClass NewClass { get; set; }
	}
	
	
	public class NewClass
	{
		public int Count { get; set; }
	}
```

which property is mapped in the Configuration (I use DB first):

```
public class CustomerConfiguration : EntityTypeConfiguration<Customer>
{
        public CustomerConfiguration()
        {
            ToTable("Customers");

            HasKey(x => x.CustomerID);
            Property(x => x.NewClass.Count).HasColumnName("Count");
	}
}
```
I would like to bulk update Count but UpdateFromQuery method doesn't support such objects, I suppose.
```
context.Customers.UpdateFromQuery(new Dictionary<string, object>
                {
                    {"NewClass.Count",  34}
                });
```
It returns: 
'The destination column could not be found: NewClass or Count'
depending on what I put to the props.
Would it be possible to improve library?

### Exception

```
Exception message: The destination column could not be found:VerificationTriggeredDateTime 
Stack trace:
   at .[](IQueryable`1 , Expression`1 , SchemaEntityType`1 )
   at .Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, IDictionary`2 dictionary, Action`1 bulkOperationFactory)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, IDictionary`2 dictionary)
```

### Fiddle or Project (Optional)
It is not really reproducible (because of db first, I assume), but I tried here https://dotnetfiddle.net/G1yRdJ

### Further technical details
- EF version: EF6 core
- EF Extensions version: Z.EntityFramework.Extensions, Version=4.0.24.0
- Database Provider: MSSQLLocalDB

**Comment by JonathanMagnan** [comment]
Hello @EvgeniyaZamakhina ,

You are right, we currently doesn't support this syntax.

However, it can be possible with the following ways:

```csharp
context.Customers.Update(x => new Customer() { NewClass  = new NewClass() { Count = 34 } });
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
