### ISSUE TITLE
Exception on BulkSaveChanges with Owned Entity Type

### ISSUE THREAD

**Issue by kfairs** [zzzprojects/EntityFramework-Extensions#368]
### Description
I am evaluating with view to inclusion in our standard stack. . We have extensive use of Owned Entity Types. I see this exception when calling BulkSaveChanges on a model which includes an Owned Entity.  The contrived example is the minimum to reproduce. This is SQLlite in memory, but exactly the same issue with full SQL Server

### Exception

```
Exception message:
System.Exception
  HResult=0x80131500
  Message=System.Boolean
  Source=Z.EntityFramework.Extensions.EFCore
  StackTrace:
   at Z.EntityFramework.Extensions.PropertyZInfo.ConvertValueToProvider(DbContext context, Object value)
   at .`1.( )
   at .Read()
   at .()
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 , DbContext )
   at Tests.Integration.Entities.SqlBulkOperationTests.OwnedIssue() in C:\TFS.Nbrly\Neighbourly\App\Dev3\Tests.Integration\Entities\SqlBulkOperationTests.cs:line 499

  This exception was originally thrown at this call stack:
    [External Code]
    Tests.Integration.Entities.SqlBulkOperationTests.OwnedIssue() in SqlBulkOperationTests.cs
```

### Code
```
[TestMethod]
        public void OwnedIssue()
        {

            var options = SqliteInMemory.CreateOptions<BookContext>();

            using (var context = new BookContext(options))
            {

                SqlServerHelpers.CreateEmptyViaWipe(context);

                var book1 = new Book { Title = "Book1", Stock = new BookStock { InStock = true }};
                context.Add(book1);
                var book2 = new Book { Title = "Book2", Stock = new BookStock { InStock = false } };
                context.Add(book2);

                context.BulkSaveChanges();
            }
        }




        class BookContext : DbContext
        {
            public DbSet<Book> Books { get; set; }


            public BookContext(
                DbContextOptions<BookContext> options)
                : base(options) { }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.ApplyConfiguration(new BookConfig());
            }

        }

        class Book
        {
            public int BookPk { get; set; }
            public string Title { get; set; }

            public BookStock Stock { get; set; } = new BookStock();
        }

        class BookStock
        {
            public bool InStock { get; set; }
        }

        class BookConfig : IEntityTypeConfiguration<Book>
        {
            public void Configure(EntityTypeBuilder<Book> entity)
            {
                entity.HasKey(t => t.BookPk);
                entity.OwnsOne(x => x.Stock);

            }

        }
```

### Further technical details
- EF version:  EFCore v3.1.9
- Z.EntityFramework.Extensions.EFCore v3.0.102
- Z.EntityFramework.Plus.EFCore v3.0.67
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer v3.1.9  / Microsoft.EntityFrameworkCore.Sqlite v3.1.9

**Comment by JonathanMagnan** [comment]
Hello @kfairs ,

Thank you for the code.

We are currently re-writing the code related to the model to fix issues similar to this one.

I cannot promise any date yet since this is part of a very big merge but we push it very hard to be able to release it ASAP, perhaps next week if everything goes well.

Best Regards,

Jon

**Comment by kfairs** [comment]
Any update on this?
Thanks

**Comment by JonathanMagnan** [comment]
Hello @kfairs ,

We just tested your code in our branch and everything looks to work perfectly.

We are currently pushing very hard to make this big release on Thursday. In the worse case at the beginning of next week.

So the fix is coming very soon.

**Comment by JonathanMagnan** [comment]
Hello @kfairs ,

It took us more time than expected but it should be finally released.

This scenario should work with the latest version.

Let me know if the issue has been also solved on your side.

Best Regards,

Jon

**Comment by kfairs** [comment]
It is certainly working with our unit tests, thanks.

**Comment by JonathanMagnan** [comment]
Thank you @kfairs 

Let us know if you need anything ;)
