### ISSUE TITLE
BulkMerge - `IncludeGraph` feature not work with InMemoryDatabase

### ISSUE THREAD

**Issue by tien199013** [zzzprojects/EntityFramework-Extensions#373]
### Description
When adding unit tests for a business logic where touching `BulkMerge` with `IncludeGraph` feature, we got the following exceptions. Surprisingly, the production code works and behaves as what we expected. However, in the unit tests stage where we using the EF core's in memory database it failed.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
System.Exception: Oops! The 'IncludeGraph' feature doesn't work with 'BulkUpdate' and 'BulkMerge' NMemory provider.
   at .(DbContext this, Action`1 , DbContext )
   at DbContextExtensions.(DbContext this, Action`1 , DbContext )
   at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
   at .BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkMergeAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
```
Exception message:
Stack trace:
```

### Example code
`using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Metis.Wellbore.Repository.Tests
{
    public class Tests
    {
        [Fact]
        void Should_pass()
        {
            using (var context = new BookStore())
            {
                var authors = new List<Author>
                {
                    new Author
                    {
                        FirstName ="Carson",
                        LastName ="Alexander",
                        BirthDate = DateTime.Parse("1985-09-01"),
                        Books = new List<Book>()
                        {
                            new Book { Title = "Introduction to Machine Learning"},
                            new Book { Title = "Advanced Topics on Machine Learning"},
                            new Book { Title = "Introduction to Computing"}
                        }
                    },
                    new Author
                    {
                        FirstName ="Meredith",
                        LastName ="Alonso",
                        BirthDate = DateTime.Parse("1970-09-01"),
                        Books = new List<Book>()
                        {
                            new Book { Title = "Introduction to Microeconomics"}
                        }
                    },
                    new Author
                    {
                        FirstName ="Arturo",
                        LastName ="Anand",
                        BirthDate = DateTime.Parse("1963-09-01"),
                        Books = new List<Book>()
                        {
                            new Book { Title = "Calculus I"},
                            new Book { Title = "Calculus II"}
                        }
                    }
                };

                //IncludeGraph allows you to INSERT/UPDATE/MERGE entities by including the child entities graph.
                context.BulkMerge(authors, options => options.IncludeGraph = true);
            }

            using (var context = new BookStore())
            {
                var list = context.Authors
                    .Include(a => a.Books)
                    .ToList();

                foreach (var author in list)
                {
                    Console.WriteLine(author.FirstName + " " + author.LastName);

                    foreach (var book in author.Books)
                    {
                        Console.WriteLine("\t" + book.Title);
                    }
                }
            }
        }

    }

    public class BookStore : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase(databaseName: "BookStoreDb");
        }

        public DbSet<Author> Authors { get; set; }
        public DbSet<Book> Books { get; set; }
    }

    public class Author
    {
        public int AuthorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
        public List<Book> Books { get; set; }
    }

    public class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public Author Author { get; set; }
    }
}`

### Further technical details
- EF version: 3.1.10
- EF Extensions version:3.1.0
- Database Provider:Microsoft.EntityFrameworkCore.InMemory 3.1.10

**Comment by JonathanMagnan** [comment]
Hello @tien199013 ,

Unfortunately, we have disabled the support of `IncludeGraph` for `InMemory` provider.

The problem happens due to how the context works under the hood for the `InMemory` provider. We will eventually re-work the `IncludeGraph` feature to stop using some EF Core method but for now, there is nothing we can do since that's not a quick fix and a lot of big development is already ongoing on this library to better support EF Core 5.

Best Regards,

Jon

**Comment by daxstar83** [comment]
HI,
 is there any further development regarding the problem with IncludeGraph and the InMemory Db provider ?

Best Regards,
Rico

**Comment by JonathanMagnan** [comment]
Hello @daxstar83 ,

Unfortunately there is currently no progress

**Comment by mbikodusic** [comment]
What is the latest EF Plus version where this was supported?
Do you have any timeline when this can be expected?
