### ISSUE TITLE
.NET 5 and EFCore 5: BulkMergeAsync throws TypeInitializationException

### ISSUE THREAD

**Issue by tystol** [zzzprojects/EntityFramework-Extensions#380]
### Description
BulkMergeAsync works fine at runtime (using EFCore.PostgreSQL).
However within tests (using EFCore.InMemory) it throws the below:

### Exception
```
System.TypeInitializationException: "The type initializer for '' threw an exception." ---> System.Reflection.AmbiguousMatchException: "Ambiguous match found."
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at System.Type.GetMethod(String name)
   at ..cctor()
  --- End of inner exception stack trace ---
   at .GetAllByPrimaryKeys( action, DbContext inMemoryContext, Type entityType, Object entity)
   at .( , DbCommand )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkMerge()
   at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DbContextExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyApp.<UpsertData>d__13.MoveNext() in /Users/tystol/Code/MyApp.cs:line 713
```

### Further technical details
- EF version: EFCore 5.0.0
- EF Extensions version: Extensions.EFCore 5.1.5
- Database Provider: InMemory 5.0.0
- Test framework: NUnit 3.12.0
- Test runner: Running within VS for Mac IDE. NUnit3TestAdapter 3.17.0, Microsoft.NET.Test.Sdk 16.8.3

It appears to be the same as the issue reported in the last few comments of https://github.com/zzzprojects/EntityFramework-Extensions/issues/378
However I've double checked all references and there is no old EFCore 3.1 references anywhere.
bin and obj folders have been cleared and fresh rebuilds done. Definitely running EFCore 5.

**Comment by kdvtrifork** [comment]
Yes I get the same exception. 
I just updated to Z.EntityFramework.Plus.EFCore 5.1.6, but still the same.

**Comment by JonathanMagnan** [comment]
Hello @kdvtrifork ,

The v5.1.8 has been released.

Could you try it? The issue should be fixed in this version.

Best Regards,

Jon

**Comment by kdvtrifork** [comment]
Hi @JonathanMagnan ,

Yes it looks like that it works now! Thanks 🚀
