### ISSUE TITLE
BulkDeleteAsync not working 

### ISSUE THREAD

**Issue by devonLBRI** [zzzprojects/EntityFramework-Extensions#381]
### Description
When trying to bulk delete from a table, getting error message saying Type not supported yet: enum.

This is for a MySql Database.

### Exception

Type not supported yet (LazyType): enum
   at ?.?(String ?, PrimitiveType ?)
   at ?.<>c.?(Property ?)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ?.?.?(SchemaEntityType ?)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ?.?(Schema ?, Boolean ?)
   at ?.?(Schema ?, Boolean ?)
   at ?.?(String ?, String ?, String ?, String ?)
   at ?.?(DbContext ?)
   at ?.?(DbContext ?)
   at DbContextExtensions.GetModel(DbContext this)
   at ?.?(DbContext this, String ?)
   at ?.BulkDelete[T](DbContext this, BulkOperation`1 bulkOperation, IEnumerable`1 entities2)
   at ?.BulkDelete[T](BulkOperation`1 this, DbContext context, IEnumerable`1 entities)
   at DbContextExtensions.BulkDelete[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at DbContextExtensions.?`1.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DbContextExtensions.?`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DataToEventsDB.Program.<InsertCustomers>d__6.MoveNext() in D:\C# Progs (Non Network)\DataToEventsDB\DataToEventsDB\Program.cs:line 195

### Code executed:
public static EventsEntities db2 = new EventsEntities();

List<customer> cust = db2.customers.ToList();
await db2.BulkDeleteAsync(cust);

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 5.1.9
- Database Provider: MYSQL

**Comment by JonathanMagnan** [comment]
Hello @devonLBRI ,

Thank you for reporting,

I will ask my developer to try it and support it if he can reproduce it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @devonLBRI ,

Sorry for the long waiting for a reply (Chrismas break fault!)

My developer tried a few scenarios but everything seems to work.

This is indeed an error raised by our library but we are not able to reproduce this error about the `enum`

Is it possible for you to provide a runnable project that contains the minimum code to show this error? You can send it in private here: info@zzzprojects.com

You can also let us know what is missing in the simple project we attached
[request_3387.txt](https://github.com/zzzprojects/EntityFramework-Extensions/files/5764726/request_3387.txt)

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Yes, there is a huge chance.

One of your types in the `EDMX` has probably the `enum` type which explains why we cannot reproduce it.

Do you think you can still provide us a runnable project? It will surely help my developer to look at it.

Another way to fix it on your side is probably to change the type `enum` to the underlying enum type such as `int`

**Comment by devonLBRI** [comment]
I figured it out. We can mark this as resolved.

I did find an enum type but in my code it was defined as a string.

Devon Albert
IT Administrator

L’BRI PURE n’ NATURAL
909 Perkins Drive<x-apple-data-detectors://10/0>
Mukwonago, WI 53149<x-apple-data-detectors://10/0>
Phone: 262-333-0709<tel:262-363-9674;242>
Email: devon@lbri.com<mailto:devon@lbri.com>

**Comment by JonathanMagnan** [comment]
Awesome,

Thank for letting us know.

Have a great new year ;)

Best Regards,

Jon
