### ISSUE TITLE
DeleteFromQuery not working for joint entities

### ISSUE THREAD

**Issue by YeskaNova** [zzzprojects/EntityFramework-Extensions#387]
### Description
I have some dependencies between two entities ( Post and Tag ) materialized by a joint entity PostTag in the example below. For performance reasons, I want to execute a delete on these dependencies, but the DeleteFromQuery does not work on them, even if EF Core queries work.

### Exception
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'property')
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at .`1.(String , Int32 )
   at System.Linq.Enumerable.<SelectIterator>d__173`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at .[](IQueryable`1 , List`1 )
   at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query)
   at BatchDeleteExtensions.DeleteFromQuery[T](IQueryable`1 query)
```

### Fiddle or Project (Optional)
```
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

public class Post
{
    public int Id { get; set; }

    public ICollection<Tag> Tags { get; set; }
}

public class Tag
{
    public int Id { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class PostTag
{
    public Post Post { get; set; }
    public Tag Tag { get; set; }
}
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tag>();
        modelBuilder.Entity<Post>()
            .HasMany(p => p.Tags)
            .WithMany(p => p.Posts)
            .UsingEntity<PostTag>(
                j => j
                    .HasOne(pt => pt.Tag).WithMany(),
                j => j
                    .HasOne(pt => pt.Post).WithMany());
    }
}

class Program
{
    static void Main(string[] args)
    {
        var sc = new ServiceCollection();
        var guid = Guid.NewGuid();
        sc.AddDbContext<AppDbContext>(op => op.UseSqlServer(@"Server=(localdb)\MSSQLLocalDB;Integrated Security=true;DataBase=" + guid));
        using (var provider = sc.BuildServiceProvider())
        {
            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
               dbcontext.Database.EnsureCreated();
            }

            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
                var tag = new Tag();
                dbcontext.Add(tag);
                dbcontext.Add(new Post() { Tags = new List<Tag>() { tag} });
                dbcontext.SaveChanges();
            }


            using (var scope = provider.CreateScope())
            using (var dbcontext = scope.ServiceProvider.GetService<AppDbContext>())
            {
                Debug.Assert(dbcontext.Set<PostTag>().Count() == 1);   // EF Queries work
                var deleteCmd = dbcontext.Set<PostTag>().DeleteFromQuery();  // DeleteFromQuery not working
            }

        }

    }
}
```
### Further technical details
- EF version: 5.0.2
- EF Extensions version: 5.1.12
- Database Provider: Sql Server

**Comment by JonathanMagnan** [comment]
Hello @YeskaNova ,

Thank you for reporting, we successfully reproduced it with your code.

We will look if that's possible to support an entity that doesn't have any property.

If you need a quick resolution meanwhile, all you have to do is adding an `Id` property to the `PostTag`.

Best Regards,

Jon

**Comment by YeskaNova** [comment]
@JonathanMagnan The workaround works, thank you!

**Comment by JonathanMagnan** [comment]
Awesome @YeskaNova !

We are glad to hear everything is working out for you!

Don't hesitate to contact us with any questions or further assistance!

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @YeskaNova ,

The v5.1.13 has been released.

Table with only shadow property (no property) should now work correctly.

Let me know if everything is now working with the latest version.

**Comment by YeskaNova** [comment]
@JonathanMagnan It works great, thank you.
