### ISSUE TITLE
Enabling FIPS Mode on Server 2012 R2 results in multiple failures

### ISSUE THREAD

**Issue by VonOgre** [zzzprojects/EntityFramework-Extensions#39]
When using a licensed version of pro, the license validation will fail if FIPS mode is enabled on the machine with the following stack trace:
The program has encountered an unknown error: The provided license key is invalid or trial period is expired. Please buy a product license or go to http://www.zzzprojects.com and download the latest trial version.  User: NEXTNET\bdunn Url: FPML Publish  Exception Details:    at ..(String , String , Int32& )
   at ..(ProviderType , Boolean )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at ..(List`1 , Object , Dictionary`2 )
   at ..()

When using the latest demo version on nuget (3.12.0), BulkInsert (and I assume the other bulk methods) fail with the following stack trace:

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at ..(String )
   at Z.BulkOperations.InternalLicenseManager.(String , String , Int32& )
   at ..(ProviderType , Boolean , Boolean )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.EntityFramework.Extensions.SqlServerBulkSaveChanges.(List`1 , Int32 , Object , Dictionary`2 )
   at Z.EntityFramework.Extensions.SqlServerBulkSaveChanges.()

   Inner Exception: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()

**Comment by JonathanMagnan** [comment]
Hello @VonOgre ,

You are right. If you cannot disable FIPS, please contact us and we will generate a license compatible with it.

The short story is we have two choices when creating a license. Making it compatible with Windows XP and lower (the one you currently use), making it compatible with FIPS enabled.

Please contact us directly: info@zzzprojects.com and we will generate you the license.

Best Regards,

Jonathan

**Comment by VonOgre** [comment]
Email sent!

**Comment by VonOgre** [comment]
Updating to v3.12.0 with a new license that supports FIPS seems to have done the trick!
