### ISSUE TITLE
BulkInsert throws InvalidCastException with EnumToStringConverter for in-memory database

### ISSUE THREAD

**Issue by meinsiedler** [zzzprojects/EntityFramework-Extensions#398]
### Description
We are receiving an `InvalidCastException` when we try to perform a `BulkInsert` with an entity which has an enum property and this enum property uses an `EnumToStringConverter`.

The issue is easily reproducible with the sample code below. When we define the `EnumToStringConverter<BookType>` in the `BookStore`, we receive the exception. When we remove the converter, everything works as expected.

It seems that this issue only occurs when using the in-memory database. We tested with a SQL database too and it works there.

### Exception
```
Exception message: System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'EfExtensionsTest.BookType'.'
Stack trace: 
at System.Runtime.CompilerServices.CastHelpers.Unbox(Void* toTypeHnd, Object obj)
at .( , DbCommand )
at .( , DbCommand )
at .Execute(List`1 actions)
at .(List`1 )
at Z.BulkOperations.BulkOperation.Execute()
at Z.BulkOperations.BulkOperation.BulkInsert()
at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
at DbSetExtensions.BulkInsert[T](DbSet`1 this, IEnumerable`1 entities)
at EfExtensionsTest.Program.Main(String[] args) in Program.cs:line 22
```

### Fiddle or Project (Optional)
```
namespace EfExtensionsTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new BookStore())
            {
                var books = new List<Book>()
                {
                    new Book { Title = "Introduction to Machine Learning", Type = BookType.Paperback },
                    new Book { Title = "Advanced Topics on Machine Learning", Type = BookType.Paperback },
                    new Book { Title = "Introduction to Computing", Type = BookType.Hardcover }
                };

                context.Books.BulkInsert(books);
            }

            using (var context = new BookStore())
            {
                var list = context.Books.ToList();
                
                foreach (var book in list)
                {
                    Console.WriteLine($"\t{book.Title} ({book.Type})");
                }
            }
        }
    }

    public class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public BookType Type { get; set; }
    }

    public enum BookType
    {
        Paperback,
        Hardcover
    }

    public class BookStore : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase(databaseName: "BookStoreDb");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Works when we don't specify the EnumToStringConverter here.
            modelBuilder.Entity<Book>()
                .Property(e => e.Type)
                .HasMaxLength(100)
                .HasConversion(new EnumToStringConverter<BookType>());
        }

        public DbSet<Book> Books { get; set; }
    }
}
```

### Further technical details
- EF version: 5.0.3
- EF Extensions version: 5.1.21
- Database Provider: in-memory

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

Thank you for reporting, I believe we have all the information needed to reproduce it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

The v5.1.22 has been released.

Could you try it and let us know if my developer successfully fixed it?

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Hello @JonathanMagnan ,

everything is working is expected with the new version. Thank you!
