### ISSUE TITLE
ArgumentNullException during call to UpdateFromQueryAsync with Owned types.

### ISSUE THREAD

**Issue by michaelnero** [zzzprojects/EntityFramework-Extensions#401]
### Description
I'm trying to do an UpdateFromQueryAsync with an entity that has an owned type, but I'm getting an exception. I've tried a couple of different ways to work around it.

### Exception

```
Exception message:
System.ArgumentNullException: 'Value cannot be null. (Parameter 'constructor')'

Stack trace:
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilde)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
   at BatchUpdateExtensions.`1.()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at BatchUpdateExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Infrastructure.Azure.Messaging.Handling.EventDispatcher.<>c__DisplayClass7_0.<<DispatchMessage>b__0>d.MoveNext() in C:\Projects\jollygig\src\Infrastructure.Azure\Messaging\Handling\EventDispatcher.cs:line 39
```

### More details
I have a class defined like this:

```
public class Person
{
    public Person(string email)
    {
        Email = email;
        Memberships = new List<Membership>();
    }

    public Guid Id { get; set; }
    public string Email { get; set; }
    public PersonProfile? Profile { get; set; }

    public List<Membership> Memberships { get; }

    [Timestamp]
    public byte[]? RowKey { get; set; }
}

[Owned]
public class PersonProfile
{
    public PersonProfile(string displayName, string timeZoneId, string avatar)
    {
        DisplayName = displayName;
        TimeZoneId = timeZoneId;
        Avatar = avatar;
    }

    public string DisplayName { get; set; }
    public string TimeZoneId { get; set; }
    public string Avatar { get; set; }
}
```

I've tried the following, and for all three I get the exception above:

```
await _db.People.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Profile = new
    {
        @event.DisplayName,
        @event.TimeZoneId,
        @event.Avatar
    }
});
```

```
await _db.People.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Profile = new PersonProfile(@event.DisplayName, @event.TimeZoneId, @event.Avatar)
});
```

```
var profile =  new PersonProfile(@event.DisplayName, @event.TimeZoneId, @event.Avatar);

await _db.People.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Profile = profile
});
```

### Further technical details
- EF version: 5.0.4
- EF Extensions version: 5.1.23
- Database Provider: MS Sql Server

**Comment by JonathanMagnan** [comment]
Hello @michaelnero ,

Thank you for reporting, we indeed do not support it `Owned` yet.

We will try to look at it soon (we currently have more issues than we can handle, so we cannot promise any date yet).

Best Regards,

Jon

**Comment by michaelnero** [comment]
Hi @JonathanMagnan thank you for your reply. I am happy to contribute a fix if you point me in the right direction. Otherwise, I've found a workaround in the meantime, so no rush.

**Comment by JonathanMagnan** [comment]
Unfortunately, this part of the code is private so nothing you can really contribute ;(

I hope we will be able to look at it in 1-2 weeks, so I guess all we need for now is some time hehe

**Comment by JonathanMagnan** [comment]
Hello @michaelnero ,

The v5.1.27 has been released.

Our library should now support some basic scenario with `OwnedOne` like this one.

I believe in your case, you need to use the following code:

```csharp
await _db.People.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x =>
new Person
{
    Profile = new
    {
        @event.DisplayName,
        @event.TimeZoneId,
        @event.Avatar
    }
});
```

You "create" the `Person` and assign the OwnedOne

Let me know if that has worked correctly.

Best Regards,

Jon

**Comment by michaelnero** [comment]
Hello, I tried a few scenarios, and a lot of what I needed looks to be supported now. You're awesome, so thank you for looking into this for me.

If it helps, here's what I tried, what didn't work, and what I did to get around the ones that didn't work. I think some of my issues is that I've turned on nullable reference support for the project, and most of my owned types don't have parameterless constructors.

I will let you decide to close this issue, but from my perspective my original issue is fixed. The following is just FYI.

My model looks like this (simplified from the real one):

```
public class Story
{
    public Story(Summary summary)
    {
        Summary = summary;
    }

    public Guid Id { get; set; }
    public Summary Summary { get; set; }
    public bool IsComplete { get; set; }
    public ThreePointEstimate? Estimate { get; set; }

    [Timestamp]
    public byte[]? RowKey { get; set; }
}

[Owned]
public class Summary
{
    public Summary(string name)
    {
        Name = name;
    }

    public string Name { get; set; }
    public string? Description { get; set; }
    public string? DescriptionHtml { get; set; }
}

[Owned]
public class ThreePointEstimate
{
    public double Min { get; set; }
    public double Mode { get; set; }
    public double Max { get; set; }
}
```
========================================

### This worked great:
```
await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    IsComplete = false
});
```

========================================

### This did not work:
```
await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Summary = new
    {
        @event.Name
    }
});
```

with the exception:
```
Message:
Argument types do not match

Stack trace:
      at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilde)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
   at BatchUpdateExtensions.`1.()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at BatchUpdateExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReadModel.Handlers.StoryEventHandlers.<Handle>d__9.MoveNext() in C:\xxx\xxx\xxx\xxx\StoryEventHandlers.cs:line 146
```

But I replaced it with this, which did work:
```
await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Summary = new Summary(@event.Name)
    {
        Name = @event.Name
    }
});
```

========================================

### This did not work:
```
await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Estimate = (null == @event.Estimate) ? null : new ThreePointEstimate
    {
        Min = @event.Estimate.Min,
        Mode = @event.Estimate.Mode,
        Max = @event.Estimate.Max,
    }
});
```

with the exception:
```
Message:
Incorrect syntax near the keyword 'FROM'.
Incorrect syntax near the keyword 'AS'.

Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.(DbCommand , Nullable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
   at BatchUpdateExtensions.`1.()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at BatchUpdateExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReadModel.Handlers.StoryEventHandlers.<Handle>d__8.MoveNext() in C:\xxx\xxx\xxx\xxx\StoryEventHandlers.cs:line 99
```

But I replaced it with this, which did work:
```
if (null == @event.Estimate)
{
    await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
    {
        Estimate = (ThreePointEstimate?)null
    });
}
else
{
    await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
    {
        Estimate = new ThreePointEstimate
        {
            Min = @event.Estimate.Min,
            Mode = @event.Estimate.Mode,
            Max = @event.Estimate.Max,
        }
    });
}
```

**Comment by JonathanMagnan** [comment]
Awesome ;) Thank you for providing us this code.

We will look at the first one about the anonymous type, I believe it could be possible.

The second one which you check for null is probably too hard for now. We will check it but I don't think we will be able for this one.

**Comment by JonathanMagnan** [comment]
Hello @michaelnero ,

The v5.1.30 has been released.

It should now be possible to specify an anonymous type inside an anonymous type such as the code you provided: 

```csharp
await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    Summary = new
    {
        @event.Name
    }
});
```

As for your second scenario, we abandoned it as we didn't find any easy way to make it works.

Let me know if the first one work as expected.

**Comment by michaelnero** [comment]
Hi there, I re-tried the scenario, but I'm afraid I still got an exception. Keep in mind that my owned types do not have parameter-less contructors, which I'm assuming is what's causing this exception based on the error message.

Message:
```
System.ArgumentNullException: 'Value cannot be null. (Parameter 'constructor')'
```

Stack trace:
```
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilde)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
   at BatchUpdateExtensions.`1.()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at BatchUpdateExtensions.`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReadModel.Handlers.StoryEventHandlers.<Handle>d__9.MoveNext() in C:\xxx\StoryEventHandlers.cs:line 106
```

The code I used to trigger this:
```
public async Task Handle(StoryNameChanged @event)
{
    await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
    {
        Summary = new
        {
            @event.Name
        }
    });
}
```

The summary type looks like this:
```
[Owned]
public class Summary
{
    public Summary(string name)
    {
        Name = name;
    }

    public string Name { get; set; }
    public string? Description { get; set; }
    public string? DescriptionHtml { get; set; }
}
```

**Comment by JonathanMagnan** [comment]
Hello @michaelnero ,

Sorry for the delay, I just saw that I forget to answer you.

Unfortunately at this moment, a constructor without parameters is required.

We might eventually change our logic to allow purely anonymous type but behind the scene, we currently create an instance of the type to make it works.

**Comment by michaelnero** [comment]
Hello. Understood. There are plenty of workarounds, so I'm not stressing. 🙂

Thanks for all the work you've done so far on this issue. I'll go ahead and close it.
