### ISSUE TITLE
Not compatible with latest version of Entity Framework Core

### ISSUE THREAD

**Issue by ooples** [zzzprojects/EntityFramework-Extensions#402]
Exception Type:
System.MissingMethodException

Exception Message:
Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.

Exception StackTrace:
   at ?.?[?](DbContext this, IEnumerable`1 ?, List`1 ?)
   at ?.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.?`1.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkUpdateAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.Utils.<>c__DisplayClass30_1`1.<<HandleNetworkTask>b__0>d.MoveNext() in D:\Code Projects\OoplesFinanceAdminClient\Utils.cs:line 633
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass4_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Fallback.AsyncFallbackPolicy.<>c__DisplayClass3_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Fallback.AsyncFallbackEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, Func`3 onFallbackAsync, Func`4 fallbackAction, Boolean continueOnCapturedContext)

Exception Target Site:
?

Exception Source:
Z.EntityFramework.Extensions.EFCore

I get the above exception when I try to use the BulkUpdate command and I'm using the following versions in my proejct:

Microsoft.EntityFrameworkCore.SqlServer v6.0.0-preview.2.21154.2
Z.EntityFramework.Plus.EFCore v6.0.0-preview.1.21102.2-01

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Thank you for reporting.

We are indeed not yet compatible with the `preview2`, only the `preview.`.

We already have a fix that we hope to merge later this week to support the `preview2`.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Just to let you know that the latest version is now compatible with the `preview2`. We still have a small issue to fix on our side but we do not believe that will impact anyone.

If you have a problem, just let us know.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

I will close this issue as we got a very similar from you here: https://github.com/zzzprojects/EntityFramework-Plus/issues/675

Best Regards,

Jon
