### ISSUE TITLE
6.0 Preview 2 - BulkInsert GIS Data

### ISSUE THREAD

**Issue by AwkEng** [zzzprojects/EntityFramework-Extensions#403]
### Description
I am testing your BulkInsert() function.  It has been working great under EF Core 5.  For the heck of it, I tried out EF Core 6.0 Preview 2 and hit an exception when importing GIS data (NetTopologySuite.Geometries.Point)

Let me know if you need any additional information.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Stack trace:

System.Exception: NetTopologySuite.Geometries.Point
   at Z.EntityFramework.Extensions.PropertyZInfo.ConvertValueToProvider(DbContext context, BulkOperation bulkOperation, Object value)
   at ?.?`1.?(? ?)
   at ?.Read()
   at ?.?()
   at ?.Read()
   at ?.?(? ?, DbConnection ?, DbTransaction ?, Int32 ?)
   at ?.?(? ?)
   at ?.?(? ?)
   at ?.Execute(List`1 actions)
   at ?.?(List`1 ?)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at DbContextExtensions.?(DbContext this, Action`1 ?, DbContext ?)
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.?`1.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Application.Asrs.Commands.BulkAddAsrs.BulkAddAsrsCommandHandler.Handle(BulkAddAsrsCommand request, CancellationToken cancellationToken) in C:\...
   at Application.Common.Behaviors.UnhandledExceptionBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\...
[16:06:02 ERR] System.Exception: NetTopologySuite.Geometries.Point
   at Z.EntityFramework.Extensions.PropertyZInfo.ConvertValueToProvider(DbContext context, BulkOperation bulkOperation, Object value)
   at ?.?`1.?(? ?)
   at ?.Read()
   at ?.?()
   at ?.Read()
   at ?.?(? ?, DbConnection ?, DbTransaction ?, Int32 ?)
   at ?.?(? ?)
   at ?.?(? ?)
   at ?.Execute(List`1 actions)
   at ?.?(List`1 ?)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at DbContextExtensions.?(DbContext this, Action`1 ?, DbContext ?)
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.?`1.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
```

### Further technical details
- EF version: EF Core 6.0.0-preview.2.21154.2
- EF Extensions version: 6.0.0-preview.2.21154.2-01
- Database Provider: Postgres 12 + PostGIS 3.1

**Comment by JonathanMagnan** [comment]
Hello @AwkEng ,

Thank you for reporting, we will look at this.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @AwkEng ,

A new version has been released.

Could you try it and let us know if my developer fixed this issue correctly?

**Comment by AwkEng** [comment]
Yes, I believe it is working now.  I got the following exception on a couple tries, but it was intermittent and my bulk inserts have successfully run on 2 separate attempts.  I'm going to do some more testing and open/reopen if I see any other issues.  Thanks for addressing so quickly!

`Npgsql.NpgsqlException (0x80004005): Unknown message code: 0
   at Npgsql.Util.PGUtil.ValidateBackendMessageCode(BackendMessageCode code)
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|202_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|43_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.Read(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.Read()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at ?.?(DbCommand ?, BulkOperation ?, Int32 ?)
   at ?.?(? ?, DbCommand ?)
   at ?.Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Application.StaticLocations.Commands.BulkAddLocations.BulkAddLocationsCommandHandler.Handle(BulkAddLocationsCommand request, CancellationToken cancellationToken) in C:\...
   at Application.Common.Behaviors.UnhandledExceptionBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\...
[23:01:05 ERR] Npgsql.NpgsqlException (0x80004005): Unknown message code: 0
   at Npgsql.Util.PGUtil.ValidateBackendMessageCode(BackendMessageCode code)
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|202_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|43_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.Read(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.Read()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at ?.?(DbCommand ?, BulkOperation ?, Int32 ?)
   at ?.?(? ?, DbCommand ?)
   at ?.Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Application.StaticLocations.Commands.BulkAddLocations.BulkAddLocationsCommandHandler.Handle(BulkAddLocationsCommand request, CancellationToken cancellationToken) in C:\...
   at Application.Common.Behaviors.UnhandledExceptionBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\...
   at Application.Common.Behaviors.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\...
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)`

**Comment by JonathanMagnan** [comment]
Awesome,

I'm not sure if that's related but for the error message you can see the answer of Roji: https://github.com/npgsql/npgsql/issues/2281#issuecomment-451594185

He answered a lot of times the same cause in different issue I found related to this error.
