### ISSUE TITLE
BulkSaveChangesAsync: KeyNotFoundException / The given key '<entityname>' was not present in the dictionary.

### ISSUE THREAD

**Issue by schuettecarsten** [zzzprojects/EntityFramework-Extensions#404]
### Description
I receive an exception of type KeyNotFoundException when trying to save changes using BulkSaveChangesAsync. The model is somewhat complex, but the changes I want to save here are simple: Add some new entities.

ChangeTracker shows the following details (only entities that are not unchanged or referenced are listed here). Details where extracted after the exception, so please notice tha the added BillingPeriod entity has an ID value - this value was set during the BulkSaveChangesAsync call before the exception occured.

```
BillingPeriod {ID: 565} Added
  ID: 565 PK
  AccountID: 1 FK
  EndDate: '27.04.2021 00:00:00'
  RowVersion: <null>
  StartDate: '28.03.2021 00:00:00'
  TenantID: 1 FK
  Account: {ID: 1}
  Tenant: {ID: 1}
TenantEntity<long> {ID: 1} Unchanged
  ID: 1 PK
  Name: 'DefaultTenant'
Account {ID: 1} Unchanged
  ID: 1 PK
  Name: 'DefaultAccount'
  Tenant: {ID: 1}
```

### Exception
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in System.Private.CoreLib.dll
The given key 'BillingPeriod' was not present in the dictionary.

```
Stack trace:
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at .`1.(Int32 , String , Object )
   at .( , DataTable )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at .(DbContext this, List`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 , DbContext )
   at DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 options)
   at DbContextExtensions..()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DbContextExtensions..MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neusta.Shared.DataAccess.EntityFramework.ExtendedEntityFrameworkDataContext`2.
```

### Further technical details
- EF version: 5.0.4
- EF Extensions version: 5.1.27
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Is it possible for your to provide a runnable project with this issue? (You can send it in private here: info@zzzprojects.com).

We are currently unable to retrieve exactly where this dictionary is used and your scenario is rather very simple so, we will be able to reproduce it.

Best Regards,

Jon

**Comment by schuettecarsten** [comment]
I will try to create a project asap.
My workaround is to check the ChangeTracker for entries that have State==EntityState.Added and use the standard SaveChangesAsync.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

A simple reminder that we are here to assist you!

Don't hesitate to provide a runnable project with this issue (You can send it in private here: info@zzzprojects.com).

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten 

Since my previous message, I haven't heard from you!

Don't hesitate to provide a runnable project with this issue (You can send it in private here: info@zzzprojects.com).

Best regards,

Jon

**Comment by buthomas** [comment]
Hi

I'm currently evaluating your extension and I'm facing a similar (or the same) problem. I have the following entity and mapping defined:

```
public class Foo : EntityBase
{
    private Foo()
    {
    }

    private Foo(int value)
        : this()
    {
        Value = value;
    }

    public static Foo Create(int value) => new(value);

    public int Value { get; private set; }
}

public abstract class EntityBase
{
    protected EntityBase()
    {
    }

    protected EntityBase(long id, ulong rowVersion)
    {
        Id = id;
        RowVersion = rowVersion;
    }

    public long Id { get; }

    public ulong RowVersion { get; }

    public override bool Equals(object? obj)
    {
        if (!(obj is EntityBase other))
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        if (this.GetType() != other.GetType())
        {
            return false;
        }

        if (Id.Equals(default) || other.Id.Equals(default))
        {
            return false;
        }

        return Id.Equals(other.Id);
    }

    public static bool operator ==(EntityBase? a, EntityBase? b)
    {
        if (a is null && b is null)
        {
            return true;
        }

        if (a is null || b is null)
        {
            return false;
        }

        return a.Equals(b);
    }

    public static bool operator !=(EntityBase? a, EntityBase? b) => !(a == b);

    public override int GetHashCode() => (this.GetType().ToString() + Id).GetHashCode();
}

public class FooMapping : IEntityTypeConfiguration<Foo>
{
    public void Configure(EntityTypeBuilder<Foo> builder)
    {
        builder.ToTable(name: "Foo");
        builder.HasKey(e => e.Id);
        builder.Property(e => e.RowVersion).HasConversion<byte[]>().IsRowVersion();
        builder.Property(e => e.Value);
    }
}
```

The DB table looks like this:
```
CREATE TABLE [dbo].[Foo](
  [Id] BIGINT CONSTRAINT PK_Foo PRIMARY KEY IDENTITY (1, 1) NOT NULL,
  [RowVersion] ROWVERSION NOT NULL,
  [Value] [int] NULL)
```

And here's a simple insert of a new `Foo`:

```
public class FooService : IFooService
{
    private readonly FooBarDbContext dbContext;

    public FooService(FooBarDbContext dbContext)
    {
        this.dbContext = dbContext;
    }

    public async Task InsertNewAsync(CancellationToken cancellationToken)
    {
        var foo = Foo.Create(42);
        dbContext.Set<Foo>().Attach(foo);
        await dbContext.BulkSaveChangesAsync(cancellationToken);
    }
}
```

This results in a KeyNotFoundException:
```
2021-06-03 09:04:13.7951|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.Collections.Generic.KeyNotFoundException: The given key 'FooBar.Foo' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ?.?`1.?(Int32 ?, String ?, Object ?)
   at ?.SetValue(Int32 position, ? accessor, Object value)
   at ?.?(? ?, DataTable ?)
   at ?.Execute(List`1 actions)
   at ?.?(List`1 ?)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 options)
   at DbContextExtensions.?.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```


Interestingly the problem doesn't happen
* if I ignore the `RowVersion` in the mapping, or
* if I remove the equality overrrides in the `EntityBase` class.

I'm using:
* EF Core version: 5.0.4
* EF Extensions version: 5.1.38
* Database Provider: SqlServer

Any inputs what's going wrong here?

Thanks a lot.

**Comment by JonathanMagnan** [comment]
Hello @buthomas ,

The issue probably happens because you override the `Equals` and `GetHashCode` methods. Doing such a thing usually doesn't make it very user-friendly with a dictionary which is exactly what the error message show.

One of my developers is currently evaluating one solution to add an option for people that override those methods to make it compatible with our library. I should have more detail soon about if we go ahead with this solution or not.

**Comment by JonathanMagnan** [comment]
Hello @buthomas ,

I agree, my developer has a task to add an option to change how our dictionary behaves to support `Equals` and `GetHashCode` for your kind of scenario.

A release with this fix should be done during June.

Thank you for explaining to me how/why you are doing it. This now makes more sense.

Best Regards,

Jon

**Comment by schuettecarsten** [comment]
Sorry for my very late response. My `Equals` and `GetHashCode` implementation is a bit different, but we also implemented them and run into this issue.  Please let us know when a fix is available so I can test it.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten , @buthomas ,

The v5.1.41 has been released.

If you override the `GetHashCode` method, it is now possible to use your own `IEqualityComparer` for dictionary that we use:

```csharp
context.BulkSaveChanges(option =>
{
	option.DictionaryEqualityComparer = new CustomEqualityComparer();
	option.UnsafeMode = true;	
});
```

However, this option requires the option `UnsafeMode` to be true as we will do our best to keep supporting it and make sure unit tests for this continue to run, but we cannot guarantee that it will never have a side effect due to the HashCode being override.

@schuettecarsten , we prefer to keep relying bydefault on the `GetHashCode` as this is the default behavior of a dictionary. It will be weird to change the default behavior on our side.

Let me know if that solution could work for you

**Comment by schuettecarsten** [comment]
I tested this with my own "ReferenceEqualsComparer" that uses ReferenceEquals and RuntimeHelpers.GetHashCode, and it seems to work now. Will do some more testing and let you know if I run into further issues.

**Comment by JonathanMagnan** [comment]
Awesome @schuettecarsten !

We are glad to hear that it is working.

Don't hesitate to contact us with any questions, issues, or feedback.

Best regards,

Jon

**Comment by schuettecarsten** [comment]
I come back to this issue. Since I've implemented this, I can see that the order of newly added entities is mixed up when the changes are written to the database. Might this be caused by using the UnsafeMode or DictionaryEqualityComparer?

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Is it possible for your to provide a runnable project with the minimum code to reproduce this issue?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten,

Since our last conversation, we haven't heard from you. 

Would it be possible to provide a runnable project?

Don't hesitate to contact us if you need assistance. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten , 

A simple reminder that we are here to assist you!

Feel free to provide a runnable project so we can help you better.

Looking forward to hearing from you, 

Jon

**Comment by schuettecarsten** [comment]
@JonathanMagnan I know, thank your for the reminder. I am currently working on this, and it's a greater task, as I am not sure if this problem is caused by the way how we internally work with our entity lists. I will come back to this soon.
