### ISSUE TITLE
UpdateFromQuery doesn't appear to work with InMemoryDatabase

### ISSUE THREAD

**Issue by schil227** [zzzprojects/EntityFramework-Extensions#405]
### Description
While using `UpdateFromQuery` works fine on a regular database instance, when running it against an InMemoryDatabase (for the purpose of unit testing) the query fails to obtain the object to update.

### Exception
Exception message: **Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException:** *'Attempted to update or delete an entity that does not exist in the store.'*

```
at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry)
at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger)
at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IList`1 entries)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
at BatchUpdateExtensions.`1.()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at <REDACTED>.TeamClientSyncLogicTests.<SyncTeamClient_WhenClientTeamOutOfSync_GetsEndDatedAndReplaced>d__7.MoveNext() 
```

### Code

This appears to be the minimum reproducible code:

In the Unit test:
``` C#
	var builder = new DbContextOptionsBuilder<MyContext>();
	builder.EnableSensitiveDataLogging();
	_context = new MyContext(builder.UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);

...

	_context.ClientTeams.Add(new ClientTeam
	{
		ClientNumber = 1,
		ClientTeamRespId = 1,
		EmployeeNumber = 222,
		DateBegin = DateTime.Now,
		DateEnd = DateTime.Now.AddDays(5)
	});

	await _context.SaveChangesAsync().ConfigureAwait(false);

	await _context.ClientTeams
		.Where(c => c.ClientTeamId == 1)
		.UpdateFromQueryAsync(x => new ClientTeam { DateEnd = DateTime.Now });
```

The ClientTeam POCO:
``` C#
	public partial class ClientTeam
	{
		public int ClientTeamId { get; set; }
		public int ClientNumber { get; set; }
		public byte ClientTeamRespId { get; set; }
		public int EmployeeNumber { get; set; }
		public DateTime DateBegin { get; set; }
		public DateTime DateEnd { get; set; }

		public virtual Client ClientNumberNavigation { get; set; }
	}
```

... and the `ClientTeam` object as defined in the context:
``` C#
	modelBuilder.Entity<ClientTeam>(entity =>
	{
		entity.HasKey(e => new { e.ClientTeamId, e.DateEnd });

		entity.ToTable("t_client_team");

		entity.Property(e => e.ClientTeamId)
			.HasColumnName("client_team_id")
			.ValueGeneratedOnAdd();

		entity.Property(e => e.DateEnd)
			.HasColumnName("date_end")
			.HasColumnType("smalldatetime");

		entity.Property(e => e.ClientNumber).HasColumnName("client_number");

		entity.Property(e => e.ClientTeamRespId).HasColumnName("client_team_resp_id");

		entity.Property(e => e.DateBegin)
			.HasColumnName("date_begin")
			.HasColumnType("smalldatetime");

		entity.Property(e => e.EmployeeNumber).HasColumnName("employee_number");

		entity.HasOne(d => d.ClientNumberNavigation)
			.WithMany(p => p.ClientTeams)
			.HasForeignKey(d => d.ClientNumber)
			.OnDelete(DeleteBehavior.ClientSetNull)
			.HasConstraintName("R_195");
	});
```
Here's an image for clarity (note, code had to be altered slightly to censor company details). As you can see, the ClientTeam exists in the context, however the exception suggests that EFExtensions cannot find it. Further, doing a simple `var result = await _context.ClientTeams.Where(c => c.ClientTeamId == 1).ToListAsync();` retrieved the object.
![efe_issue](https://user-images.githubusercontent.com/3317989/113928778-d77af880-97b4-11eb-8e91-257036627a1b.PNG)

Please reach out if there's anything you'd like me to try, I could certainly be doing something stupid on my end. Thanks for your time.

### Further technical details
- EF version: 5.0.0 (Microsoft.EntityFrameworkCore)
- EF Extensions version: 5.1.30
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Thank you for reporting, we will look at it.

**Comment by JonathanMagnan** [comment]
Hello @schil227 ,

We finally find out what's happening,

The problem is that you try to change the key. The `DateEnd` you try to update is part of your key:

```csharp
entity.HasKey(e => new { e.ClientTeamId, e.DateEnd });
```

Since we need to re-attach the item after and set it as modified, Entity Framework is no longer to retrieve the original entity which cause the following issue.

Unfortunately a key cannot be modified, even if we use some workaround to make it works and go to a step further, then the following error will happen:

```txt
InvalidOperationException: The property 'ClientTeam.DateEnd' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal.
```

Let me know if that explains correctly why this issue is hapenning
Best Regards,

Jon

**Comment by schil227** [comment]
Thanks for looking into this Jonathan - initially I had tried using straight EF Core to set the primary key, and I encountered the `InvalidOperationException` you have above, which is why I changed it to `UpdateFromQuery` in the first place. 

Using `UpdateFromQuery` works; it sets the value in the database despite it being part of the key; Is this because the actual database instance is less restrictive than the in-memory one, which is strictly tied to the context? 

>Since we need to re-attach the item after and set it as modified, Entity Framework is no longer to retrieve the original entity which cause the following issue.

Would it be possible to set the entity as non-tracking so it doesn't have to be re-attached to the context?

**Comment by JonathanMagnan** [comment]
Hello @schil227 ,

Unfortunately, that's not possible at this moment.

We use `Entity Framework` to save the entity in their memory provider. So the entity must be attached to be saved.

To make it works, we will need to save directly in the "memory" provider and skip the `Entity Framework` part which is somewhat I don't think we are ready to do right now.

**Comment by schil227** [comment]
Interesting - Thanks you again for the insight, this was a tricky problem to figure out. I'll close the issue - hopefully someone else finds this information useful.
