### ISSUE TITLE
BulkInsert for PostgreSQL throws exception if AutoMapOutputDirection and InsertIfNotExists options used

### ISSUE THREAD

**Issue by DmitriyMarov** [zzzprojects/EntityFramework-Extensions#407]
### Description

If I use bulk insert with both `AutoMapOutputDirection` and `InsertIfNotExists` flags enabled, it throws exception. 

```
context.BulkInsert<Client>(new List<Client> { clients }, options =>
                {
                    options.AutoMapOutputDirection = true;
                    options.InsertIfNotExists = true;
                    options.BatchSize = 100;
                });
```

This works fine on MS SQL configuration, so I think such options combination is allowed.

### Exception

```
Exception message: "Devart.Data.PostgreSql.PgSqlException (0x80004005): cannot insert multiple commands into a prepared statement"
Stack trace: 
 at Devart.Data.PostgreSql.x.a(Boolean A_0, Boolean A_1, Char A_2, Boolean A_3)
   at Devart.Data.PostgreSql.f.f(s A_0)
   at Devart.Data.PostgreSql.s.o()
   at Devart.Data.PostgreSql.PgSqlCommand.InternalPrepare(Boolean implicitPrepare, Int32 startRecord, Int32 maxRecords)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at .(DbCommand , BulkOperation , Int32 )
   at .( , DbCommand )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at .BulkInsert[T](BulkOperation`1 this, DbContext context, List`1 list, Boolean isManager, List`1 entitiesToUpdate, Type type, String typeName)
   at .`1.(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .BulkInsert[T](DbContext this, BulkOperation`1 bulkOperation, IEnumerable`1 entities2, List`1 entitiesToUpdate)
   at .BulkInsert[T](BulkOperation`1 this, DbContext context, IEnumerable`1 entities, List`1 entitiesToUpdate)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
```

### Fiddle or Project (Optional)
Simple demo to reproduce issue: https://github.com/DmitriyMarov/BulkDemo (Don't forget to change connection string in app.config and run createtables.sql script on your postgres db)

### Further technical details

- EF version: 6.4.0
- EF Extensions version: 5.1.29
- Database Provider: Devart.Data.PostgreSql 7.20.1860

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov ,

The v5.1.31 has been released.

Could you test it and let us know if everything is now working as expected?

Best Regards,

Jon

**Comment by DmitriyMarov** [comment]
Thanks, this bug was fixed. Some issues still left, I don't know if it related to the latest changes, but unfortunately I can't reproduce it in demo. Maybe you have some thoughts about this exception? I'll try to give more information later.
![image](https://user-images.githubusercontent.com/16375594/115560813-9eb34700-a2bd-11eb-8121-6b62e78464ad.png)

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov ,

Thank you, we will look at it.

That's indeed very weird, it seems there is no `open` parenthesis. It doesn't look to have any column to insert.

I'm not sure at this moment if the issue is on our side or on `DevArt` side. However, we will make some tests to discover what could cause this.

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov ,

We tried to reproduce it but unfortunately, we were not able either.

In the `SQL`, we see that no column looks to be provided which seems to lead to an ending `)` without an opening '(' + some column (we don't manage that part, devart generate it).

After talking to my developer, he doesn't think that even by spending more hours he will be able to find out how to reproduce it correctly.

The only hint we have at this moment is why no column to insert is provided, perhaps that will give you an idea

**Comment by DmitriyMarov** [comment]
Issue was fixed after setting "InsertIfNotExists" option to true, I don't know why, because all inserted entities were unique, but it is so.

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov, 

Thank you for the update. 

Don't hesitate to contact us if you have any issues or questions. 

Best regards, 

Jon
