### ISSUE TITLE
Issue with Bulkinsert / bulkupdate

### ISSUE THREAD

**Issue by killermoon** [zzzprojects/EntityFramework-Extensions#419]
Hi, 

When we try to update with bulk my table with this : 

 public string UpdateMemoArticles(List<MemoToSynchronizeResponse> list)
        {
            DapperPlusManager.RemoveEntity<MemoToSynchronizeResponse>();

            DapperPlusManager.Entity<MemoToSynchronizeResponse>()
                .Table("Article.ArticlesMemoToSynchronize")
                .Key(x => new { x.ArtId, x.PharmId })
                .Map(x => new
                {
                    ErrorMessage = x.ErrorMessage, LatestSynchroAttempt = x.LatestSynchroAttempt,
                    PushStatusType = x.PushStatusType
                });
            var sb = new StringBuilder();
            var resultInfo = new ResultInfo();

            using (SqlConnection connection = DalBase2.OpenConnection(this.connectionString))
            {
                try
                {
                    sb.AppendLine($"-----> ismap: {DapperPlusManager.IsMappedEntity<MemoToSynchronizeResponse>()}");
                    connection.UseBulkOptions(options =>
                        {

                            options.Debug1 = true;
                            options.RetryCount = 10;
                            options.RetryInterval = TimeSpan.FromSeconds(1);
                            options.ResultInfo = resultInfo;
                            options.UseRowsAffected = true;
                            options.UseLogDump = true;
                            options.LogDump = sb;
                            
                            options.Log = s => sb.AppendLine("-----> " + s);
                        }).BulkUpdate(list);
                   
                }
                catch (Exception e)
                {
                    sb.AppendLine("-----> UpdateMemoArticles : " + e.Message + " - " + e.StackTrace);
                }

                sb.AppendLine($"-----> UpdateMemoArticles : Rows Affected: {resultInfo.RowsAffected} - RowsDeleted: {resultInfo.RowsAffectedDeleted} - RowsInserted: {resultInfo.RowsAffectedInserted} - RowsUpdated: {resultInfo.RowsAffectedUpdated} ");

                return sb.ToString();
            }
          
        }

### Exception
---->-----> ismap: True
-- Executing Command:

/* SELECT server information */
SELECT  @@VERSION

/* SELECT table information */
SELECT  DestinationTable.Name AS DestinationName ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsInsertTrigger') = 1 )
        ) AS HasInsertTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsUpdateTrigger') = 1 )
        ) AS HasUpdateTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsDeleteTrigger') = 1 )
        ) AS HasDeleteTrigger
FROM    (SELECT @Table_0 AS Name) AS DestinationTable  
        LEFT JOIN sys.synonyms  AS B ON B.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(B.base_object_name)
ORDER BY DestinationName

/* SELECT column information */
SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        D.Name AS TypeName,
        (CASE WHEN E.base_object_name IS NOT NULL THEN 1 ELSE 0 END) AS IsSynonym,
        D.is_user_defined,
        F.name,
		CASE WHEN C.default_object_id  = 0 THEN 'ZZZ_NO_DEFAULT' ELSE ISNULL(OBJECT_DEFINITION(C.default_object_id), 'ZZZ_ERROR_DEFAULT_ZZZ') END AS DefaultValueSql
FROM    (SELECT @Table_0 AS Name) AS DestinationTable
        LEFT JOIN sys.synonyms  AS E ON E.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(E.base_object_name)
        LEFT JOIN sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder

-- @Table_0: [Article].[ArticlesMemoToSynchronize] (Type = String, Size = 37)
-- CommandTimeout:30
-- Executing at 11/06/2021 15:48:28
-----> -- Executing Command:

/* SELECT server information */
SELECT  @@VERSION

/* SELECT table information */
SELECT  DestinationTable.Name AS DestinationName ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsInsertTrigger') = 1 )
        ) AS HasInsertTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsUpdateTrigger') = 1 )
        ) AS HasUpdateTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsDeleteTrigger') = 1 )
        ) AS HasDeleteTrigger
FROM    (SELECT @Table_0 AS Name) AS DestinationTable  
        LEFT JOIN sys.synonyms  AS B ON B.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(B.base_object_name)
ORDER BY DestinationName

/* SELECT column information */
SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        D.Name AS TypeName,
        (CASE WHEN E.base_object_name IS NOT NULL THEN 1 ELSE 0 END) AS IsSynonym,
        D.is_user_defined,
        F.name,
		CASE WHEN C.default_object_id  = 0 THEN 'ZZZ_NO_DEFAULT' ELSE ISNULL(OBJECT_DEFINITION(C.default_object_id), 'ZZZ_ERROR_DEFAULT_ZZZ') END AS DefaultValueSql
FROM    (SELECT @Table_0 AS Name) AS DestinationTable
        LEFT JOIN sys.synonyms  AS E ON E.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(E.base_object_name)
        LEFT JOIN sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder

-- @Table_0: [Article].[ArticlesMemoToSynchronize] (Type = String, Size = 37)
-- CommandTimeout:30
-- Executing at 11/06/2021 15:48:28

-- Completed at 11/06/2021 15:48:28
-- Result: SqlDataReader

-----> -- Completed at 11/06/2021 15:48:28
-- Result: SqlDataReader

-----> UpdateMemoArticles : Original DataSource Type: System.Collections.Generic.List`1[[ArticlesPrices.Dto.MemoToSynchronizeResponse, ArticlesPrices.Dto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
IsStreaming: False
IteratorType: ?
 -    at Z.BulkOperations.BulkOperation.?()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkUpdate()
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
   at Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
   at Z.Dapper.Plus.DapperPlusActionSet`1..ctor(BaseDapperPlusActionSet oldActionSet, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1.BulkUpdate[T](String mapperKey, T item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1.BulkUpdate[T](T item, Func`2[] selectors)
   at ArticlesPrices.Service.Business.v1.ArticlePriceStrategyDalV1.UpdateMemoArticles(List`1 list)
-----> UpdateMemoArticles : Rows Affected: 0 - RowsDeleted: 0 - RowsInserted: 0 - RowsUpdated: 0 

this is the type definition we have  : 
    [Serializable]
    public class MemoToSynchronizeResponse
    {
        public MemoToSynchronizeResponse(int artId, int pushStatusType)
        {
            ArtId = artId;
            PushStatusType = pushStatusType;
            LatestSynchroAttempt = DateTime.Now;
        }

        public int ArtId { get; set; }

        public int PharmId { get; set; }

        public int PushStatusType { get; set; }

        public DateTime? LatestSynchroAttempt { get; set; }

        public string ErrorMessage { get; set; }
    }

**Comment by killermoon** [comment]
for some information, we have the same problems on different types, in the latest version. 

We have a lot of request and are hosted on WCF (i know :( but we can't change everything right now, i will say history) and we go to sql server 2019  

---->Original DataSource Type: System.Collections.Generic.List`1[[ArticlesPrices.Dto.HistBuyPriceToSynchronizeResponse, ArticlesPrices.Dto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
IsStreaming: False
IteratorType: ?
 -    at Z.BulkOperations.BulkOperation.?()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkDelete()
   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusAction..ctor(BaseDapperPlusActionSet action, String key, DapperPlusActionKind kind, Object dataSource)
   at Z.Dapper.Plus.DapperPlusActionSet`1.AddAction(String mapperKey, DapperPlusActionKind actionKind, TEntity item)
   at Z.Dapper.Plus.DapperPlusActionSet`1..ctor(BaseDapperPlusActionSet oldActionSet, String mapperKey, DapperPlusActionKind actionKind, TEntity item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1.BulkDelete[T](String mapperKey, T item, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1.BulkDelete[T](T item, Func`2[] selectors)
   at ArticlesPrices.Service.Business.v1.ArticlePriceStrategyDalV1.DeletePrices(List`1 list)
   at ArticlesPrices.Service.Business.v1.ArticlePriceStrategyV1.SetPricesResult(List`1 responses). Original DataSource Type: System.Collections.Generic.List`1[[ArticlesPrices.Dto.HistBuyPriceToSynchronizeResponse, ArticlesPrices.Dto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
IsStreaming: False
IteratorType: ?

**Comment by JonathanMagnan** [comment]
Hello @killermoon ,

Is there a reason why `options.Debug1 = true;` is enabled?

This option when enabled throws an exception 100% of the time. Not because there is an exception but because this is how the options work (I don't think it was intended to really let people use it).

So at this moment, I'm not sure if there is a bug somewhere else or this is simply because you enabled that option.

Let me know more about it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @killermoon ,

Since our last conversation, we haven't heard from you!

As mentioned in my previous message, when the `options.Debug1 = true;` is enabled, it throws an exception. 

Let us know more about your issue so that we can assist you better!

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello again @killermoon ,

A simple reminder that we are here to assist you!

Feel free to provide more information about your issue so that we can help you better!

Best regards,

Jon
