### ISSUE TITLE
Oops! The method 'GetAllPath' failed with error: more than one table has been found

### ISSUE THREAD

**Issue by souchprod** [zzzprojects/EntityFramework-Extensions#430]
### Description
Hi, using BulkSaveChangeAsync(), trying to save a few operations (insert), i get an exception.

The mentioned table is a view.

            builder.ToView("view_catalog_entries");
            builder.HasKey(e => e.Id);

With the EF SaveChangesAsyn(), no error.

Issue under v 5.1.5, updated to 5.2.6 with no improvement (but better error message :))

### Exception
An exception resulting in an error 500 ("Internal Server Error") was encountered. System.Exception: Oops! The method 'GetAllPath' failed with error: more than one table has been found entityTypeNavigation.TargetEntityType.Name = *****.ViewCatalogEntry
   at Z.EntityFramework.Extensions.EntityTypeZInfo.?(IEntityType ?)
   at Z.EntityFramework.Extensions.EntityTypeZInfo.GetFlattenHierarchyProperties(IEntityType entityTypeMaster)
   at Z.EntityFramework.Extensions.EntityTypeZInfo..ctor(IEntityType entityType)
   at PublicExtensions.?.?(IEntityType ?)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at PublicExtensions.ToZInfo(IEntityType entityType)
   at ?.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 options)
   at DbContextExtensions.?.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkSaveChangesAsync(DbContext this, Action`1 options, CancellationToken cancellationToken)

### Further technical details
- EF version: 5.0
- EF Extensions version: 5.2.6
- Database Provider: MariaDb

**Comment by souchprod** [comment]
Edit: 

Changing from
`builder.ToView("...");`
to
`builder.ToTable("...");`
fix the problem. However this seems not normal, and will probably product some adverse event somewhere else on my code.
Thanks to investigate

**Comment by JonathanMagnan** [comment]
Hello @souchprod ,

Thank you for reporting, we will look at it.

We indeed don't have a lot of test with the `ToView`, so we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @souchprod ,

My developer failed to reproduce your exact error.

Is it possible to provide a runnable project or even some part of your code to help him to reproduce it?

Here is what he asked:

- The view
- The entity
- The navigation between all entities and how they are set (`ViewCatalogEntry` look to be the more important one)

The best is of course a runnable project (you can send it in private here: info@zzzprojects.com) but if you cannot, try to give us as much information as you can and he will try again.

**Comment by JonathanMagnan** [comment]
Hello @souchprod 

Since our last conversation, we haven't heard from you!

As mentioned in my previous message, could you provide a runnable project or parts of your code to help him to reproduce the issue?

Here is what he asked:

- The view
- The entity
- The navigation between all entities and how they are set (ViewCatalogEntry look to be the more important one)

Don't hesitate to provide a runnable project in private: info@zzzprojects.com 

Looking forward to hearing from you, 

Jon

**Comment by souchprod** [comment]
Hello Jon,

Yes, i will try to reproduce is a small project asap

**Comment by JonathanMagnan** [comment]
Awesome! 

I will be looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @souchprod ,

Did you make any progress in reproducing this issue in a standalone project?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @souchprod ,

Since our last conversation, we haven't heard from you!

Unfortunately, this issue will be closed. 

However, we will be glad to open it once you can provide a standalone project. 

Best Regards,

Jon
