### ISSUE TITLE
6.0.0-preview.6.21352.1-2 Runtime Error: System.TypeInitializationException: 'The type initializer for 'Microsoft.AspNetCore.Hosting.HostingLoggerExtensions' threw an exception.'

### ISSUE THREAD

**Issue by aherrick** [zzzprojects/EntityFramework-Extensions#433]
Receiving the following error on the latest NET6 preview7 version. `6.0.0-preview.6.21352.1-2`

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.AspNetCore.Hosting.HostingLoggerExtensions' threw an exception.
  Source=Microsoft.AspNetCore.Hosting
  StackTrace:
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\source\aherrick\Cellar\Cellar.Api\Program.cs:line 452
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\source\aherrick\Cellar\Cellar.Api\Program.cs:line 452

Inner Exception 1:
MissingMethodException: Method not found: 'System.Action`3<Microsoft.Extensions.Logging.ILogger,!!0,System.Exception> Microsoft.Extensions.Logging.LoggerMessage.Define(Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, System.String, Boolean)'.
```

**Comment by aherrick** [comment]
Actually looks like Preview7 just wasn't installed. Sorry for the confusion!

**Comment by JonathanMagnan** [comment]
No problem,

We just saw with your issue that `Preview7` is available so that's a good thing.

We will run our unit tests and check if any fix is necessary.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
