### ISSUE TITLE
Issues with BulkUpdate, auditing of specific columns, and owned entity types

### ISSUE THREAD

**Issue by a-keen** [zzzprojects/EntityFramework-Extensions#442]
### Description
I am having issues implementing `BulkUpdate` with auditing of specific columns and owned entity types.  I have found that I can achieve a `BulkUpdate` of an owned type with a `ColumnInputExpression`, but I receive the exception below when I try to use `ColumnMappings`.  I would like to use the `ColumnMappings` approach so that I can set the `ColumnMappingAuditModeType` to Include ONLY those specific columns.  

My problem is that the columns to be updated are dynamic and will change so I need to dynamically build the inputs and I would like the auditing to be limited to only these input fields or better yet the fields that have changed.  Maybe there is another approach to my problem that I am missing. I originally started with `UpdateFromQuery`, is it possible to enable auditing for that?

### Exception
Run-time exception (line 35): An error occured while resolving mapping by name. See the inner exception for details

Stack Trace:

[System.Exception: Missing Column : Name
On entity : Customer
On Table : [dbo].[Customers]]
   at Z.BulkOperations.BulkOperation.(String , Boolean , Boolean , Boolean )
   at Z.BulkOperations.BulkOperation.()

[System.Exception: An error occured while resolving mapping by name. See the inner exception for details]
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkUpdate()
   at .BulkUpdate[T](BulkOperation`1 this, DbContext context, List`1 list, Boolean isManager, Type type, String typeName)
   at .`1.(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .BulkUpdate[T](DbContext this, BulkOperation`1 bulkOperation, IEnumerable`1 entities2)
   at .BulkUpdate[T](BulkOperation`1 this, DbContext context, IEnumerable`1 entities)
   at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at Program.Main() :line 35

### Fiddle
https://dotnetfiddle.net/m5KnsT
See comment around lines 45-50.

**Comment by a-keen** [comment]
Hi @JonathanMagnan,

Thank you for your response and the proposed solution. This appears to be working for me!

Thanks,
Andrew
