### ISSUE TITLE
The Provider could not be resolved. (Devart)

### ISSUE THREAD

**Issue by Bjoern78** [zzzprojects/EntityFramework-Extensions#449]
Wenn i use the BulkInsert im get the The Provider could not be resolved Exeption. 

### Exception

Exception message:The Provider could not be resolved. You must explicitly set the Provider.
Stack trace:   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
   at 
```

I am Using:
Devart.Data.MySQl.EFCore (8.19.2001)
Z.EntityFramework.Extensions.EFCore (5.2.16)

**Comment by JonathanMagnan** [comment]
Hello @Bjoern78 ,

Thank you for reporting, we will look at it.

Best Regards,

Jon
