### ISSUE TITLE
After migration of solution to .NET 6

### ISSUE THREAD

**Issue by newjantheva** [zzzprojects/EntityFramework-Extensions#454]
### Description
Throws below:

### Exception
Unhandled exception. System.TypeInitializationException: The type initializer for 'Z.BulkOperations.LicenseManager' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Z.BulkOperations.LicenseManager..cctor()
 
```
Exception message:
Stack trace:
  --- End of inner exception stack trace ---
   at Z.BulkOperations.LicenseManager.IsLicenseAdded()
   at Z.EntityFramework.Extensions.LicenseManager.IsLicenseAdded()
   at App.Infrastructure.AppDbContext.InitializeZzzEntityFramework() in D:\a\1\s\App\App.Infrastructure\AppDbContext.cs:line 131
   at App.Infrastructure.AppDbContext..ctor(IOptions`1 settings) in D:\a\1\s\App\App.Infrastructure\AppDbContext.cs:line 23
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at App.Web.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IWebshellRoutingService routing, IServiceProvider serviceProvider, IOptions`1 devSettings) in D:\a\1\s\App\App.Web\Startup.cs:line 81
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at App.Web.Program.Main(String[] args) in D:\a\1\s\App\App.Web\Program.cs:line 10

### Further technical details
- EF version: 6.0.0
- EF Extensions version: 6.13.2
-

**Comment by newjantheva** [comment]
@JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @newjantheva ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it to info@zzzprojects.com if you need to keep it private.

My developer did some tests and never got the issue. So we are currently missing something to be able to reproduce it.

Best Regards,

Jon

**Comment by newjantheva** [comment]
Hello @JonathanMagnan 

I built an Asp.Net Core application that runs well locally. But when I deploy it to azure I get a 500.30 error. What I did was:

1. Open Kudu,
2. Open Cmd,
3. Navigate to wwwroot folder
4. Run dotnet MyApp.dll

Then the error appeared as mentioned.

Best Regards,

Newjan

**Comment by JonathanMagnan** [comment]
Hello @newjantheva ,

Do you have any `Newtonsoft.Json` dll in your wwwroot folder? If yes, that's the version?

Our library has a dependency to this dll, so you should find it.

Let me know as we cannot really debug this one on our side as it seems more a deployment issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello again!

Since our last conversation, we haven't heard from you. 

Let me know if you have any Newtonsoft.Json dll in your wwwroot folder?

Don't hesitate to contact us if you need further assistance. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @newjantheva, 

A simple reminder that we are here to assist you. 

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @newjantheva,

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide more information. 

Best regards,

Jon
