### ISSUE TITLE
BulkInsertAsync table/relation does not exist exception

### ISSUE THREAD

**Issue by uuupsgit** [zzzprojects/EntityFramework-Extensions#460]
### Description

I am using BulkInsertAsync from Z.EntityFramework.Extensions.EFCore (version 5.13.5)

Here's my code:
```
public async Task BulkInsertAsync(IEnumerable<TEntity> localList, int? batchSize = null)
{
    if (localList.Any())
    {
        await this._dbContext.BulkInsertAsync(localList, this.GetBulkOptions(batchSize: batchSize));
    }
}

private Action<BulkOperation<TEntity>> GetBulkOptions(bool includeGraph = true, int? batchSize = null)
{
    return x =>
    {
        x.IncludeGraph = includeGraph;
        x.InsertIfNotExists = true;
        x.BatchTimeout = 600;
        if (batchSize.HasValue)
        {
            x.BatchSize = batchSize.Value;
        }
    };
}
```
### Exception

Periodically I get errors like this (when inserting data into the same existing table):

"42P01: table "zzzprojects_265af66a_1c8b_41da_b388_db203ab47c09" does not exist"
"42P01: relation "zzzprojects_846a5481_e104_45e1_bce4_e9393f5886a2" does not exist"

Stack trace:

```
at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at .(DbCommand , BulkOperation , Int32 )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at .(DbContext this, List`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 , DbContext )
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Persistence.Impl.Repository`1.BulkInsertAsync(IEnumerable`1 localList, Nullable`1 batchSize) in  [code files/locations removed]
```

Possibly errors occur when inserting a large amount of data (up to 10,000).

### Further technical details
- EF version: Microsoft.EntityFrameworkCore 5.0.11
- EF Extensions version: Z.EntityFramework.Extensions.EFCore 5.13.5
- Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL v5.0.10

**Comment by JonathanMagnan** [comment]
Hello @uuupsgit ,

Thank you for reporting, I'm not sure if we will be able to reproduce it but he will try and let you know about our result.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @uuupsgit ,

We have not been able to reproduce the issue using the same configuration as you. We are probably missing something else on our side.

Can you provide a runnable project/solution with the issue you describe? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

You can send private files here: info@zzzprojects.com

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello again @uuupsgit,

Since our last conversation, we haven't heard from you. 

As mentioned in my previous we weren't able to reproduce your issue. 

Is it possible for you to create a runnable project reproducing the issue?

Best regards, 

Jon

**Comment by uuupsgit** [comment]
Hello @JonathanMagnan,

Sorry for the delay in responding. 

I will try to reproduce this situation in a new test project and come back here.

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Did you get the time to reproduce the issue?

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by uuupsgit** [comment]
I could not reproduce this situation in a new project. Therefore, I close the current issue.

**Comment by JonathanMagnan** [comment]
Hello @mayfieldiv ,
 
Could you look at the following answer and see if that could solve your issue: https://github.com/zzzprojects/Bulk-Operations/issues/75#issuecomment-1647644133

When changing the pooling mode into `session`, the same connection will be used through all the bulk operations (the temporary table only exists within the same connection)

Let me know if that worked.

Best Regards,

Jon
