### ISSUE TITLE
PK violation on bulk merge

### ISSUE THREAD

**Issue by andymartin** [zzzprojects/EntityFramework-Extensions#461]
### Description
Bulk merge gives a duplicate key violation on primary key.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:  23505: duplicate key value violates unique constraint "ohlcv_nq_fut_195m_pkey"
Stack trace:

Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "ohlcv_nq_fut_195m_pkey"

DETAIL: Key ("timestamp")=(2021-12-21 00:30:00-05) already exists.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at .(DbCommand , BulkOperation , Int32 )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkMerge()
   at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```

### Usage

```
await using var tx = await symbolDataProvider.Database.BeginTransactionAsync();
await symbolDataProvider.BulkMergeAsync(mapped, options =>
{
    options.ColumnPrimaryKeyExpression = c => c.Timestamp;
});
await tx.CommitAsync();

```

### Table structure
```
CREATE TABLE IF NOT EXISTS ohlcv_nq_fut_195m (
  timestamp TIMESTAMPTZ NOT NULL,
  open      NUMERIC NOT NULL,
  high      NUMERIC NOT NULL,
  low       NUMERIC NOT NULL,
  close     NUMERIC NOT NULL,
  volume    NUMERIC NOT NULL,
  PRIMARY KEY(timestamp)
```

### Further technical details
- EF version:     <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.1" />
- EF Extensions version:     <PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="6.13.7" />
- Database Provider:  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.2" />

**Comment by JonathanMagnan** [comment]
Hello @andymartin ,

Thank you for reporting. We will look at how to comparison with the timestamp is made.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @andymartin ,

My developer has a hard time reproducing the problem but told me it can highly depend on the version of the `Npgsql.EntityFrameworkCore.PostgreSQL` you are using as the timestamp logic got some breaking changes in the past. Could you let him know which version you are using?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello again! 

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, Could you let us know which version of  Npgsql.EntityFrameworkCore.PostgreSQL you are using?

Don't hesitate to contact us if you have any questions. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @andymartin,

A simple reminder that we are here to assist you. 

Let me know if you need more help. 

Best regards, 

Jon

**Comment by andymartin** [comment]
Thanks @JonathanMagnan. I've been out of town for a bit and unable to respond.

I am using Npgsql.EntityFrameworkCore.PostgreSQL version 6.0.2. If there is a better version to use I'm happy to upgrade/downgrade.

Thanks,
Andy

**Comment by andymartin** [comment]
I thought there was a possibility that there were duplicates in my insert batch, but I added an assert for that and they're all unique.  AllowDuplicateKeys is a workable solution because if I'm getting an existing row it's just because my query pulled back more data than it needed to gapfill the table, so it's fine to overwrite.

I'll see if I can set up a repro project. Thanks for your help!

**Comment by JonathanMagnan** [comment]
Thank,

With a project, it will sure be way easier on our side to look at it.

**Comment by JonathanMagnan** [comment]
Hello @andymartin, 

Since our last conversation, we haven't heard from you. 

We will re-open this issue as soon as we get a project that will allow us to reproduce it. 

Don't hesitate to contact us if you need more information. 

Best regards, 

Jon
