### ISSUE TITLE
Optional Owned Entity Types not supported exception on BulkMergeAsync

### ISSUE THREAD

**Issue by meinsiedler** [zzzprojects/EntityFramework-Extensions#473]
### Description
We have configured an _optional_ owned entity type in the same table as the entity. We receive the following `TargetInvocationException` when using `BulkMergeAsync`.

Unfortunately, we cannot reproduce the issue in a simple sample program and this occurs only in our actual project, so it would be helpful if we could get any hint on where/why in the EF extensions source code this exception is thrown and what we could do to find the issue in our code.

While trying to reproduce the issue in a sample program, we found #472 which maybe has something to do with it.

Optional owned entity types should be supported by now (EF Core 6.0.0) and so we don't understand where the exception message (`Oops! An Owned reference cannot be null (not supported yet) when the owned is on the same table as the entity`) comes from.

### Exception
```
Exception message: Oops! An Owned reference cannot be null (not supported yet) when the owned is on the same table as the entity
Stack trace:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Oops! An Owned reference cannot be null (not supported yet) when the owned is on the same table as the entity.
   at ?.?`1.?(? ?, String ?)
   at ?.?(? ?, DbCommand ?)
   at ?.?(? ?, DbCommand ?)
   at ?.?(? ?, DbCommand ?)
   at ?.?(? ?, DbCommand ?)
   at ?.Execute(List`1 actions)
   at ?.?(List`1 ?)
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkMerge()
   at ?.BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at Z.EntityFramework.Extensions.PublicInternalBulkOperationManager.BulkMergeCast[T](BulkOperation`1 this, DbContext context, List`1 list)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ?.BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at ?.?(DbContext this, List`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, StateManager ?, IReadOnlyList`1 ?, Action`1 ?)
   at ?.?(DbContext this, Action`1 ?, DbContext ?)
   at DbContextExtensions.?(DbContext this, Action`1 ?, DbContext ?)
   at ?.BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.?`1.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkMergeAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)

```

### Further technical details
- EF version: `Microsoft.EntityFrameworkCore.SqlServer` 6.0.0
- EF Extensions version: 6.13.12
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

Same as the other issue you provider, at this moment, our library for methods such as BulkMerge doesn't support really well optional Owned.

We force them to be not null. One of the major reasons for this is that the list provided could contain sometime the owned and sometimes not which required 2 different logic that we still don't handle.

I will look with my developer if we could do something in the short term.

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Thank you, @JonathanMagnan 

I'll close this issue and as it looks like it's basically the same as #472 .
