### ISSUE TITLE
Composite Key abstraction

### ISSUE THREAD

**Issue by puschie286** [zzzprojects/EntityFramework-Extensions#474]
### Description
Hi, we would like to know how to correctly abstract the key expression. Currently we have have an IEntity interface with an key property as object array - but this doesnt work for updates ( it works somehow for insert ).

Could you give us an advise how to handle this ?

### Exception

```
System.Exception: An error occured while resolving ColumnPrimaryKey expression or name. See the inner exception for details.
 ---> System.Exception: Invalid expression.
   at .(Expression this, ParameterExpression )
   at .(LambdaExpression this)
   at Z.BulkOperations.BulkOperation.()
   --- End of inner exception stack trace ---
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkUpdate()
   at .BulkUpdate[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

### Details
interface for all Entities
````
public interface IEntity
  {
    /// <summary>Returns an array of ordered keys for this entity.</summary>
    /// <returns></returns>
    object[] GetKeys();
  }
````
update call
````
await ( await GetDbContextAsync() ).BulkUpdateAsync(
	entityArray,
	options => options.ColumnPrimaryKeyExpression = e => e.GetKeys(),
	GetCancellationToken( cancellationToken )
);
````
Example Entity
````
public class ExampleEntity: IEntity
{
	public Guid UserId { get; set; }
	
	public Guid AccountId { get; set; }
	
	public DateOnly Day { get; set; }

	public override object[] GetKeys()
	{
		return new object[] { UserId, AccountId, Day };
	}
}
````

### Further technical details
- EF version: 6.0.102
- EF Extensions version: 6.13.12
- Database Provider: EFCore

**Comment by puschie286** [comment]
Note: we also tried to use object instead of object[] as key, but same result ( with the exactly same exception & callstack )

**Comment by JonathanMagnan** [comment]
Hello @puschie286 ,

The easiest way would probably using the options `ColumnPrimaryKeyNames` instead which required a list of string.

```csharp
public class ExampleEntity : IEntity
{
	public Guid UserId { get; set; }

	public Guid AccountId { get; set; }

	public DateOnly Day { get; set; }

	public override List<string> GetKeys()
	{
		return new List<string>() { nameof(UserId), nameof(AccountId), nameof(Day) };
	}
}
```

Let me know if that solution could work for you.

Best Regards,

Jon

**Comment by puschie286** [comment]
thanks, works great :)
