### ISSUE TITLE
Null reference exception when running UpdateFromQuery

### ISSUE THREAD

**Issue by david-garcia-garcia** [zzzprojects/EntityFramework-Extensions#476]
### Description
Null reference exception when running UpdateFromQuery

`dcs.CurrentContext.SABENTIS_COMPANY
                    .Where(i => i.cif.Contains(" "))
                    .UpdateFromQuery(i => new SABENTIS_COMPANY() { cif = i.cif.Replace(" ", string.Empty) });`

### Exception

Exception message: {"Object reference not set to an instance of an object."}

Stack trace:
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.(MemberExpression )
   at `1.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at `1.Visit(Expression expression)
   at Z.EntityFramework.Extensions.BatchUpdate.ResolveUpdateFromQueryDictValuesMemberInit(Dictionary`2 dictValues, Type entityType, MemberInitExpression memberInitExpression, String prefix)
   at Z.EntityFramework.Extensions.BatchUpdate.ResolveUpdateFromQueryDictValues[T](Expression`1 updateFactory)
   at Z.EntityFramework.Extensions.BatchUpdate.[](IQueryable`1 , Expression`1 , SchemaEntityType`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression)

### Fiddle or Project (Optional)

https://github.com/david-garcia-garcia/zzzbrokenmerge

Test for this specific issue in the project is:

TestMethod3

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 6.13.12
- Database Provider: MS SQL Server

**Comment by david-garcia-garcia** [comment]
This does not work:

EntityFrameworkManager.BulkOperationBuilder = builder => { builder.UseLegacyBatchOperation = true; };

But if you set the legacy behaviour directly on the operation it does work:

`                db.CORE_LOCALES_SOURCE
                    .Where(i => i.source.Contains(" "))
                    .UpdateFromQuery(
                        i => new CORE_LOCALES_SOURCE() { source = i.source.Replace(" ", string.Empty) },
                        (o) =>
                        {
                            o.UseLegacyBatchOperation = true;
                        });`

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

The v6.13.17 has been released.

The initial issue should now be fixed. My developer also fixed the `BulkOperationBuilder` which was not used to check if the `UseLegacyBatchOperation` value.

Let me know if everything works as expected.

Best Regards,

Jon
