### ISSUE TITLE
ORA-03113 with Devart and BulkInsert

### ISSUE THREAD

**Issue by andro44** [zzzprojects/EntityFramework-Extensions#48]
Hi,

I'm getting an ORA-03113: end-of-file on communication channel exception when using BulkInsert. Do you have any ideas how to fix this error? I was assured by the DBA that the Oracle DB server is working properly, and that the problem seems to be in our app.

``` 
Stack trace: ORA-03113: end-of-file on communication channel
   at Devart.Data.Oracle.cq.a(Byte[] A_0, Int32 A_1, Int32 A_2)
   at Devart.Data.Oracle.cq.a(Byte& A_0)
   at Devart.Data.Oracle.ar.a(Byte[] A_0, Int32 A_1, Int32 A_2)
   at Devart.Data.Oracle.ar.g()
   at Devart.Data.Oracle.bm.a()
   at Devart.Data.Oracle.e.a(bm A_0, Int32 A_1)
   at Devart.Data.Oracle.e.a(Int32 A_0, s A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.OracleCommand.ExecuteNonQuery()
   at Devart.Data.Oracle.OracleCommand.a(Int32 A_0, Boolean A_1, Int64[]& A_2)

ORA-03113: end-of-file on communication channel
ORA-03113: end-of-file on communication channel
   at Devart.Data.Oracle.OracleCommand.a(Int32 A_0, Boolean A_1, Int64[]& A_2)
   at Devart.Data.Oracle.OracleCommand.ExecuteArray(Int32 iters)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ..(DbCommand , BulkOperation , Int32 )
   at ..(ExecuteAction , DbCommand )
   at Z.BulkOperations.DbActionExecutor.(List`1 )
   at Z.BulkOperations.OracleArrayProvider.(List`1 )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , List`1 , Boolean , List`1 , Type , String )
   at Z.EntityFramework.Extensions.InternalBulkOperationManager..(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Z.EntityFramework.Extensions.InternalBulkOperationManager.[](DbContext , BulkOperation`1 , IEnumerable`1 , List`1 )
   at Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
```

I've found a similar problem on devart's support forum (http://forums.devart.com/viewtopic.php?f=1&t=15912&hilit=03113) and they suggested that it was a timeout error. 

The following describes how we use the BulkInsert method.
`context.BulkInsert(collectionOfObjects);`

I've also found a BatchTimeout setting in your library but I haven't found any docs stating, what the input value should be (ms, s, min?).

Any help would be greatly appreciated.
Regards, A

**Comment by JonathanMagnan** [comment]
Hello @andro44 ,

Looking at your information, there is good chance that a timeout occurred.

The value is in second.

Here is an example how to set it:

```csharp
context.BulkInsert(list, operation =>
{
   operation.BatchTimeout = 180;
});
```

Let me know if that's working by increasing the timeout.

Best Regards,

Jonathan

**Comment by andro44** [comment]
What is the default value?

**Comment by JonathanMagnan** [comment]
Hello @andro44 ,

- If the `Context.Database.CommandTimeout` has no value, the default timeout is the default timeout of a the DbCommand depending on the provider
- If the `Context.Database.CommandTimeout` has a value, the default timeout is the Max between 120s and the CommandTimeout.

Best Regards,

Jonathan

**Comment by andro44** [comment]
Changing the BatchTimeout fixed my problem, thank you.

Regards, A

**Comment by andro44** [comment]
Well this is ackward 😞 It didn't solve my problem...

I'm still getting 03113 but I got a lot more info this time around. Below is a screenshot from Oracle's Enterprise Manager:

![image](https://user-images.githubusercontent.com/2691499/29522135-874ad600-8688-11e7-8c44-288f694f80eb.png)

You can see at the end that it got stuck on "SQL*net more data from client". As far as I understand it is telling me that it opened the cursor to do the bulk insert but failed to send the actual data, so it got a timeout after a period of inactivity. Any ideas?

**Comment by andro44** [comment]
Any news on this matter?

Regards, A

**Comment by JonathanMagnan** [comment]
Hello @andro44 ,

Yes, we have made some research but it's currently hard to find out the real problem.

I may be wrong, but I believe `SQL*Net more data from client` is the wait time outside of the database waiting for the IO to read data from the disk.

How many rows do you try to insert at once? How many columns each row have?

Could you try again by reducing the Batch Size to something like 500 or 1000? The default batch size is 10,000 so perhaps this number is too high for your scenario.

As said, unfortunately for us, Oracle has default behavior store data on disk prior being inserted. Reading from the disk is what's the most costly in this operation.

If you can try, please give me an update if that helped or not.

Best Regards,

Jonathan

**Comment by andro44** [comment]
Hi,

it appears we've fixed the problem. It seems that there was a problem with the amount of memory available on the server. Ever since we added extra we stopped getting this error. 

I have another question though: how can I get additional error details when I get an ORA-24381: error(s) in array DML?

```Something went wrong. Stack trace: ORA-24381: error(s) in array DML
   at Devart.Data.Oracle.b8.d()
   at Devart.Data.Oracle.bm.e()
   at Devart.Data.Oracle.bm.a()
   at Devart.Data.Oracle.e.a(bm A_0, Int32 A_1)
   at Devart.Data.Oracle.e.a(Int32 A_0, s A_1)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.OracleCommand.ExecuteNonQuery()
   at Devart.Data.Oracle.OracleCommand.a(Int32 A_0, Boolean A_1, Int64[]& A_2)

ORA-24381: error(s) in array DML
ORA-12592: TNS:bad packet

ORA-03106: fatal two-task communication protocol error

   at Devart.Data.Oracle.OracleCommand.a(Int32 A_0, Boolean A_1, Int64[]& A_2)
   at Devart.Data.Oracle.OracleCommand.ExecuteArray(Int32 iters)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ..(DbCommand , BulkOperation , Int32 )
   at ..(ExecuteAction , DbCommand )
   at Z.BulkOperations.DbActionExecutor.(List`1 )
   at Z.BulkOperations.OracleArrayProvider.(List`1 )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   at Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , List`1 , Boolean , List`1 , Type , String )
   at Z.EntityFramework.Extensions.InternalBulkOperationManager..(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Z.EntityFramework.Extensions.InternalBulkOperationManager.[](DbContext , BulkOperation`1 , IEnumerable`1 , List`1 )
   at Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)```

**Comment by JonathanMagnan** [comment]
Hello @andro44 ,

That's great ;) I hope that will be enough to never seen this error again.

About the error, you get the same error as our library. Oracle is not very good to show an error message to let us find what has happened really.

Our knowledge on Oracle is very limited, so we are not aware if there is a way to get more information about an error if one exists.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: @andro44  have confirmed by mail that reducing the Batch Size have fixed the issue.

Feel free to reopen if you find out you still have it.

Best Regards,

Jonathan
