### ISSUE TITLE
NoTracking doesn't work on BulkMerge

### ISSUE THREAD

**Issue by hoanglan11037** [zzzprojects/EntityFramework-Extensions#495]
### Description
I'm using BulkMerge to insert/update a list of records when multiple entities have the same key and value and it throws this exception.

I tried using UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking) and ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking but it doesn't seem to work.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

Exception message:
**The instance of entity type 'x' cannot be tracked because another instance with the same key value for {'key'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.**

Stack trace:
   **at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)**

### Fiddle or Project (Optional)
If you are able,

### Further technical details
- EF version: EF core 6.21.61
- EF Extensions version: 6.14.2
- Database Provider: Oracle

Do you have any ideas ?

**Comment by JonathanMagnan** [comment]
Hello @hoanglan11037 ,

Could you try the latest v6.14.3?

We made a lot of improvements on this latest version related to shadow value and change tracking. My developer believes that it might already be fixed on this latest version.

If you keep having the issue, do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. That will surely help my developer as he is currently no idea how to reproduce it especially with all the changes/test he recently did for the latest version.

Best Regards,

Jon

**Comment by hoanglan11037** [comment]
Hi @JonathanMagnan 

I found my problem at the step of declaring the datetime property in the type configuration

**builder.Property<DateTime?>("LastUpdateTime").HasColumnName("ALASTUPDATETIME").HasDefaultValueSql("SYSTIMESTAMP");**

I realized this when creating a runnable project with the above issue

You saved me this time
Thank you so much

LanHN
