### ISSUE TITLE
TemporaryTableUseSameName=true leads to exceptions in partial updates

### ISSUE THREAD

**Issue by sawirth** [zzzprojects/EntityFramework-Extensions#503]
### Description
Updating different properties from multiple entities of the same type generates faulty SQL when calling BulkSaveChanges() with TemporaryTableUseSameName set to true.

### Exception
```
Exception message: There is already an object named '#ZZZ_Customer' in the database.
Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 1853
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs:line 611
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs:line 1327
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs:line 2550
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 3233
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 1546
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery() in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs:line 1090
   at Z.BulkOperations.Internal.Data.SqlClient.SqlCommandSet.Execute()
   at .(DbConnection , DbTransaction ,  , List`1 )
   at .(DbConnection , DbTransaction , List`1 )
   at .(DbContext this, List`1 , List`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 , DbContext )
   at DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 options)
   at DbContextExtensions..()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkSaveChangesAsync(DbContext this, Action`1 options, CancellationToken cancellationToken)
   at Playground.Program.Main(String[] args)
   at Playground.Program.<Main>(String[] args)
ClientConnectionId:49f8266b-01c7-4295-87d0-754ccc0538ba
Error Number:2714,State:1,Class:16
Command terminated by signal 6
```

### Fiddle
https://dotnetfiddle.net/SdtP72
For some reason you have to run a second time to see the exception, no idea why. Doesn't happen if I try it locally with my own database.

It creates the following SQL command which is not correct:
```sql
CREATE TABLE #ZZZ_Customer ( [CustomerId] [sys].[int] NULL, [Name] varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, ZZZ_Index [INT] NOT NULL )
      
CREATE CLUSTERED INDEX [INDEX_#ZZZ_Customer] ON #ZZZ_Customer (ZZZ_Index ASC);
CREATE TABLE #ZZZ_Customer ( [CustomerId] [sys].[int] NULL, [IsActive] [sys].[bit] NULL, ZZZ_Index [INT] NOT NULL )
      
CREATE CLUSTERED INDEX [INDEX_#ZZZ_Customer] ON #ZZZ_Customer (ZZZ_Index ASC);
```

### Further technical details
- EF core version: 6.0.8
- EF core Extensions version: 6.14.4
- Database Provider: SQL Server

**Comment by sawirth** [comment]
If I disable TemporaryTableUseSameName then the queries are always different which leads to a lot of query plan compiling (afaik, I am not an SQL Server expert). It also avoids analyzing which queries are called the most and take the most time when viewing them in Datadog because they don't get aggregated.

**Comment by JonathanMagnan** [comment]
In this case, you really want to disable the batching.

The plan is probably different from one query to another as they look different (if batching is enabled, they can be combined with any other query that come next).

So I recommend you using the option `Z.EntityFramework.Extensions.EntityFrameworkManager.PreserveCommandOrder = true;`

I will let you know when the option with the new name will come out, so you will be able to choose if you want to keep using this name or the new options name we added.

Best Regards,

Jon

**Comment by sawirth** [comment]
It works with disabling batching, thx for your help

**Comment by JonathanMagnan** [comment]
Just to update the recommended answer,

A new option has been added to be more specific about this issue: `DisableBulkCommandBatch`

```csharp
Z.EntityFramework.Extensions.EntityFrameworkManager.DisableBulkCommandBatch= true;
```

By setting this option to `true`, the command will no longer combine together to fix this issue
