### ISSUE TITLE
InvalidProgramException when using Z.EntityFramework.Extensions.EFCore library in Android and IOS NET Maui Project

### ISSUE THREAD

**Issue by hosamyousof** [zzzprojects/EntityFramework-Extensions#508]
### Description
We are using Z.EntityFramework.Extensions.EFCore in a NET Maui project but we faced an issue in using batch extensions. They are working fine in windows but it throws an System.InvalidProgramException when run on Android.

### Exception
System.InvalidProgramException

Exception message:
Stack trace:
   at BatchDeleteExtensions.`1[[POS.Domain.Model.ReportTemplate, POS.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].()
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at POS.Logic.Services.Sync.ManageSync.startDownloadReportTemplates(Boolean IsFreshData) in D:\TFS Projects\OXO.Maui.POS\POS.Logic\Services\Sync\ManageSyncBaseDataService.cs:line 1584
   at POS.Logic.Services.Sync.ManageSync.DownloadBaseData(Boolean IsFreshData) in D:\TFS Projects\OXO.Maui.POS\POS.Logic\Services\Sync\ManageSyncBaseDataService.cs:line 113

![image](https://user-images.githubusercontent.com/16549201/194763009-e2a64adb-e885-46a0-bae9-f05793c3b673.png)

### Further technical details
- NET Maui: net6.0
- EF version: Microsoft.EntityFrameworkCore v6.0.9
- EF Extensions version: Z.EntityFramework.Extensions.EFCore 6.15.1
- Database Provider: Sqlite

**Comment by JonathanMagnan** [comment]
Hello @hosamyousof ,

Do you have an error if you are using non async method? Or only when using async method?

Best Regards,

Jon

**Comment by hosamyousof** [comment]
Hello @JonathanMagnan 

The same error is thrown when using non async method.

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @hosamyousof , 

Since our last conversation, we haven't heard from you. 

As mentioned, in my previous message; Could you provide the stack trace and exactly the error message when using non-async method?

Looking forward to hearing from you. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you need more information. 

Best regards, 

Jon
