### ISSUE TITLE
BulkUpdate fails when using TPH and unique index

### ISSUE THREAD

**Issue by david-wimmer** [zzzprojects/EntityFramework-Extensions#513]
### Description
When using `BulkUpdate` to update entities with TPH inheritance and unique index an exception is thrown:

### Exception
```
Exception message:
'Cannot insert duplicate key row in object 'dbo.BaseEntry' with unique index 'IX_BaseEntry_Position'. The duplicate key value is (4).
The statement has been terminated.'

Stack trace:
at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at .(DbCommand , BulkOperation , Int32 )
at .( , DbCommand )
at .Execute(List`1 actions)
at Z.BulkOperations.BulkOperation.Execute()
at .BulkUpdate[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
at .BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options)
at Program.<Main>$(String[] args) in C:\dev\git\z-ef-extensions-issues\bulkupdate-tph\Program.cs:line 45
```

### Project

There is a TPH inheritance structure with abstract base class `BaseEntry` which has an unique index on column `Position` and two child classes `ChildEntryA` and `ChildEntryB`.
Loading all the entities, incrementing the positions and calling `BulkUpdate` throws that exception.

```cs
// Modify positions
var entries = context.BaseEntries.ToList();
entries.ForEach(b => b.Position++);

// Bulk update fails
context.BulkUpdate(entries);
```

The problem is that `BulkUpdate` executes a separate update statement for each child class, so there is a unique index violation.
This already worked in EF Core 2.2.6 with EF Extensions 2.16.0, because it was executed in a single statement.

```sql
exec sp_executesql N'UPDATE DestinationTable
SET     [Position] = StagingTable.[Position], [Type] = StagingTable.[Type]
FROM [BaseEntry] AS DestinationTable 
INNER JOIN (SELECT TOP 100 PERCENT * FROM (SELECT @0_0 AS [Id], @0_1 AS [Position], @0_2 AS [Type], @0_3 AS ZZZ_Index
UNION ALL SELECT @1_0 AS [Id], @1_1 AS [Position], @1_2 AS [Type], @1_3 AS ZZZ_Index
UNION ALL SELECT @2_0 AS [Id], @2_1 AS [Position], @2_2 AS [Type], @2_3 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index) AS StagingTable ON DestinationTable.[Id] = StagingTable.[Id]  
;',N'@0_0 int,@0_1 int,@0_2 nvarchar(1),@0_3 int,@1_0 int,@1_1 int,@1_2 nvarchar(1),@1_3 int,@2_0 int,@2_1 int,@2_2 nvarchar(1),@2_3 int',@0_0=1,@0_1=2,@0_2=N'A',@0_3=0,@1_0=2,@1_1=3,@1_2=N'A',@1_3=1,@2_0=3,@2_1=4,@2_2=N'A',@2_3=2
```

<details><summary>Entire Project</summary>
<p>

```cs
using Microsoft.EntityFrameworkCore;

using (var context = new TestDbContext())
{
    // Create test data
    context.Database.EnsureDeleted();
    context.Database.EnsureCreated();

    Enumerable.Range(1, 3).ToList().ForEach(p =>
    {
        var childEntryA = new ChildEntryA
        {
            Position = p
        };
        context.Add(childEntryA);
    });

    Enumerable.Range(4, 3).ToList().ForEach(p =>
    {
        var childEntryB = new ChildEntryB
        {
            Position = p
        };
        context.Add(childEntryB);
    });

    context.SaveChanges();
}

using (var context = new TestDbContext())
{
    // Modify positions
    var entries = context.BaseEntries.ToList();
    entries.ForEach(b => b.Position++);

    // Bulk update fails
    context.BulkUpdate(entries);
}

public class TestDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseSqlServer("Server=localhost;Database=bulkupdate-tph;Integrated Security=True;Encrypt=False");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<BaseEntry>(b =>
        {
            b.ToTable(nameof(BaseEntry));
            b.HasDiscriminator<char>("Type")
                .HasValue<ChildEntryA>('A')
                .HasValue<ChildEntryB>('B');
            b.HasIndex(b => b.Position).IsUnique();
        });
    }

    public DbSet<BaseEntry> BaseEntries { get; set; }
}

public abstract class BaseEntry
{
    public int Id { get; set; }
    public int Position { get; set; }
}

public class ChildEntryA : BaseEntry
{ }

public class ChildEntryB : BaseEntry
{ }
```
</p>
</details>

### Further technical details
- EF version: 7.0.0-rc.2.22472.11
- EF Extensions version: 7.0.0-rc.2.22472.11-03
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by JonathanMagnan** [comment]
Hello @david-wimmer ,

Thank you for reporting, my developer will look at it. I believe we have enough information with your Entire Project section

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @david-wimmer ,

At this moment, we have no solution for this issue as it can happen either:

- On different batches (We could reproduce a similar issue even in EF Core 2)
- On TPH (As we insert all `ChildEntityA`, then all `ChildEntryB` or vice-versa)

In this case, I recommend using `SaveChanges` instead as there is currently no options to skip the discriminator at this moment.
