### ISSUE TITLE
ColumnPrimaryKeyNames works from Context but not from BulkOperation

### ISSUE THREAD

**Issue by lordpalf** [zzzprojects/EntityFramework-Extensions#519]
### Description
ColumnPrimaryKeyNames doesn't work as expected on BulkOperation

First test using Context works, the result is one updated record and one inserted
```
using(var ctx = new TestContext()) {

                var org_items = new List<Item> {
                    new Item { Id = Guid.NewGuid(), Name = "test1", Count = 0  }
                };

                ctx.BulkMerge(org_items, options => {
                    options.ColumnPrimaryKeyNames = new List<string> { "Name" };
                });

                var upd_items = new List<Item> {
                    new Item { Id = Guid.NewGuid(), Name = "test1", Count = 1  },
                    new Item { Id = Guid.NewGuid(), Name = "test2", Count = 0  }
                };

                ctx.BulkMerge(upd_items, options => {
                    options.ColumnPrimaryKeyExpression = c => new { c.Name };
                });
            }
```
Second test using BulkOperation fails with exception. Removing the ColumnPrimaryKeyNames options will make the code run.
Note: TestReader is and implementation of IDataReader see, github below.
```
 using(var cnn = new SqlConnection(TestContext.ConnectionString)) {
                cnn.Open();
                using(var bulk = new BulkOperation(cnn)) {
                    var org_reader = new TestReader(new List<Item> {
                        new Item { Id = Guid.NewGuid(), Name = "test3", Count = 0 }
                    });
                    bulk.DestinationTableName = "Items";
                    bulk.ColumnPrimaryKeyNames = new List<string> { "Name" };
                    bulk.BulkMerge(org_reader);
                }

                using(var bulk = new BulkOperation(cnn)) {
                    var org_reader = new TestReader(new List<Item> {
                        new Item { Id = Guid.NewGuid(), Name = "test3", Count = 1 },
                        new Item { Id = Guid.NewGuid(), Name = "test4", Count = 0 },
                    });
                    bulk.DestinationTableName = "Items";
                    bulk.ColumnPrimaryKeyNames = new List<string> { "Name"  };
                    bulk.BulkMerge(org_reader);
                }
            }
```

### Exception
```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Cannot insert the value NULL into column 'Id', table 'BulkTest.dbo.Items'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at .(DbCommand , BulkOperation , Int32 )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at BulkTest.Program.Test2() in C:\Users\Luuk.Mettes\source\repos\BulkTest\BulkTest\Program.cs:line 33
   at BulkTest.Program.Main(String[] args) in C:\Users\Luuk.Mettes\source\repos\BulkTest\BulkTest\Program.cs:line 20

  This exception was originally thrown at this call stack:
    [External Code]
    BulkTest.Program.Test2() in Program.cs
    BulkTest.Program.Main(string[]) in Program.cs
```

### Fiddle or Project (Optional)
Full project example using SqlServer
https://github.com/lordpalf/BulkTest

**Comment by JonathanMagnan** [comment]
Hello @lordpalf ,

When you use the `BulkOperation` class and specify some mapping (such as the primary key), you need to specify the whole mapping as our library doesn't assume you want every column (this is not coming from Entity Framework, so we don't know exactly your model).

So you also need to specify your `ColumnMappings` or `ColumnInputNames` such as the missing column `Id`.

Let me know if that explains correctly the cause and solution of this issue.

Best Regards,

Jon

**Comment by lordpalf** [comment]
Thanks a lot for the fast response!
Adding a ColumnInputNames makes it work.
