### ISSUE TITLE
Crash on NET/EF 7

### ISSUE THREAD

**Issue by DjKlazaplaza** [zzzprojects/EntityFramework-Extensions#520]
I get the following exception when trying to do ImportAsync after updating to NET/EF 7

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnName(Microsoft.EntityFrameworkCore.Metadata.IProperty)'.
   at Npgsql.Bulk.NpgsqlHelper.<>c.<GetMetadata>b__1_1(IProperty x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Npgsql.Bulk.NpgsqlHelper.GetMetadata(DbContext context, Type type)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetMappingInfo(Type type, String tableName)
   at Npgsql.Bulk.NpgsqlBulkUploader.CreateEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.<GetEntityInfo>b__54_0[T](String x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.ImportAsync[T](IEnumerable`1 entities)
   at migrator.Program.MigrateUsers(IDbContextFactory`1 factory, IDbContextFactory`1 oldFactory, ILogger logger) in C:\src\web-3.0\services\migrator\Program.cs:line 578
   at migrator.Program.MigrateUsers(IDbContextFactory`1 factory, IDbContextFactory`1 oldFactory, ILogger logger) in C:\src\web-3.0\services\migrator\Program.cs:line 584
   at migrator.Program.MigrateUsers(IDbContextFactory`1 factory, IDbContextFactory`1 oldFactory, ILogger logger) in C:\src\web-3.0\services\migrator\Program.cs:line 584
   at migrator.Program.Main(String[] args) in C:\src\web-3.0\services\migrator\Program.cs:line 103
   at migrator.Program.<Main>(String[] args)
```

### User definition in dbcontext
```
modelBuilder.Entity<User>().HasKey(n => n.Id);
			modelBuilder.Entity<User>().Property(n => n.Id).UseIdentityByDefaultColumn();
			modelBuilder.Entity<User>().Property(n => n.Registered).HasDefaultValue(DateTime.UtcNow);
			modelBuilder.Entity<User>().HasIndex(n => n.Email).IsUnique();
			modelBuilder.Entity<User>().HasMany(n => n.RefreshTokens).WithOne(n => n.User)
				.HasForeignKey(n => n.UserId).OnDelete(DeleteBehavior.Cascade);
			modelBuilder.Entity<User>().HasMany(n => n.Installs).WithOne(n => n.User)
				.HasForeignKey(n => n.UserId);
			modelBuilder.Entity<User>().HasMany(n => n.Sessions).WithOne(n => n.User)
				.HasForeignKey(n => n.UserId);
```

### Further technical details
- EF version: 7.0.0
- EF Extensions version: 7.17.0
- Database Provider: Postgres (Npgsql.EntityFrameworkCore.PostgreSQL 7.0.0)

**Comment by JonathanMagnan** [comment]
Hello @DjKlazaplaza ,

We do not have an `ImportAsync` method.

So at this moment, this issue doesn't look to be related to our library.

Best Regards,

Jon

**Comment by DjKlazaplaza** [comment]
Very sorry. Got fooled by own project files. Please close this issue.
