### ISSUE TITLE
Setting varbinary fields to NULL in an UPDATE query throws exception

### ISSUE THREAD

**Issue by tiesont** [zzzprojects/EntityFramework-Extensions#525]
### Description

When attempting to set a `varbinary` field to NULL, an exception is thrown. The stacktrace seems to indicate that it's happening because a `NVARCHAR` value is being set to the field rather than a `VARBINARY` value.

This seems to the same error reported in #436. I'm not seeing the suggested option in that issue, probably because I'm using EF Core 6, not EF6.

I've attempted to replace `UpdateFromQuery` with `Update`, from the Z.EntityFramework.Plus.EfCore package, but same error occurs.

### Exception

```
Exception message:
Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.

Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.(DbCommand , Nullable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at ClassNameA.MyMethod(MyArgType[] args) in C:\Path\To\My\Class\ClassNameA.cs:line 176
   at ClassNameB.<MyMethod>d__9.MoveNext() in C:\Path\To\My\Class\ClassNameB.cs:line 410
```

### Further technical details
- EF version: EF Core 6
- EF Extensions version: 6.18.4
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @tiesont ,

Thank you for reporting, my developer will look at it very soon.

Best Regards,

Jon

**Comment by tiesont** [comment]
> Hello @tiesont ,
> 
> Thank you for reporting, my developer will look at it very soon.
> 
> Best Regards,
> 
> Jon

I was able to get my method to work using the `BulkSaveChanges()` method, so this isn't an urgent issue. I would _prefer_ to be able to use the UpdateFromQuery (or Update) methods, though, to avoid having to query for the records first.

**Comment by JonathanMagnan** [comment]
Hello @tiesont ,

The v7.18.5 has been released (6.18.5 for EF Core 6)

The issue should be fixed in this version.

If you have the chance to test it, could you confirm that everything is working?

Best Regards,

Jon

**Comment by tiesont** [comment]
@JonathanMagnan Awesome! I'll update today and let you know what I see.

**Comment by tiesont** [comment]
@JonathanMagnan Just ran a test with the code that was failing before. No errors, database updated correctly. Seems fixed. Thanks!
