### ISSUE TITLE
UpdateFromQuery Exception - Npgsql.PostgresException: '42703: column b.id does not exist

### ISSUE THREAD

**Issue by viniciusverasdossantos** [zzzprojects/EntityFramework-Extensions#531]
### Description

expression:
new Produto { IdUnidadeDeEstocagem = (Guid)value }

Method:
Produtos.UpdateFromQuery(expression);

### Exception

Exception message:
Npgsql.PostgresException: '42703: column b.id does not exist
Stack trace:
   at Npgsql.Internal.NpgsqlConnector.<<ReadMessage>g__ReadMessageLong|233_0>d.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__124.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__124.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__112.MoveNext()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Extensions.BatchUpdate.<>c.(DbCommand , Nullable`1 )
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateFactory)
   at Vvs.CPlusAnywhere.Aplicacao.Produtos.Produtos.ProdutoAppService.AtualizarCampo(CampoASerAtualizadoEnum campo, Guid[] arrIdProduto, Object value) in C:\repos\CPlus5\Aplicacao\Produtos\Produtos\ProdutoAppService.cs:line 5783
   at Vvs.CPlusAnywhere.Aplicacao.Produtos.Produtos.ProdutoAppService.AlterarUnidadeDeEstocagem(Guid[] idProduto, Guid idUnidade) in C:\repos\CPlus5\Aplicacao\Produtos\Produtos\ProdutoAppService.cs:line 5863
   at Castle.Proxies.Invocations.IProdutoAppService_AlterarUnidadeDeEstocagem.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Vvs.Seedwork.Events.ImmediateConsistency.Scopes.ImmediateConsistencyScopeInterceptor.<>c__DisplayClass0_0.<Intercept>b__1()
   at Vvs.Seedwork.Events.ImmediateConsistency.Scopes.ImmediateConsistencyScopeInterceptor.<Intercept>g__TransactionAbortedExceptionHandle|0_0(Action action)

### Further technical details
EF version: 7.0.5
EF Extensions version: 7.21.1
Database Provider: Npgsql 7.0.2 Npgsql.EntityFrameworkCore.PostgreSQL 7.0.3

**Comment by JonathanMagnan** [comment]
Hello @viniciusverasdossantos ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

Unfortunately, I don't think my developer currently have enough issue to reproduce it

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @viniciusverasdossantos 

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, could you provide a runnable project?

Let me know if you have any questions. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Let me know if you need more information. 

Best regards, 

Jon
