### ISSUE TITLE
HasColumnName throws Exception: Missing Column 

### ISSUE THREAD

**Issue by virzak** [zzzprojects/EntityFramework-Extensions#532]
### Description
HasColumnName on entities throws exception when HasColumnName is used on either owned entity or main entity.

This is a bit urgent :(

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.Exception
  HResult=0x80131500
  Message=An error occured while resolving mapping by expression. See the inner exception for details.
  Source=Z.EntityFramework.Extensions.EFCore
  StackTrace:
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkUpdate()
   at .BulkUpdate[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at Program.<Main>$(String[] args) in Q:\Code\Sandbox\BulkUpdateOwned\BulkUpdateOwned\Program.cs:line 19

  This exception was originally thrown at this call stack:
    Z.BulkOperations.BulkOperation.(string, bool, bool, bool)
    Z.BulkOperations.BulkOperation.()

Inner Exception 1:
Exception: Missing Column : Name.MiddleName
On entity : Customer
On Table : [Customers]
```

### Fiddle or Project (Optional)

https://dotnetfiddle.net/718w6F

### Further technical details
- EF version: 7, 8
- EF Extensions version: 7, 8
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Could this solution work for you? https://dotnetfiddle.net/NS6kem

Best Regards,

Jon

**Comment by virzak** [comment]
@JonathanMagnan thanks, this solution works.
