### ISSUE TITLE
Cannot validate license in code if not using Entity Framework.

### ISSUE THREAD

**Issue by rkreiseloakwood** [zzzprojects/EntityFramework-Extensions#534]
### Description
My project does not use Entity Framework. It uses Dapper to access a Sql Server database.
My client purchased a SQL License for Dapper Plus.
I use this product in an Azure Function and I put the json settings in my local.settings.json file.
I then attempted to validate that I was using the licensed copy instead of the free one by adding the sample code into my program.cs file.
Z.EntityFramework.Extensions.LicenseManager.AddLicense("my license name", "my license key");
        if (!Z.EntityFramework.Extensions.LicenseManager.ValidateLicense(out string licenseErrorMessage))
        {
            _logger.LogCritical(licenseErrorMessage);
            throw new Exception(licenseErrorMessage);
        }
I get the following exception.
Is there a different extension package that works for Dapper?

### Exception
[2023-05-30T18:43:54.371Z] Unhandled exception. System.Exception: **Your current license is not compatible with this feature.**
[2023-05-30T18:43:54.373Z] You currently have the following license:
[2023-05-30T18:43:54.374Z] Dapper Plus - SQL Server
[2023-05-30T18:43:54.376Z] The following license is required to perform such operation (contact us info@zzzprojects.com for more information):
[2023-05-30T18:43:54.377Z] .NET EF Extensions - SQL Server
[2023-05-30T18:43:54.378Z]    at HealthFundSolutions.HFSRevOneOutboundFunction.Program.Main() in C:\HFS\DataIngestionAF\HFSDataIngestionFunction\Program.cs:line 39
[2023-05-30T18:43:54.379Z]    at HealthFundSolutions.HFSRevOneOutboundFunction.Program.<Main>()
[2023-05-30T18:43:54.445Z] Host lock lease acquired by instance ID '0000000000000000000000001B688606'.

**Comment by rkreiseloakwood** [comment]
Okay. This was my mistake. There IS a different process/method to validate when using Dapper. It is found here:

https://dapper-plus.net/licensing
