### ISSUE TITLE
BulkInsert fail for partition table with text[] column in postgreSQL

### ISSUE THREAD

**Issue by ImKoala** [zzzprojects/EntityFramework-Extensions#544]
### Description
If the target table is a partition table, and has text[] type column, Bulk operations and BulkSaveChanges will fail.
Current workaround I found is to overwrite the destination table name to the child table.

### Exception

```
Unhandled exception. System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details.
 ---> System.Exception: Oops! Unsupported types : ARRAY _text
 ---> System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ToBoolean(Object value)
   at ?.?(? ?, String[] ?)
   --- End of inner exception stack trace ---
   at ?.?(? ?, Exception ?, List`1 ?, Table ?, String[] ?)
   at ?.?(? ?, String[] ?)
   at ?.?(Boolean ?, String[] ?)
   at ?.?()
   at Z.BulkOperations.BulkOperation.?()
   --- End of inner exception stack trace ---
   at Z.BulkOperations.BulkOperation.?()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at ?.BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at ?.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.?`1.?()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in D:\repos\Personal\TestJson\TestJson\TestEFE\Program.cs:line 30
   at Program.<Main>(String[] args)


```

### Fiddle or Project (Optional)
Sample table scripts
```
create table public.test_positions
(
    source_timestamp timestamp not null,
    pms_key          text      not null,
    is_eod           boolean   not null,
    position_date    date      not null,
    tags             text[],
    constraint pk_test_positions
        primary key (position_date, source_timestamp, pms_key, is_eod)
) partition by RANGE (position_date);

create table public.test_positions_p2023_09_21
    partition of public.test_positions
        FOR VALUES FROM ('2023-09-21') TO ('2023-09-22');
```
Sample Code in a dotnet 6 Console project
Required Nuget Packages:
```
Microsoft.EntityFrameworkCore 7.0.11
Npgsql.EntityFrameworkCore.PostgreSQL 7.0.11
Z.EntityFramework.Extensions.EFCore 7.100.0.1
```
```
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

var connectionString = Environment.GetEnvironmentVariable("DB_URL");

var services = new ServiceCollection();
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
services.AddDbContext<TestContext>(options =>
{
    options.UseNpgsql(connectionString);
    options.LogTo(Console.WriteLine).EnableDetailedErrors();
});

var serviceProvider = services.BuildServiceProvider();
var dbContext = serviceProvider.GetRequiredService<TestContext>();


var testPos = new TestPosition()
{
    PmsKey = "test1",
    SourceTimestamp = DateTime.UtcNow,
    PositionDate = new DateTime(2023,9,21, 0,0,0,DateTimeKind.Utc),
    IsEod = false,
    Tags = new []{"test1"}
};
await dbContext.TestPositions.BulkInsertAsync(new[] { testPos });
//await dbContext.TestPositions.BulkInsertAsync(new[] { testPos }, opt=>opt.DestinationTableName="test_positions_p2023_09_21");

public class TestPosition
{
    [Column(TypeName = "date")] 
    public DateTime PositionDate { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime SourceTimestamp { get; set; }

    public string PmsKey { get; set; }
    public bool IsEod { get; set; }
    public string[] Tags { get; set; }
}

public partial class TestContext : DbContext
{
    public TestContext() {}

    public TestContext(DbContextOptions<TestContext> options): base(options)    {    }

    public virtual DbSet<TestPosition> TestPositions { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TestPosition>(entity =>
        {
            entity.ToTable("test_positions");
            entity.Property(e => e.PositionDate).HasColumnName("position_date");
            entity.Property(e => e.SourceTimestamp).HasColumnName("source_timestamp");
            entity.Property(e => e.PmsKey).HasColumnName("pms_key");
            entity.Property(e => e.IsEod).HasColumnName("is_eod");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.HasKey(e => new { e.PositionDate, e.SourceTimestamp, e.PmsKey, e.IsEod });
        });
    }
}
```

### Further technical details
- EF version: EF Core 7.0.11
- EF Extensions version: EF Core7.100.0.1
- Database Provider: postgreSQL

**Comment by JonathanMagnan** [comment]
Hello @ImKoala ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @ImKoala ,

We are currently working on this issue.

The code we are currently using to solve the array doesn't work because of the partition. For an unknown reason, the `AllowDBNull` when retrieving the information returns null when we use the `GetSchemaTable` method from the reader with PostgreSQL.

When this kind of issue is hapenning, we tried to find the table information in an alternative way that was still not support array.

**Comment by JonathanMagnan** [comment]
Hello @ImKoala ,

The v7.100.0.3 has been released today.

If you have the chance to try it, let us know if this is now working correctly.

Best Regards,

Jon

**Comment by ImKoala** [comment]
Hello @JonathanMagnan
Thanks a lot, verified the issue is fixed.
