### ISSUE TITLE
Oops! Custom mapping is currently not supported with self-hierarchy at this moment.

### ISSUE THREAD

**Issue by NicoKno** [zzzprojects/EntityFramework-Extensions#545]
### Description
I get the error stated below. All I did was upgrade from version 5.1.21 to Version 7.100.0.2. Everything worked fine for ages. What is the exception even trying to tell me?

```
Exception message:
Oops! Custom mapping is currently not supported with self-hierarchy at this moment.

Stack trace:

System.Exception: Oops! Custom mapping is currently not supported with self-hierarchy at this moment.
   at .[](BulkOperation`1 this, BulkOperationActionType , Boolean , Dictionary`2 , IEntityType , List`1 , HashSet`1 , Dictionary`2 )
   at .[](BulkOperation`1 this, IEntityType , BulkOperationActionType )
   at .[](BulkOperation`1 this, DbContext , IEntityType , IEnumerable`1 , BulkOperationActionType )
   at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .[](DbContext , SavingSelector , List`1 , Action`1 )
   at .[](DbContext ,  , BulkOperationActionType , Action`1 )
   at .BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at CmpDataWriter.DataWriters.TcDataWriterGitDataContainer.Commit() in /builds/corp/smartapplicationsservices/cmp/cmpgate/CmpDataWriter/DataWriters/TcDataWriterGitDataContainer.cs:line 83
   at CmpGateBusinessLogic.BusinessLogic.TcEntityFrameworkWriter`1.Commit() in /builds/corp/smartapplicationsservices/cmp/cmpgate/CmpGateBusinessLogic/BusinessLogic/TcEntityFrameworkWriter.cs:line 54
   at CmpGateBusinessLogic.BusinessLogic.TcGenericWorker`1.TransformAndStore(Device tDevice, IReadOnlyCollection`1 tPostProcessedRecords) in /builds/corp/smartapplicationsservices/cmp/cmpgate/CmpGateBusinessLogic/BusinessLogic/TcGenericWorker.cs:line 51
   at CmpGateBusinessLogic.BusinessLogic.TcParserJob.Run(String tEquipmentNr, IEnumerable`1 tPaths) in /builds/corp/smartapplicationsservices/cmp/cmpgate/CmpGateBusinessLogic/BusinessLogic/TcParserJob.cs:line 61
   at CmpGateBusinessLogic.TcCmpParserRunner.ExecuteAsync(TcRequestStartParser tRequest, PerformContext tContext) in /builds/corp/smartapplicationsservices/cmp/cmpgate/CmpGateBusinessLogic/TcCmpParserRunner.cs:line 35
   at InvokeStub_TcCmpParserRunner.ExecuteAsync(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Further technical details
- EF version: 7.0.0
- EF Extensions version: 7.100.0.2
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @NicoKno ,

I talked with my developer, and you are right. This is a scenario that is currently not yet supported with the new `IncludeGraph` introduced in the v`7.100.0.0`.

Our new `IncludeGraph` greatly improves the performance for `self-hierarchy` but is still incompatible with custom mapping in this case. That's something we will try to support soon.

You can learn more about the new `IncludeGraph` here: https://entityframework-extensions.net/v7-100-0-0-include-graph

## LegacyIncludeGraph

You can use the `LegacyIncludeGraph` option, which should work like the `IncludeGraph` in the v5.1.21.

```csharp
context.BulkInsert(list, options => {
	options.LegacyIncludeGraph = true;
});
```

It will be a lot slower but at least will be compatible with self-hierarchy with custom mapping (at this time, commands were generated by EF Core).

Let me know if that solves your issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @NicoKno ,

I will have a meeting with my employee who worked on this next Monday. So I will provide you soon a more accurate answer about it.

**Comment by NicoKno** [comment]
I implemented LegacyIncludeGraph in my codebase and it works now. Thanks for the heads up.
