### ISSUE TITLE
BulkSynchronizeAsync & an unsupported options when using MySQL provider

### ISSUE THREAD

**Issue by vinaghost** [zzzprojects/EntityFramework-Extensions#547]
### Description
BulkSynchronize is okay with 7.22.6, but today when I updated to 7.100.0.2, it was broken

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Unhandled exception. System.Exception: Oops! You are currently MySQL provider and using `BulkSynchronize` method with an unsupported options (AllowConcurrency, ColumnSynchronizeMatchedAnd, ColumnSynchronizeMatchedAndOneNot, SynchronizeMatchedAndFormula).
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkSynchronize[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
   at .BulkSynchronize[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.BulkSynchronize[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkSynchronizeAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at MapSqlDatabaseUpdate.Service.Implementations.UpdateDatabaseService.ExecutePlayers(ServerDbContext context, List`1 villageRaws) in /home/runner/work/TravianMapSqlAnalytics/TravianMapSqlAnalytics/MapSqlDatabaseUpdate/Service/Implementations/UpdateDatabaseService.cs:line 45
   at MapSqlDatabaseUpdate.Service.Implementations.UpdateDatabaseService.Execute(List`1 villageRaws) in /home/runner/work/TravianMapSqlAnalytics/TravianMapSqlAnalytics/MapSqlDatabaseUpdate/Service/Implementations/UpdateDatabaseService.cs:line 26
   at MapSqlDatabaseUpdate.Service.Implementations.StartUpService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/TravianMapSqlAnalytics/TravianMapSqlAnalytics/MapSqlDatabaseUpdate/Service/Implementations/StartUpService.cs:line 46
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MapSqlDatabaseUpdate.Program.Main(String[] args) in /home/runner/work/TravianMapSqlAnalytics/TravianMapSqlAnalytics/MapSqlDatabaseUpdate/Program.cs:line 14
```

### Fiddle or Project (Optional)
My project is public so you can check it [here](https://github.com/vinaghost/TravianMapSqlAnalytics/blob/c96a6160c1bdad594e08eba788cf5dada99c2f5d/MapSqlDatabaseUpdate/Service/Implementations/UpdateDatabaseService.cs#L45) 

The line causes exception
```c#
await context.BulkSynchronizeAsync(players, options => options.SynchronizeKeepidentity= true);
```

### Further technical details
- EF version: 7.0.11 (Pomelo.EntityFrameworkCore.MySql 7.0.0)
- EF Extensions version: 7.100.0.2
- Database Provider: MySQL

**Comment by JonathanMagnan** [comment]
Hello @vinaghost ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by vinaghost** [comment]
@JonathanMagnan any news ?

**Comment by JonathanMagnan** [comment]
Hello @vinaghost ,

A fix has been merged into our master.

It will be released either tomorrow or next week.

Best Regards,

Jon

**Comment by vinaghost** [comment]
@JonathanMagnan 
sorry for late reply, it works perfectly, thanks
