### ISSUE TITLE
MySql XAER_RMFAIL error with BulkSaveChanges and TransactionScope

### ISSUE THREAD

**Issue by joniles** [zzzprojects/EntityFramework-Extensions#552]
### Description
I have base class set  up for running tests which modify the database. At the completion of each test, changes to the database are rolled back:

```c#
public abstract class DatabaseTest
{
    private TransactionScope _scope;

    [SetUp]
    public void SetUp()
    {
        _scope = new TransactionScope(
            TransactionScopeOption.Required,
            new TransactionOptions { IsolationLevel = IsolationLevel.ReadCommitted }
        );
    }

    [TearDown]
    public void TearDown()
    {
        _scope.Dispose();
    }
}
```

I can then write a test like this:

```c#
public class SomethingTest : DatabaseTest
{
    [Test]
    public void TestSomething()
    {
        using (var context = new DatabaseContext())
        {
            // make some changes

            // now save the changes
            context.SaveChanges();

            // rest of the test
        }
    }
}
```

Any changes the test makes to the database are rolled back on completion.

If I switch to using `context.BulkSaveChanges()` I get the exception shown below. If I remove the use of `TransactionScope` from the base class, `BulkSaveChanges` will work as expected, but the changes my test makes won't have been rolled back.

### Exception
```
MySqlConnector.MySqlException : XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state
Data:
  Server Error Code: 1399
  SqlState: XAE07
Stack trace:
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 344
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 278
   at .(DbCommand , BulkOperation )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at .(DbContext this, List`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 , DbContext )
   at DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 options)
   at DbContextExtensions.BulkSaveChanges(DbContext this)
```

### Further technical details
- EF version: 7.0.12
- EF Extensions version: 7.100.0.4
- Database Provider: Pomelo.EntityFrameworkCore.MySql 7.0.0

**Comment by JonathanMagnan** [comment]
Hello @joniles ,

The 7.101.0.0 has been released today.

The fix for this issue has been included in this release.

Let me know if everything works as expected in the latest version.

Best Regards,

Jon

**Comment by joniles** [comment]
Works perfectly - thank you!
