### ISSUE TITLE
BulkInsert Error after upgrading to Ef Core .Net 8 with latest Extensions

### ISSUE THREAD

**Issue by rabberbock** [zzzprojects/EntityFramework-Extensions#559]
### Description
When trying to insert some of entities using include graph an error is thrown. This worked prior to the upgrade to ,Net 8. We are using Postgres and NpgSQL.

### Exception
[System.Exception: Oops! The distinct count of item to insert doesn't match. Please report this issue to our support team: info@zzzprojects.com , v=8.101.0.0
   at .Create()
   at .Create(DbContext context, EntityTypeZInfo entityTypeInfo, IEqualityComparer`1 dictionaryEqualityComparer, List`1 list, BulkOperationActionType actionType, Boolean isIncludGraph, Boolean isIncludGraphBuilderBulkSaveChanges)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges, Boolean isOptimized)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at Database.Utilities.DatabaseUtilities.InsertProjects(ApplicationContext applicationContext, ILogger logger, Int32 numItems) in C:\Users\tgabb\Repos\Connect\src\Database\Utilities\DatabaseUtilities.cs:line 1577
   at Database.Utilities.DatabaseUtilities.SeedDatabaseIfNeeded(IServiceProvider serviceProvider, ILogger logger, Int32 numItems, Boolean isTestDb) in C:\Users\tgabb\Repos\Connect\src\Database\Utilities\DatabaseUtilities.cs:line 99
   at Database.Utilities.DatabaseUtilities.SeedDatabaseIfNeeded(IServiceProvider serviceProvider, ILogger logger, Int32 numItems, Boolean isTestDb) in C:\Users\tgabb\Repos\Connect\src\Database\Utilities\DatabaseUtilities.cs:line 230
   at Program.<Main>$(String[] args) in C:\Users\tgabb\Repos\Connect\src\Services\Researcher\ResearcherBackend\Program.cs:line 19
   at Program.<Main>(String[] args)

### Fiddle or Project (Optional)
Have not been able to isolate the problem yet using a simple example of BulkInsert. Will add more details when I have, but thought I would post to see if you had any guidance. Thanks!

### Further technical details

- EF version: [EF Core v8.0.0]
- EF Extensions version: [EFE Core v8.101.0]
- Database Server version: [Postgres 14]
- Database Provider version (NuGet): [Npgsql.EntityFrameworkCore.PostgreSQL v8.0.0]

**Comment by JonathanMagnan** [comment]
Hello @rabberbock ,

This issue happens when there is a duplicate (exactly the same instance) of one of your entities in the list such as:

```csharp
var customerA = new Customer();
var customerB = new Customer();

var list = new List<Customer>();
list.Add(customerA);
list.Add(customerA); // added twice
list.Add(customerB);
```

We had some inconsistency before about how this scenario was handled (for example, [BulkInsert](https://entityframework-extensions.net/bulk-insert) was working, but [Include Graph](https://entityframework-extensions.net/include-graph) was throwing an error, so indeed starting from [v7.100.0.0](https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/7.100.0.0), this error start to appear.

Is there a reason on your side that an entity would be a duplicate in your list?

Obviously, to fix it, you can simply use the `Distinct` method, but that's maybe not something you can do:

```csharp
context.BulkInsert(list.Distinct());
```

Best Regards,

Jon

**Comment by rabberbock** [comment]
@JonathanMagnan Thanks for the detailed explanation! That was exactly it and we don't need duplicates in our scenario. So all good to go on this issue.
