### ISSUE TITLE
22P03: incorrect binary data format

### ISSUE THREAD

**Issue by joelnotified** [zzzprojects/EntityFramework-Extensions#56]
I'm using `Z.EntityFramework.Extensions" Version="3.12.27` with Postgresql.

I load 100 entities from the database, and update properties on some of them, then I do a `BulkSaveChangesAsync`. I get the following error:

`22P03: incorrect binary data format`

Stacktrace: 
```
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadExpecting>d__154`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlBinaryImporter.Close()
   at ..(Int32 , DbTransaction , ExecuteAction , PostgreSqlActionExecutor , DbConnection )
   at Z.BulkOperations.PostgreSqlActionExecutor.(ExecuteAction )
   at Z.BulkOperations.PostgreSqlActionExecutor.(ExecuteAction )
   at Z.BulkOperations.DbActionExecutor.(List`1 )
   at Z.BulkOperations.PostgreSqlProvider.(List`1 )
   at ..(BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkUpdate()
   at Z.EntityFramework.Extensions.SqlServerBulkSaveChanges.(List`1 , Object , Dictionary`2 )
   at Z.EntityFramework.Extensions.SqlServerBulkSaveChanges.()
```

This is the `data` field of the exception (if that helps):
```
-		Data	Count = 8	System.Collections.IDictionary {System.Collections.Generic.Dictionary<string, object>}
+		[0]	{[Severity, ERROR]}	System.Collections.Generic.KeyValuePair<string, object>
+		[1]	{[SqlState, 22P03]}	System.Collections.Generic.KeyValuePair<string, object>
+		[2]	{[Code, 22P03]}	System.Collections.Generic.KeyValuePair<string, object>
+		[3]	{[MessageText, incorrect binary data format]}	System.Collections.Generic.KeyValuePair<string, object>
+		[4]	{[Where, COPY zzzprojects_973b718c_8d26_4bb3_a261_38dc26535b8d, line 1, column zzzpredicate_7]}	System.Collections.Generic.KeyValuePair<string, object>
+		[5]	{[File, copy.c]}	System.Collections.Generic.KeyValuePair<string, object>
+		[6]	{[Line, 4153]}	System.Collections.Generic.KeyValuePair<string, object>
+		[7]	{[Routine, CopyReadBinaryAttribute]}	System.Collections.Generic.KeyValuePair<string, object>
```

Here is some pseudo code of what I'm doing:
```
var items = _dataContext
    .Items
    .Take(100)
    .ToList();

var filteredItems = items.Where(someCondition).ToList();

foreach (var item in filteredItems)
{
    item.property1 = updatedValue1;
    item.property2 = updatedValue2;
}

await _dataContext.BulkSaveChangesAsync();
```

Do you have an idea of what the problem could be? When using the standard EF6 `SaveChangesAsync()` everything works fine.

**Comment by joelnotified** [comment]
Here are the actual logs from postgresql:

```
2017-09-27 15:04:59 CEST LOG:  execute <unnamed>: CREATE TEMP TABLE ZZZProjects_0b7ac9ed_d3cc_4eb7_a127_bc538349210b AS SELECT "name" AS "name", "url" AS "url", "originalurl" AS "originalurl", "domainreach" AS "domainreach", "description" AS "description", "sourcelogo" AS "sourcelogo", "processed" AS "processed", 0 AS ZZZPredicate_7, 0 AS ZZZ_Index FROM "public"."sources" LIMIT 0
2017-09-27 15:04:59 CEST LOG:  statement: COPY ZZZProjects_0b7ac9ed_d3cc_4eb7_a127_bc538349210b ("name","url","originalurl","domainreach","description","sourcelogo","processed",ZZZPredicate_7,ZZZ_Index) FROM STDIN BINARY
2017-09-27 15:04:59 CEST ERROR:  incorrect binary data format
2017-09-27 15:04:59 CEST CONTEXT:  COPY zzzprojects_0b7ac9ed_d3cc_4eb7_a127_bc538349210b, line 1, column zzzpredicate_7
2017-09-27 15:04:59 CEST STATEMENT:  COPY ZZZProjects_0b7ac9ed_d3cc_4eb7_a127_bc538349210b ("name","url","originalurl","domainreach","description","sourcelogo","processed",ZZZPredicate_7,ZZZ_Index) FROM STDIN BINARY
2017-09-27 15:04:59 CEST LOG:  statement: ROLLBACK
```

**Comment by JonathanMagnan** [comment]
Hello @joelnotified ,

Could you send me the class definition and the PostgreSQL schema.

This kind of error normally happens because of a wrong mapping.

You can send me in private to info@zzzprojects.com

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @joelnotified ,

The v3.13.1 has been released.

The issue should be now fixed. However, some similar issue could happen depending on the primary key type. We will need on ur side to find a more generic way to support this. If it happens, just open a new request and we will add this type as well.

Best Regards,

Jonathan

**Comment by joelnotified** [comment]
Seems to be working fine, thank you! 👍 ⭐️

**Comment by JonathanMagnan** [comment]
Great ;)
