### ISSUE TITLE
Invalid Cast. The update expression must be of type MemberInitExpression.

### ISSUE THREAD

**Issue by vinaykarora** [zzzprojects/EntityFramework-Extensions#564]
### Description
While attempting to use the UpdateFromQuery method from Entity Framework Extensions library to update an entity using an expression, an InvalidCastException is encountered. The exception message states that the update expression must be of type MemberInitExpression.

### Exception
System.Exception
Invalid Cast. The update expression must be of type MemberInitExpression.
  
```
System.Exception
  HResult=0x80131500
  Message=Invalid Cast. The update expression must be of type MemberInitExpression.
  Source=Z.EntityFramework.Extensions.EFCore
  StackTrace:
   at Z.EntityFramework.Extensions.BatchUpdate.ResolveUpdateFromQueryDictValues[T](Expression`1 updateFactory)
   at Z.EntityFramework.Extensions.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, IEntityType entity, Dictionary`2 convertToProviderDict)
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at TonguesProductionPlatform.Entities.Repositories.Definition.RepositoryAsync`2.UpdateDeAttachAsync(T entity, Expression`1 predicate) in D:\Projects\TTS\Repositories\Definition\RepositoryAsync.cs:line 69

```

### Further technical details
- .NET Core v6
- EF version: [EF Core v6.0.13]
- EF Extensions version: [EFE Core v6.101.1.2]
- Database Server version: [PostgreSQL]
- Database Provider version (NuGet): [Npgsql.EntityFrameworkCore.PostgreSQL v6.0.8]

**Comment by JonathanMagnan** [comment]
Hello @vinaykarora ,

Could you show us the code you are using for the `UpdateFromQuery`? That will surely help us to better understand why it's currently happening in your specific case.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @vinaykarora, 

Since our last conversation, we haven't heard from you. 

Could you show us the code you are using for the [UpdateFromQuery](https://entityframework-extensions.net/update-from-query)?

Best regards, 
Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Let me know if you need further support. 

Best regards, 

Jon
