### ISSUE TITLE
BulkInsertAsync throw errors not supporting ARRAY

### ISSUE THREAD

**Issue by packersland** [zzzprojects/EntityFramework-Extensions#586]
### Description
In Postgresql, there is a column of array of custom type. When running the BulkInsertAsync, it throws the exception with Unsupported Type ARRAY _custom_type

### Exception
```
Exception message: 
Oops! Unsupported types : ARRAY _custom_type

Stack trace:
 at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping, Boolean isOptimized)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges, Boolean isOptimized)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
```

### Further technical details

- EF version: [EF Core v8.0.2]
- EF Extensions version: [EFE Core v8.102.2.5]
- Database Server version: [Postgresql 15.4]

**Comment by JonathanMagnan** [comment]
Hello @packersland ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. Including your table creation.

Indeed, we don't support this kind of `_custom_type` array, but we will be happy to look at it if we receive a project to check if we can make it happen.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @packersland 

Since our last conversation, we haven't heard from you. 

Let me know if you need more information. 

Best regards, 

Jon

**Comment by packersland** [comment]
I decided to change my db schema to use other data type the Extension supports. I would like to know when the future release supports this. Thanks.

**Comment by JonathanMagnan** [comment]
Hello @packersland ,

To be honest, we would not investigate this issue more unless we get a project.

When we have a project, everything is way easier for us as we are sure to work on the right issue.

If you provide one, I will be more able to let you know when we plan to support this scenario in the future release.

Best Regards,

Jon

**Comment by packersland** [comment]
I will provide a running project later.
