### ISSUE TITLE
Batch Insert with SQLite 2

### ISSUE THREAD

**Issue by SerenaFA** [zzzprojects/EntityFramework-Extensions#605]
Got an exception when using Batch Insert with SQLite

Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Boolean]'.  

Source=Z.EntityFramework.Extensions.EFCore
  StackTrace:
   at Z.EntityFramework.Extensions.PropertyZInfo.SetValue( reader, Object item, Object value, String propertyName)
   at .`1.(Int32 , String , Object )
   at .( , DataSet , String , Boolean )
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping, Boolean isOptimized)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges, Boolean isOptimized)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)

**Comment by JonathanMagnan** [comment]
Hello @SerenaFA ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

At this moment, I do not believe we have enough information to try to reproduce it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @SerenaFA ,

The problem is really in the exception message: `Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Boolean]'.`

Why is an `Int64` currently mapping to a nullable bool?

At this moment, it is very hard to understand this problem without a project. From what I understand, you currently have a column of type `bigint` in your table, but you have a property of type `bool?` in your entity type. This scenario should throw this error without any code; this is our only hypothesis.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Dont hesitate to contact us if you need anything. 

Best regards, 
Jon
