### ISSUE TITLE
Trial not working

### ISSUE THREAD

**Issue by asiridissa** [zzzprojects/EntityFramework-Extensions#609]
### Description
I got the latest package installed. But it says it is expired.

### Exception
```
System.Exception
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at RideScheduler.Migration.MigrateV2.InsertWithMapUpdate[T1,T2](IEnumerable`1 map, Boolean includeGraph) in X.cs:line 2839
   at RideScheduler.Migration.MigrateV2.Begin() in X.cs:line 281
   at RideScheduler.Migration.Program.Main() in Program.cs:line 17

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: ERROR_005: The monthly trial period is expired (date: 2024-11-05, version: 8.103.6.0). You can extend your trial by downloading the latest version as the beginning of every month. If you already have purchased a license, you can find more common causes of this problem here: https://entityframework-extensions.net/trial```

### Further technical details

- EF version: [EF6]
- Database Server version: [SQL Server 2022]

**Comment by JonathanMagnan** [comment]
Hello @asiridissa  

Sorry for the inconvenience, we are currently working on releasing a new trial and it will be available shortly. 

The trial expires at the end of each month. We do not recommend that you use the trial in a production machine or client machine; Occasionally, there may be a lapse of a few days between releases. 

That said, we highly suggest that companies purchase a license so that they won’t have to update their production environment every month. 

Don't hesitate to contact us for further information regarding our product. 

Jon

**Comment by asiridissa** [comment]
Hey Jon,

**Comment by asiridissa** [comment]
Hi Jon,
Thanks for the quick response.
I'll check later.
