### ISSUE TITLE
Exception on Bulk Merge

### ISSUE THREAD

**Issue by david-garcia-garcia** [zzzprojects/EntityFramework-Extensions#79]
Reported this to info@, we need help investigating this random issue:

System.Exception : An error occured while resolving mapping by name. See the inner exception for details
---- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
Error stack trace:
   at Z.BulkOperations.BulkOperation. ()
   at  . . (BulkOperation )
   at Z.BulkOperations.BulkOperation.BulkMerge()
   at Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkMerge()
   at Z.EntityFramework.Extensions.InternalBulkOperationManager. [ ](BulkOperation`1  , DbContext  , List`1  , Boolean  , Type  , String  )
   at Z.EntityFramework.Extensions.InternalBulkOperationManager. . (SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Z.EntityFramework.Extensions.InternalBulkOperationManager. [ ](DbContext , BulkOperation`1 , IEnumerable`1 )
   at Z.EntityFramework.Extensions.InternalBulkOperationManager. [ ](BulkOperation`1 , DbContext , IEnumerable`1 )
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at ETG.SABENTISpro.Application.Modules.DataTest.Services.Sabentis.TestData.LoadData() in C:\projects\prime\ETG.SABENTISpro.Application.Modules\DataTest\Services\Sabentis\TestData.cs:line 50
   at ETG.SABENTISpro.Application.Modules.DataTest.DataTestModule.install(ApplicationInterface app) in C:\projects\prime\ETG.SABENTISpro.Application.Modules\DataTest\DataTestModule.cs:line 54
   at ETG.SABENTISpro.Application.Core.Module.ModuleManager.ModuleManager.installModules(List`1 modules) in C:\projects\prime\ETG.SABENTISpro.Application.Core\Module\ModuleManager\ModuleManager.cs:line 249
   at ETG.SABENTISpro.Application.Core.Kernel.App.restartApplication(Boolean autoInstallBootModules, Boolean skipBootEventTriggering) in C:\projects\prime\ETG.SABENTISpro.Application.Core\Kernel\Application.cs:line 249
   at ETG.SABENTISpro.Application.Core.Kernel.App..ctor(SettingsManagerInterface settingsManager) in C:\projects\prime\ETG.SABENTISpro.Application.Core\Kernel\Application.cs:line 99
   at ETG.SABENTISpro.Tests.PrimeBaseFixture.doInitializeTests(PrimeTestBaseInterface testObject, Boolean restoreDatabase) in C:\projects\prime\ETG.SABENTISpro.Tests\PrimeBaseFixture.cs:line 244
   at ETG.SABENTISpro.Tests.PrimeBaseFixture.EnsureInitialized(PrimeTestBaseInterface testObject, Boolean restoreDatabase) in C:\projects\prime\ETG.SABENTISpro.Tests\PrimeBaseFixture.cs:line 99
   at ETG.SABENTISpro.Tests.PrimeTestBase..ctor(PrimeBaseFixture proFixture, ITestOutputHelper output) in C:\projects\prime\ETG.SABENTISpro.Tests\PrimeTestBase.cs:line 44
   at ETG.SABENTISpro.Tests.Tests.Modules.Sabentis.TestPerson..ctor(PrimeBaseFixture proFixture, ITestOutputHelper output) in C:\projects\prime\ETG.SABENTISpro.Tests\Tests\Module\Sabentis\TestPerson.cs:line 31
----- Inner Stack Trace -----
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Z.BulkOperations.BulkOperation. ()
Std OUT:
Initializing test class: ETG.SABENTISpro.Tests.Tests.Modules.Sabentis.TestPerson
Required modules: sabentis, datatest

**Comment by david-garcia-garcia** [comment]
Looks like this might be related to several calls to currentContext.RefreshModel() we introduced in our application.

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

Yes, you are right. the `RefreshModel` is not thread-safe and may cause this kind of issue.

Could you remember me why you had to use this method?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Comment by david-garcia-garcia** [comment]
I think I have an idea of what is going on (after many hours of fighting this...).

ZZZ is internally using MemoryCache.Default + some internal static dictionaries.

When running several XUNIT tests in paralell for an application, XUNIT does not do Process Isolation (only application domain isolation) so basically... The contents of MemoryCache.Default LEAK between tests. Because the models are configured diferently in the different tests (properties ignored, etc...) this results in random failures.

Any chance that you could add an option to disable the usage of MemoryCache, or replace it's usage with some static storage?
