### ISSUE TITLE
BulkUpdate - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Raphael-Saldanha** [zzzprojects/EntityFramework-Extensions#90]
Any ideas to overcome the following issue?
   at (Object , String , StringComparison )
   at StringExtensions.(String , String )
   at ..(ComplexPropertyMapping , Schema )
   at Z.Internal.EntityFramework.Extensions.BLL.GetModel..(ComplexPropertyMapping )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Z.Internal.EntityFramework.Extensions.BLL.GetModel..(EntityTypeMapping )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Z.Internal.EntityFramework.Extensions.BLL.GetModel..(EntitySetMapping )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ..(Schema , Schema , SchemaMapping )
   at ..(Schema , SchemaMapping , Schema )
   at ..(String , String , String , String )
   at ..(DbContext )
   at DbContextExtensions.GetModel(DbContext this)
   at Z.EntityFramework.Extensions.BulkSaveChanges.(DbContext , List`1 , Action`1 )
   at DbContextExtensions.(DbContext , Boolean , Action`1 , Boolean )

**Comment by JonathanMagnan** [comment]
Hello @Raphael-Saldanha ,

We are not sure but it appears to happen when we read the model.

To fix it, we will need your EDMX file

Please see instruction here for Code First: http://entityframework-extensions.net/edmx

You can send it directly to us: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by Raphael-Saldanha** [comment]
It is related to complex type property, DayPrice, as show below


<EntityType Name="Price">
  <Key>
    <PropertyRef Name="MarketInstrumentID" />
  </Key>
  <Property Type="Int32" Name="MarketInstrumentID" Nullable="false" />
  <Property Name="DayPrice" Type="eBankView.Instruments.Repository.DayPrice" Nullable="false" />
  <Property Name="Timestamp" Type="Binary" Nullable="false" MaxLength="8" FixedLength="true" annotation:StoreGeneratedPattern="Computed" />          
</EntityType>
<ComplexType Name="DayPrice">
  <Property Type="String" Name="DataOriginCode" MaxLength="20" FixedLength="false" Unicode="true" />
  <Property Type="DateTime" Name="DeliveryDateTime" />
  <Property Type="DateTime" Name="RealPriceDateTime" />
  <Property Type="Decimal" Name="ClosingPrice" Precision="14" Scale="6" />
  <Property Type="Decimal" Name="AskPrice" Precision="14" Scale="6" />
  <Property Type="Decimal" Name="BidPrice" Precision="14" Scale="6" />
  <Property Type="DateTime" Name="LastUpdateTime" Nullable="false" />
  <Property Type="Decimal" Name="MarginRate" Precision="14" Scale="6" />
</ComplexType>

**Comment by JonathanMagnan** [comment]
Is it possible to have the full file?

It will make the investigation of this issue easier/faster and make sure to provide you a fix that will fully work.

As said, you can send it in private here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Raphael-Saldanha ,

The v3.14.14 has been released

Let me know if your model can now be read correctly.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Raphael-Saldanha ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
