### ISSUE TITLE
BatchDelete fails with NullReferenceException in EFCore 2.1 preview

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#95]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Z.EntityFramework.Plus.EFCore
  StackTrace:
   at Z.EntityFramework.Plus.InternalExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext)
   at Z.EntityFramework.Plus.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at Weiss.Ecesis.Data.Repositories.Data.DataValueRepository.BatchDelete(Int64 dataFieldId, DateTime startDate, DateTime endDate, Int32 batchSize) in C:\Source\Energy\Trunk\Ecesis\Source\Weiss.Ecesis.Data\Repositories\Data\DataValueRepository.cs:line 31
   at Weiss.Ecesis.Data.Tests.Repositories.Data.DataValueRepositoryTests.TestBatchDelete() in C:\Source\Energy\Trunk\Ecesis\Source\Weiss.Ecesis.Data.Tests\Repositories\Data\DataValueRepositoryTests.cs:line 48

This occurs rather a Where clause is included or not.
`Context.Set<DataValue>().Delete(x => x.BatchSize = 10)`
or 
`Context.Set<DataValue>().Where(x => x.StartDate < startDate).Delete(x => x.BatchSize = 10)`

**Comment by mmiller678** [comment]
Thanks for the quick response.  What is the difference between these two methods as I don't see the documentation for DeleteFromQuery.  Which one is the preferred usage?

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

They are pretty similar. In fact, they share the same code base. The batch methods in the `EFE` are more up to date.

We plan to remove both of these methods from `Entity Framework Plus` and offer them for free in our `Entity Framework Extensions` since that supported the same code twice in a different library doesn't make sense.

Best Regards,

Jonathan

**Comment by mmiller678** [comment]
Thanks for the update. Will look for the changes in EFE.
