### ISSUE TITLE
AddLicense - not working in Azure Function

### ISSUE THREAD

**Issue by keeleyj** [zzzprojects/EntityFramework-Extensions#98]
var zEntityLicenseKey = keyVaultClient.GetSecretAsync(Environment.GetEnvironmentVariable("AzureKeyVaultBaseUrl"), "ZEntityLicenseKey").Result;
            var zEntityLicenseName = keyVaultClient.GetSecretAsync(Environment.GetEnvironmentVariable("AzureKeyVaultBaseUrl"), "ZEntityLicenseName").Result;

            LicenseManager.AddLicense(zEntityLicenseName.Value, zEntityLicenseKey.Value);
            if (!LicenseManager.ValidateLicense(out var licenseErrorMessage))
            {
                throw new Exception(licenseErrorMessage);
            }

System.TypeInitializationException: The type initializer for 'Z.BulkOperations.LicenseManager' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.serviceModel. (C:\Users\Jim\AppData\Local\Azure.Functions.V2.Cli\func.dll.config line 204)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at Z.BulkOperations.LicenseManager..cctor()
   --- End of inner exception stack trace ---
   at Z.BulkOperations.LicenseManager.AddLicense(String licenseName, String licenseKey)
   at CannaSolFarms.DataSync.AzureFunctions.InjectConfiguration.RegisterServices(IServiceCollection services) in D:\CannaSolFarms\CannaSolFarms3.0\CannaSolFarms.DataSync.AzureFunctions\CannaSolFarms.DataSync.AzureFunctions\ExtractExcelDataToSqlServerCommandFunction.cs:line 158
   at CannaSolFarms.DataSync.AzureFunctions.InjectConfiguration.<Initialize>d__1.MoveNext() in D:\CannaSolFarms\CannaSolFarms3.0\CannaSolFarms.DataSync.AzureFunctions\CannaSolFarms.DataSync.AzureFunctions\ExtractExcelDataToSqlServerCommandFunction.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by keeleyj** [comment]
Thanks for the quick response,

I’m using  Core v 2.1.6

Jim

**Comment by JonathanMagnan** [comment]
Hello @keeleyj ,

The v2.1.9 has been released (will be available when nuget will index it)

We were not able to reproduce this issue in our environment but we believe the issue was happening in our static constructor when looking if a key has been registered in the `AppSettings` section which looks to be unavailable on your side.

We believe the new version will fix this issue (will check first if available).

Let me know if that's successfully working and if an error happens, please provide us the new stack trace if different.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @keeleyj 

We release a new version v2.1.10,

We got a strange error from the `NuGet Package` when we released, so we opted to create a new version instead.

Best Regards,

Jonathan

**Comment by keeleyj** [comment]
Thanks Jonathan,

That has resolved my issue.  Sure appreciate the quick turnaround.

Jim
